### DISCUSSION TITLE
Image tag gets removed sometimes on a new digest

### DISCUSSION THREAD

**Discussion by CSalih** [argoproj-labs/argocd-image-updater#1069] [Q&A] [answered]
Hi,

I do have some issues with the image updater. After some builds the image updater removes the tag of the image and only updates the digest in ".argocd-source-<..>.yml". This results that the images aren't updated in our k8s cluster. Is this a bug or is there a misconfiguration?

We use the nightly tag for the dev branch, it get updates several times a day. The updated build should be used directly in the k8s cluster. 

Our Application looks like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=registry.digitalocean.com/foo/web:nightly,api=registry.digitalocean.com/foo/api:nightly
    argocd-image-updater.argoproj.io/web.update-strategy: digest
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitlab-token
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: ...
    targetRevision: main
    path: foo
  destination:
    server: https://kubernetes.default.svc
    namespace: foo
```
And the deployment looks like:
```yaml
...
    spec:
      containers:
        - name: web
          image: registry.digitalocean.com/foo/web:nightly
          imagePullPolicy: Always
...
```

After the first build it generates the right image:
```yaml
kustomize:
  images:
  - registry.digitalocean.com/foo/web:nightly@sha256:9ff96a69b7a7e6683a5d94a063679a80be6b174680bd0cd562324fb2b183e7b7
  - registry.digitalocean.com/foo/api:nightly@sha256:84d57462894764331d4e2e321ec7e2aa4c1b4587d966aae6fa973e826989068e
```

But somehow after several updates it looks like:
```yaml
kustomize:
  images:
  - registry.digitalocean.com/foo/web:nightly@sha256:9ff96a69b7a7e6683a5d94a063679a80be6b174680bd0cd562324fb2b183e7b7
  - registry.digitalocean.com/foo/api:nightly@sha256:84d57462894764331d4e2e321ec7e2aa4c1b4587d966aae6fa973e826989068e
  - registry.digitalocean.com/foo/web@sha256:d86fbcfb2407b63d3e8a0e8697c060fcf7b0c81eb7edc1cf11feaa4a83b41c21
```
And the image `web:nightly` won't update, I guess it is because of the missing tag?
