### DISCUSSION TITLE
Is git write back needed for digest update strategy?

### DISCUSSION THREAD

**Discussion by NINNiT** [argoproj-labs/argocd-image-updater#869] [Q&A] [answered]
Hi,

I'm wondering wheter or not the git write back method is strictly needed for `digest` update strategies.

Example:

GitOps Repos:
app1-manifests
argocd-applicationsets

we use kustomize in app1-manifests and set the image there like this:
```
images:
  - name: image
    newName: myregistry.com/apps/frontend
    newTag: beta
```

this is our argocd-image-updater annotation in the application set:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: staging
                  url: https://cluster..local.eu:6443
                  image: myregistry.com/apps/frontend:beta
                  image_strategy: digest
          - list:
              elements:
                - namespace: namespace

  template:
    metadata:
      name: "{{.namespace}}-{{.environment}}-app1"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "image={{.image}}"
        argocd-image-updater.argoproj.io/image.update-strategy: "{{.image_strategy}}"
    spec:
      project: default
      source:
        repoURL: https://mygitlab.com/deployment/app1-manifests.git
        targetRevision: HEAD
        path: "{{.environment}}"
      destination:
        server: "{{.url}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

```
│ time="2024-09-23T16:42:22Z" level=info msg="Successfully updated image myregistry.com/apps/frontend@dummy' to 'myregistry.com/apps/frontend@sha256:4b37da38eba70826d24fbc18c281550ca0c236415c885e026e35a06f01003cbb', but pend....
│ time="2024-09-23T16:42:22Z" level=info msg="Committing 1 parameter update(s) for application app1" application=app     1                         
│ time="2024-09-23T16:42:23Z" level=info msg="Successfully updated the live application spec" application=app1
│ time="2024-09-23T16:42:23Z" level=info msg="Processing results: applications=2 images_considered=2 images_skipped=0 images_updated=2 errors=0"                                                                                                        │
...
```

Even though, looking at the logs, the update seems to work, my pods will not restart and will not use the new hash instead of the beta tag.
After 2 minutes, i get the same log message again. 

Thanks for the help! <3
