### DISCUSSION TITLE
How to update the image inside list of container in helm values ?

### DISCUSSION THREAD

**Discussion by Ah-Khai** [argoproj-labs/argocd-image-updater#951] [Q&A]
I cant find any example or solution.

i have a helm values 
```
template:
  spec:
    initContainers:
      - name: containers 1
        image: "my-repo:latest"
```

how do i update the image value using which the image is inside the template
example
`argocd-image-updater.argoproj.io/my-repo.helm.image-spec: template.spec.initContainers.0.image`

**Comment by chengfang** [comment]
Can you use non-list values, for example in you helm values file,
```yaml
  image1:
   name: image1
   tag: latest
  image2:
```
