### DISCUSSION TITLE
How to use helm.image-tag correctly

### DISCUSSION THREAD

**Discussion by ForcemCS** [argoproj-labs/argocd-image-updater#990] [Q&A]
I'm trying something about argocd and the argocd image updater.

```
root@debian:~/alls-hdh5/helmfile_charts# tree  -L 4   hdh5/
hdh5/
├── helmfile.yaml
└── servers
    ├── Chart.yaml
    ├── servers.yaml
    ├── templates
    │   ├── configmap-main.yaml
    │   ├── deployment.yaml
    │   ├── forward-service.yaml
    │   ├── _helpers.tpl
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   └── service.yaml
    └── values.yaml

3 directories, 11 files

root@debian:~/alls-hdh5/helmfile_charts# cat hdh5/servers/servers.yaml 
server:
- id: 10030
  name: operation
  runtype: 0
  siteid: 1
  parent: 0
  fight: flight01
  trade: trans01
  repo: xxxxxxxxx
  image: hdh5test
  tag: "20241204203734"
  opentime: 2024-12-05T10:14:22+08:00
  db: xxxxxx:30009:30:ccccccc
  maintenance: 0
  shutdown: 0
  shenhe: 0
  gm: 1
  debug: 0
  accesslimit: ""
  thread: 8
  agent: 8
  maxclient: 10000
  maxregist: 8
  mergetime: 2000-01-01T00:00:00+08:00
  modifytime: 2024-12-05T17:09:48+08:00

```

The above are the structures I used with helmfile cmp. They are working as expected. I'm currently trying to use argocd image updater, and I'm wondering how I should specify the tracked image
```
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: <How should I write？>
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: <How should I write？>
```

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hdh5-game
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: sandbox-txcloud
        describe: sandbox
        region: shanghai
        proj: hdh5
        namespace: hdh5
        cluster: in-cluster
  template:
    metadata:
      name: '{{.describe}}-{{.proj}}-game'
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: git
       #argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/auth-registry-secret
        argocd-image-updater.argoproj.io/image-list: hdh5-game=xxxxxxxxx/proj_hdh5/hdh5server
        argocd-image-updater.argoproj.io/hdh5-game.update-strategy: name
        argocd-image-updater.argoproj.io/hdh5-game.allow-tags: regexp:^master-[0-9]{8}-[0-9]{2}-[0-9]{2}-[0-9]{2}$
        argocd-image-updater.argoproj.io/hdh5-game.force-update: "true"
        argocd-image-updater.argoproj.io/pull-policy: Always
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: <How should I write？>
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: <How should I write？>

    spec:
      project: team-a
      sources:
      - repoURL: xxxxxxxxxxxxxxx/alls-hdh5.git
        path: helmfile_charts/hdh5
        targetRevision: HEAD
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true

```
