### DISCUSSION TITLE
How to track helm image-tag

### DISCUSSION THREAD

**Discussion by ForcemCS** [argoproj-labs/argocd-image-updater#992] [General]
I'm using argocd image updater to keep track of images and the following structure is working fine
```
root@debian:~/alls-hdh5/helm_charts/datacenter-backend# cat values.yaml 
image:
  repo: example/gz-xjcsro-1036/datacenter
  tag: master-20241031-10-28-26
root@debian:~/alls-hdh5/appsets# cat datacenter-backend.yaml 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hdh5-game
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: sandbox-txcloud
        describe: sandbox
        region: shanghai
        proj: hdh5
        namespace: hdh5
        cluster: in-cluster
  template:
    metadata:
      name: '{{.describe}}-{{.proj}}-game'
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/image-list: hdh5-game=tcr.xxxxxxxx/proj_hdh5/hdh5server
        argocd-image-updater.argoproj.io/hdh5-game.update-strategy: name
        argocd-image-updater.argoproj.io/hdh5-game.allow-tags: regexp:^dev-[0-9]{8}-[0-9]{2}-[0-9]{2}-[0-9]{2}$
        argocd-image-updater.argoproj.io/hdh5-game.force-update: "true"
        argocd-image-updater.argoproj.io/pull-policy: Always
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: 'xx'
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: 'xx'
```

But I want to change the structure of the values.yaml file as follows, how should my applicationset resource be modified
```
image:
- id: 10001
  repo: example/gz-xjcsro-1036/datacenter
  tag: master-20241031-10-28-26
- id: 10002
  repo: example/gz-xjcsro-1036/datacenter
  tag: master-20241031-10-xxx
```
