### DISCUSSION TITLE
How to track images defined in common files

### DISCUSSION THREAD

**Discussion by ForcemCS** [argoproj-labs/argocd-image-updater#993] [Q&A]
I'm trying something about argocd and the argocd image updater.
```
root@debian:~/alls-hdh5/helmfile_charts# tree  -L 4   hdh5/
hdh5/
├── helmfile.yaml
└── servers
    ├── Chart.yaml
    ├── servers.yaml
    ├── templates
    │   ├── configmap-main.yaml
    │   ├── deployment.yaml
    │   ├── forward-service.yaml
    │   ├── _helpers.tpl
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   └── service.yaml
    └── values.yaml

3 directories, 11 files

root@debian:~/alls-hdh5/helmfile_charts# cat hdh5/servers/servers.yaml 
server:
- id: 10030
  repo: xxxxxxxxx:port/cccc
  image: hdh5test
  tag: "20241204203734"
```

The above are the structures I used with helmfile cmp. They are working as expected. I'm currently trying to use argocd image updater, and I'm wondering how I should specify the tracked image
```
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: <How should I write？>
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: <How should I write？>\
```
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hdh5-game
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
    .......
  template:
    metadata:
      name: '{{.describe}}-{{.proj}}-game'
      annotations:
	    ....................
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: <How should I write？>
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: <How should I write？>

    spec:
      project: team-a
      sources:
      - repoURL: xxxxxxxxxxxxxxx/alls-hdh5.git
        path: helmfile_charts/hdh5
        targetRevision: HEAD
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
```
I think it's very important to note that servers.yaml is not an additional value file, but a regular file. This file is called in the deployment
```
{{ $global := . }}
{{- $data   := .Files.Get "servers.yaml" | fromYaml }}
{{- range $counts := $data.server }}
{{- if eq ( int $counts.shutdown ) 0 }}
{{- if and ( eq ( int $counts.parent ) 0 ) ( not (hasKey $.Values.forwardServer ( $counts.id | toString )) ) }}
{{- $main   := "main_logic"  }}
{{- $gl := "global_logic"  }}
{{- $log    := "main_log_logic"  }}
apiVersion: apps/v1
kind: Deployment
metadata:

```
