### DISCUSSION TITLE
Unable to track changes to mirror versions

### DISCUSSION THREAD

**Discussion by ForcemCS** [argoproj-labs/argocd-image-updater#994] [Q&A]
Below is my helmfile plugin, he is working fine, but I don't understand why it can't track changes to my mirrors? However helm is fine
```
root@debian:~/alls-hdh5/appsets# cat hdh5-game.yaml 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hdh5-game
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: sandbox-txcloud
        describe: sandbox
        region: shanghai
        proj: hdh5
        namespace: hdh5
        cluster: in-cluster
  template:
    metadata:
      name: '{{.describe}}-{{.proj}}-game'
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: git
       #argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/auth-registry-secret
        argocd-image-updater.argoproj.io/image-list: hdh5-game=tcr.xxxxxx:20443/proj_hdh5/hdh5server
        argocd-image-updater.argoproj.io/hdh5-game.update-strategy: name
        argocd-image-updater.argoproj.io/hdh5-game.allow-tags: regexp:^dev-[0-9]{8}-[0-9]{2}-[0-9]{2}-[0-9]{2}$
        argocd-image-updater.argoproj.io/hdh5-game.force-update: "true"
        argocd-image-updater.argoproj.io/pull-policy: Always
    spec:
      project: team-a
      sources:
      - repoURL: git@xxxxxx.com:mixture-proj/alls-hdh5.git
        path: helmfile_charts/hdh5
        targetRevision: HEAD
        plugin:
          name: helmfile
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: server[0].image
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: server[0].tag
```
Then I watch the logs of the image updater
```
time="2025-01-06T09:51:46Z" level=warning msg="skipping app 'argocd/sandbox-hdh5-game' of type 'Plugin' because it's not of supported source type" application=sandbox-hdh5-game namespace=argocd
time="2025-01-06T09:51:46Z" level=info msg="Starting image update cycle, considering 3 annotated application(s) for update"
time="2025-01-06T09:51:46Z" level=warning msg="\"name\" strategy has been renamed to \"alphabetical\". Please switch to the new convention as support for the old naming convention will be removed in future versions." image_alias=datacenter image_name="tcr.xxxxxx.com:20443/proj_datacenter/datacenter" registry_url="tcr.xxxxxx.com:20443"

```
