### ISSUE TITLE
Ineffective custom helm values file with write-back-target annotation

### ISSUE THREAD

**Issue by fabiobozzo** [argoproj-labs/argocd-image-updater#1004]
**Describe the bug**
I've recently enabled the image updater on our existing rollout process.  
The image is updated correctly, once I push a new tag of it to our private ECR repo. ArgoCD detects a new presence and deploys it to the corresponding application in our dev environment.  

The bug affects the Git write-back method. Although I specify my existing Helm values file as the target, ArgoCD commits a new file, inside the chart's folder.

**To Reproduce**
 My application is configured w/ the following annotations: 
```
billing:
      repoURL: https://github.com/myorg/argocd-workloads-repo.git
      path: charts/billing
      targetRevision: main
      valueFiles:
        - /multi-repo/argo-app-of-apps/dev/billing-values.yaml
      annotations:
        argocd-image-updater.argoproj.io/image-list: billing=00000000000.dkr.ecr.us-east-1.amazonaws.com/myorg/myrepo/billing
        argocd-image-updater.argoproj.io/billing.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: "helmvalues:../../multi-repo/argo-app-of-apps/dev/billing-values.yaml"
        argocd-image-updater.argoproj.io/billing.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/billing.helm.image-tag: image.tag
```

**Expected behavior**
I expect ArgoCD to update the `image.tag` field in the existing file I specified as `write-back-target` ( which we used to manage manually ) instead of creating one in what he thinks it's the default path. 

**Additional context**

Repository Root
```
│
├── charts/
│   └── billing/
│       ├── .argocd-source-billing.yaml    # Created here instead of updating values file
│       └── [other chart files]
│
└── multi-repo/
    └── argo-app-of-apps/
        └── dev/
            ├── values.yaml                 # Contains app-of-apps config with image updater annotations
            └── billing-values.yaml         # Should be updated but isn't
```

Key Files:
1. /multi-repo/argo-app-of-apps/dev/values.yaml
   - Contains image updater config:
     ```yaml
     argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/multi-repo/argo-app-of-apps/dev/billing-values.yaml"
     ```

2. /multi-repo/argo-app-of-apps/dev/billing-values.yaml
   - Contains values that should be updated:
     ```yaml
     image:
       repository: 0000000000.dkr.ecr.us-east-1.amazonaws.com/myorg/myrepo/billing
       tag: master-bef7237
     ```

3. /charts/billing/.argocd-source-billing.yaml
   - Created instead of updating billing-values.yaml:
     ```yaml
     helm:
       parameters:
       - name: image.repository
         value: 0000000000.dkr.ecr.us-east-1.amazonaws.com/myorg/myrepo/billing
         forcestring: true
       - name: image.tag
         value: argocd-image-updater-dev-7159c44
         forcestring: true
     ```

**Version**
```
kubectl get deployment argocd-image-updater -n argocd -o=jsonpath='{.spec.template.spec.containers[0].image}'
quay.io/argoprojlabs/argocd-image-updater:v0.12.2
```

**Logs**
```
time="2025-01-10T11:26:10Z" level=info msg="Successfully updated image '00000000000.dkr.ecr.us-east-1.amazonaws.com/myorg/myrepo/billing:argocd-image-updater-dev-ef4150c' to '00000000000.dkr.ecr.us-east-1.amazonaws.com/myorg/myrepo/billing:argocd-image-updater-dev-80fde7d', but pending spec update (dry run=false)" alias=billing application=billing image_name=myorg/myrepo/billing image_tag=argocd-image-updater-dev-ef4150c registry=00000000000.dkr.ecr.us-east-1.amazonaws.com
time="2025-01-10T11:26:10Z" level=info msg="Committing 1 parameter update(s) for application billing" application=billing
time="2025-01-10T11:26:10Z" level=info msg="Starting configmap/secret informers"
time="2025-01-10T11:26:11Z" level=info msg="Configmap/secret informer synced"
time="2025-01-10T11:26:11Z" level=info msg="secrets informer cancelled"
time="2025-01-10T11:26:11Z" level=info msg="Initializing https://github.com/myorg/argocd-workloads-myrepo.git to /tmp/git-billing2412957573"
time="2025-01-10T11:26:11Z" level=info msg="configmap informer cancelled"
time="2025-01-10T11:26:11Z" level=info msg="rm -rf /tmp/git-billing2412957573" dir= execID=93685
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[rm -rf /tmp/git-billing2412957573]" dir= operation_name="exec rm" time_ms=0.593046
time="2025-01-10T11:26:11Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git-billing2412957573 execID=27c8c
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git-billing2412957573 operation_name="exec git" time_ms=786.499686
time="2025-01-10T11:26:11Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-billing2412957573 execID=8f951
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-billing2412957573 operation_name="exec git" time_ms=0.883429
time="2025-01-10T11:26:11Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-billing2412957573 execID=a98d5
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-billing2412957573 operation_name="exec git" time_ms=0.841534
time="2025-01-10T11:26:11Z" level=info msg="git checkout --force main" dir=/tmp/git-billing2412957573 execID=3677f
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[git checkout --force main]" dir=/tmp/git-billing2412957573 operation_name="exec git" time_ms=14.635403
time="2025-01-10T11:26:11Z" level=info msg="git clean -fdx" dir=/tmp/git-billing2412957573 execID=8773f
time="2025-01-10T11:26:11Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/git-billing2412957573 operation_name="exec git" time_ms=1.189294
time="2025-01-10T11:26:11Z" level=info msg="Successfully updated the live application spec" application=billing
time="2025-01-10T11:26:11Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"
```
