### ISSUE TITLE
Broken annotation "argocd-image-updater.argoproj.io/image-list" if there is more than one image in it

### ISSUE THREAD

**Issue by onesb23** [argoproj-labs/argocd-image-updater#1008]
**Describe the bug**
If multiple images are listed, only the last one is applied.

**To Reproduce**
An application that contains the following annotations:
```
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myregistry/myimage1:prod,myregistry/myimage2:prod
    argocd-image-updater.argoproj.io/update-strategy: digest
```
According to the documentation, the corresponding kustomize should be processed and created:
```
spec:
  source:
    kustomize:
      images:
      - myregistry/myimage1:prod@sha256:blobloblo...
      - myregistry/myimage2:prod@sha256:blablabla...
```
In real life, this kustomize is created:
```
spec:
  source:
    kustomize:
      images:
        myregistry/myimage2@sha256:blablabla...
```

**Expected behavior**
I expect this to work correctly.

**Additional context**
This worked on some previous version, but rolling back to previous versions does not fix the problem.

**Version**
v0.15.2

**Logs**
In the log at each interval of synchronization with the registry there are such messages:
```
time="2025-01-10T16:03:34Z" level=info msg="Committing 1 parameter update(s) for application myapp" application=myapp
time="2025-01-10T16:03:35Z" level=info msg="Successfully updated the live application spec" application=myapp
time="2025-01-10T16:03:35Z" level=info msg="Processing results: applications=9 images_considered=8 images_skipped=3 images_updated=1 errors=0"
time="2025-01-10T16:04:06Z" level=info msg="Starting image update cycle, considering 8 annotated application(s) for update"
time="2025-01-10T16:04:07Z" level=info msg="Setting new image to myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
time="2025-01-10T16:04:07Z" level=info msg="Successfully updated image 'myimage2:prod@dummy' to 'myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36', but pending spec update (dry run=false)" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
time="2025-01-10T16:04:07Z" level=info msg="Committing 1 parameter update(s) for application myapp" application=myapp
time="2025-01-10T16:04:08Z" level=info msg="Successfully updated the live application spec" application=myapp
time="2025-01-10T16:04:08Z" level=info msg="Processing results: applications=9 images_considered=8 images_skipped=3 images_updated=1 errors=0"
time="2025-01-10T16:04:38Z" level=info msg="Starting image update cycle, considering 8 annotated application(s) for update"
time="2025-01-10T16:04:39Z" level=info msg="Setting new image to myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
time="2025-01-10T16:04:39Z" level=info msg="Successfully updated image 'myimage2:prod@dummy' to 'myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36', but pending spec update (dry run=false)" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
time="2025-01-10T16:04:40Z" level=info msg="Committing 1 parameter update(s) for application myapp" application=myapp
time="2025-01-10T16:04:41Z" level=info msg="Successfully updated the live application spec" application=myapp
time="2025-01-10T16:04:41Z" level=info msg="Processing results: applications=9 images_considered=8 images_skipped=3 images_updated=1 errors=0"
time="2025-01-10T16:05:11Z" level=info msg="Starting image update cycle, considering 8 annotated application(s) for update"
time="2025-01-10T16:05:12Z" level=info msg="Setting new image to myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
time="2025-01-10T16:05:12Z" level=info msg="Successfully updated image 'myimage2:prod@dummy' to 'myimage2:prod@sha256:9d2f8f8fb12f01697cd212f1fb79cca11a32d8120243a384e9cab153ad576c36', but pending spec update (dry run=false)" alias= application=myapp image_name=myimage2 image_tag=dummy registry="myregistry"
```
In fact, the image in the pod is not updated.
If the first or second image is specified, but only one, the pod update is successful.

**Comment by chengfang** [comment]
I tested with my sample app (https://github.com/chengfang/image-updater-examples/tree/main/image-list-kustomize) with image-updater v0.15.2, and works as expected. This app configures 2 updateable images with `image-list` annotation, and after running image-updater, the created target file `.argocd-source-xxx` contains entries for both images. See https://github.com/chengfang/image-updater-examples/blob/main/image-list-kustomize/source/.argocd-source-image-list-kustomize.yaml

**Comment by onesb23** [comment]
> I tested with my sample app (https://github.com/chengfang/image-updater-examples/tree/main/image-list-kustomize) with image-updater v0.15.2, and works as expected. This app configures 2 updateable images with `image-list` annotation, and after running image-updater, the created target file `.argocd-source-xxx` contains entries for both images. See https://github.com/chengfang/image-updater-examples/blob/main/image-list-kustomize/source/.argocd-source-image-list-kustomize.yaml

Your example is completely unrepresentative. You are using a completely different update-strategy. Moreover, you are using the write-back-method - git. I want to use default settings where possible.

**Comment by onesb23** [comment]
To rule out possible problems specific to my installation that could have arisen historically, I completely removed all argocd resources including the namespace. I reinstalled everything and the behavior changed a bit:
In the customization there is now a list, but there is still only the last image from the list. And even it updates the pod incorrectly.
```
spec:
  source:
    kustomize:
      images:
      - myimage2@sha256:blablabla...
```
But it should be like this:
```
spec:
  source:
    kustomize:
      images:
      - myimage1:prod@sha256:blobloblo...
      - myimage2:prod@sha256:blablabla...
```
