### ISSUE TITLE
helm values.yaml updates do not work with lists

### ISSUE THREAD

**Issue by aburan28** [argoproj-labs/argocd-image-updater#1032]
**Describe the bug**
when using the image updater in git write back mode the image updater does not update values in the values.yaml file when the image.tag/name have lists.

an example 
```yaml
images:
  - name: blah
    image: quay.io/animage
    tag: v0.0.1
```

annotations 
```yaml

argocd-image-updater.argoproj.io/image-list: test=quay.io/animage
argocd-image-updater.argoproj.io/test.helm.image-name: images.0.image
argocd-image-updater.argoproj.io/test.helm.image-tag: images.0.tag

```

ultimately it picks up the image change but instead of updating it in place within the list of images it will add to the bottom of the values.yaml which ultimately does not trigger the image to be updated properly. 

```yaml
images[0]:
  - tag: v1.0.0 
```

The issue seems to be caused by the `setHelmValue` function which incorrectly assumes that the structure of the values is a map. https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/update.go#L575

**To Reproduce**
See above. 

**Expected behavior**
an update is made to the values.yaml as shown below  

```yaml
images:
  - name: blah
    image: quay.io/animage
    tag: v1.0.0

```

**Additional context**

**Version**
0.15.2

Note feel free to assign this issue to me. I'm happy to open up a pr to fix this
