### ISSUE TITLE
Duplicate image entries with different formats when updating two images

### ISSUE THREAD

**Issue by etanase** [argoproj-labs/argocd-image-updater#1034]
**Describe the bug**
When updating the hash of one image using git method and digest strategy, argocd creates a copy of the other image without the ":latest" tag. This results in the containers not being re-created and remaining on the old images. This can be resolved by manually removing the hashes without the latest tag (after each update). For example, this is what the yaml looks like after attempting to update both images:
```yaml
# .argocd-source-app.yaml
kustomize:
  images:
  - ghcr.io/org/repo/image-a:latest@sha256:new-hash
  - ghcr.io/org/repo/image-b:latest@sha256:new-hash
  - ghcr.io/org/repo/image-a@sha256:old-hash
  - ghcr.io/org/repo/image-b@sha256:old-hash
```

**To Reproduce**
Have an application that uses two different images, and use these parameters:
```yaml
argocd-image-updater.argoproj.io/update-strategy: digest
argocd-image-updater.argoproj.io/write-back-method: git
```

**Expected behavior**
The image is updated with the latest tag, and no other entries are created.

**Version**
v0.15.2
