### ISSUE TITLE
Help with updating TAG

### ISSUE THREAD

**Issue by bottlesbo** [argoproj-labs/argocd-image-updater#1036]
# **Request for Assistance: ArgoCD Image Updater Not Updating Rollout Image**

**Dear [Team/Developers],**

I am seeking help with an issue involving ArgoCD Image Updater during deployment. Although the logs indicate that the image tag was successfully updated, the changes are not being applied to the Rollout resource in Kubernetes. Below are the details of the problem and the current configuration.

---

## **Issue Description**
- The ArgoCD Image Updater logs show that the image tag was successfully updated from `10055` to `10059`:
  ```log
  time="2025-02-09T15:06:31Z" level=info msg="Successfully updated image 'gitlab.sber.data1861.ru:5050/developers/frontend/frontend-landing-page/frontend-landing-page:10055' to 'gitlab.sber.data1861.ru:5050/developers/frontend/frontend-landing-page/frontend-landing-page:10059', but pending spec update (dry run=false)" alias=frontend-landing-page application=frontend-landing-page image_name=developers/frontend/frontend-landing-page/frontend-landing-page image_tag=10055 registry="gitlab.sber.data1861.ru:5050"

However, the new image tag (10059) is not reflected in the Rollout resource in the cluster. The changes remain in the "pending spec update" state, and the deployment does not proceed.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-chart-rollout
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@gitlab.sber.data1861.ru:devops/helm-data1861.git
        revision: HEAD
        directories:
          - path: app-charts-rollout/frontend-landing-page
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{path.basename}}=gitlab.sber.data1861.ru:5050/developers/frontend/frontend-landing-page/frontend-landing-page'
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/{{path.basename}}.update-strategy: semver
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/{{path.basename}}.helm.image-tag: "image.tag"
    spec:
      project: data1861
      source:
        repoURL: git@gitlab.sber.data1861.ru:devops/helm-data1861.git
        targetRevision: HEAD
        path: app-charts-rollout/{{path.basename}}
        helm:
          valueFiles:
            - envs/common/commonenv.yaml
            - envs/dev/values.yaml
            - envs/dev/env.yaml
          parameters:
            - name: image.name
              value: gitlab.sber.data1861.ru:5050/developers/frontend/frontend-landing-page/frontend-landing-page
            - name: image.tag
              value: '{{image.tag}}'
          version: v3
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

```

```
image:
  repository: gitlab.sber.data1861.ru:5050/developers/frontend/frontend-landing-page/frontend-landing-page
  tag: "10055"
```

Observed Behavior
The Image Updater logs indicate that the update process succeeded, but the updated tag (10059) is not applied to the Rollout resource.
There are no errors in the logs, but the Rollout continues to use the old tag (10055).
Expected Behavior
The new image tag (10059) should be applied to the Rollout resource, and the deployment process should proceed automatically.
Questions
Are there any additional settings required in the ApplicationSet or Helm Chart to ensure the updated image tag is applied to the Rollout resource?
Could the issue be related to passing the image.tag parameter in the Helm Chart?
Are there any specific debugging steps or configurations that we should check to resolve this issue?
Request
Please review the provided configurations and logs to identify possible errors or missing steps.
If possible, share guidance or an example of a working configuration where the Image Updater successfully updates the Rollout resources.
Thank you in advance for your assistance. If additional data or logs are required for further analysis, please let me know.

**Comment by huehnerhose** [comment]
I do not have an answer, but the same question/problem.

And would like to add how the subquestion: How does this work with git as write-back-method?

**Comment by chengfang** [comment]
If you're using appset, there are similar issues reported, and possible solutions in https://github.com/argoproj-labs/argocd-image-updater/issues/400

**Comment by andrebrkk** [comment]
Same problem here.

I using ArgoCD on version v2.14.2
And helm argocd-image-update:0:12.0

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: front-end=registry.org/front-end-image
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/front-end.update-strategy: newest-build
    argocd-image-updater.argoproj.io/front-end.allow-tags: regexp:^stg-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/front-end.pull-secret: secret:argocd/registry-credentials#creds
    argocd-image-updater.argoproj.io/front-end.force-update: "true
```

The ArgoCD Image Updater logs show that the image tag was successfully updated from `stg` to `stg-a38cf147f3cb73606c5ad337a83a0b735c155ed1`

```
time="2025-02-18T13:02:08Z" level=info msg="Successfully updated image 'registry.org/front-end-image:stg' to 'registry.org/front-end-image:stg-a38cf147f3cb73606c5ad337a83a0b735c155ed1', but pending spec update (dry run=false)" alias=front-end application=front-end image_name=front-end-image image_tag=stg registry=registry.org
```

**Comment by chengfang** [comment]
In my local testing, `git` write-back-method is working fine: the target file in the target repo is properly updated, and after the configured interval, the running app state is also updated. In a [previous issue](https://github.com/argoproj-labs/argocd-image-updater/issues/964#issuecomment-2541642848), I put the following comment and they may be also relevent here:

> for non-applicationset cases, things to double check:
> 
> * if argocd auto-sync is enabled to sync from git repo
> * if the interval has passed
> * if argocd syncs from the repo and branch that contains the updates from image-updater

**Comment by andrebrkk** [comment]
@chengfang, I discovered a pattern related to this problem. In my case, I have a local registry, this Registry has over 60 images, when the image goes from 49, Image-Update cannot apply to deployment. 

I did several tests, renamed image for ```zfront-val``` and did not work, but when I put ```front-val``` it worked, because it was above 49, I did another test by placing the image as ```safront-web``` and the image was in position 50 and did not work either, could see this pattern.

```https://my.registry.com/v2/_catalog```

```
{
{
  "repositories": [
    "acea-front",
    "acess-api",
    "cad-ad",
    "cb.app.api.inventory",
    "cf.srv.api",
    "con-web",
    "cs-di",
    "cs-g",
    "cs-gc",
    "cs-i",
    "cs-or",
    "cs-pay",
    "cs-pay-back",
    "cs-pe",
    "cs-pro",
    "cs-pro-c",
    "cs-sc",
    "cs-sg",
    "dr-api",
    "dr-web",
    "dig-api",
    "est-web",
    "eti-di-strapi",
    "front-ass",
    "front-des-on",
    "front-di",
    "front-ju",
    "front-me",
    "front-mi",
    "front-mod",
    "front-pe",
    "front-port",
    "front-prot",
    "front-val",
    "front-vi",
    "ini",
    "ju-api",
    "kold",
    "mailing",
    "me-api",
    "mi-api",
    "mod-api",
    "o-doc-api",
    "pay-web",
    "pay-web-admin",
    "pe-api",
    "po-ad",
    "pro-auth",
    "pro-online-api",
    "safront-web",
    "sec-auth",
    "sec-web",
    "seg-api",
    "sge-in-api",
    "sge-in-seg-api",
    "svc-tr",
    "ubuntu",
    "val-web",
    "val-web2",
    "zfront-val"
  ]
}
```

**Comment by chengfang** [comment]
@andrebrkk That's odd. When running image updater with any public registries or big private registries, there are thousands of images in teh registry, and they all work fine. Accessing an image is directly via its url like "docker.io/nginx", and is not sequential and its position in the registry catalog should not matter. Could it be a capacity issue of your registry?

**Comment by andrebrkk** [comment]
@chengfang I did a test uploading the image to the docker hub and the same problem occurred.

![Image](https://github.com/user-attachments/assets/2e4a9cd4-1e20-4bc6-bd9a-f47d0220449c)

![Image](https://github.com/user-attachments/assets/037af335-3b7a-444e-a38c-7da59bad14ab)

![Image](https://github.com/user-attachments/assets/feb736b2-7d10-4519-b465-d002170b0c2a)

Argocd-image-updater create file .argocd-source-validador-web-hom-troubleshooting.yaml, but not apply on deployments
![Image](https://github.com/user-attachments/assets/0748d326-b745-4aea-bf05-34d219e52214)

My application

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: validador-web-hom-troubleshooting
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: validador_web_hom_troubleshooting=andreagmatos/validador-web
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/validador_web_hom_troubleshooting.update-strategy: newest-build
    argocd-image-updater.argoproj.io/validador_web_hom_troubleshooting.allow-tags: regexp:^prod-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/validador_web_hom_troubleshooting.pull-secret: secret:argocd/registry-credentials-troubleshooting#creds
    argocd-image-updater.argoproj.io/validador_web_hom_troubleshooting.force-update: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: validador-web-hom-troubleshooting

spec:
  project: default
  source:
    repoURL: git@github.com:myrepo/gitops.git
    path: apps/manifests/validador-web/overlays/hom
    targetRevision: main
  destination:
    name: my-cluster.local
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 4
      backoff:
        duration: 15s
        factor: 5
        maxDuration: 5m0s
  revisionHistoryLimit: 4
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: validador-web
      namespace: default
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jqPathExpressions:
        - .spec.metrics[].resource.name | select((. == "cpu") or (. == "memory"))
    - kind: Secret
      name: validador-web
      jsonPointers:
        - /data
        - /stringData

```
