### ISSUE TITLE
Aliases containing slashes cannot be used in annotations

### ISSUE THREAD

**Issue by mgoodness** [argoproj-labs/argocd-image-updater#106]
**Describe the bug**
Per the [docs](https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#custom-images-with-kustomize), the correct way to use argocd-image-updater with Kustomize is to use the image name (e.g. `argoproj/argocd`) as an alias. However, Kubernetes only allows one slash in an annotation key, so I'm unable to use the alias for other argocd-image-updater options.

**To Reproduce**
1. Create a Kustomize overlay with a slash in the image name:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: hjacobs/kube-resource-report
namespace: kube-resource-report
resources:
  - github.com/hjacobs/kube-resource-report/deploy?ref=20.7.3
```
2. Create an Application manifest pointing to the overlay, with argocd-image-updater annotations:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: hjacobs/kube-resource-report=<container_repo_url>/kube-resource-report
    argocd-image-updater.argoproj.io/hjacobs/kube-resource-report.update-strategy: latest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kube-resource-report
  namespace: argocd
spec:
  destination:
    namespace: kube-resource-report
    server: https://kubernetes.default.svc
  project: cluster-services
  source:
    path: kube-resource-report/
    repoURL: <config_repo_url>
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
```
**Expected behavior**
Creation of an Argo CD Application that continuously deploys the latest version of the `<container_repo_url>/kube-resource-report` container image.

**Version**
0.7.0

**Logs**
```shell
error="Application.argoproj.io \"cluster-services-krr-bdatasf-npd-us-east4-ng\" is invalid: metadata.annotations: Invalid value: \"argocd-image-updater.argoproj.io/hjacobs/kube-resource-report.update-strategy\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')"
2020-10-01T20:36:15.016Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "applicationset", "name": "cluster-services-kube-resource-report", "namespace": "argocd", "error": "Application.argoproj.io \"cluster-services-krr-bdatasf-npd-us-east4-ng\" is invalid: metadata.annotations: Invalid value: \"argocd-image-updater.argoproj.io/hjacobs/kube-resource-report.update-strategy\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')"}
```
