### ISSUE TITLE
No uptage Image tag

### ISSUE THREAD

**Issue by bottlesbo** [argoproj-labs/argocd-image-updater#1065]
No image tag update
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-chart-rollout
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
  generators:
    - git:
        repoURL: git@gitlab.sber.data1861.ru:devops/helm.git
        revision: HEAD
        directories:
          - path: data1861/app-charts-rollout/mailhog
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/image-list: >-
            uat-img-{{path.basename}}=swr.ru-moscow-1.hc.sbercloud.ru/data1861-uat/{{path.basename}}-uat
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/pull-policy: Always

      labels:
        env: uat
        manager: applicationset
        project: data1861-uat
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      project: data1861-uat
      source:
        helm:
          valueFiles:
            - envs/common/commonenv.yaml
            - envs/uat/values.yaml
            - envs/uat/env.yaml
          version: v3
          parameters: []
        path: '{{path}}'
        repoURL: git@gitlab.sber.data1861.ru:devops/helm.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

Logs 

```
time="2025-03-13T16:12:53Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2025-03-13T16:12:54Z" level=info msg="Setting new image to swr.ru-moscow-1.hc.sbercloud.ru/data1861-uat/mailhog-uat:100105" alias=uat-img-mailhog application=mailhog image_name=data1861-uat/mailhog-uat image_tag=0 registry=swr.ru-moscow-1.hc.sbercloud.ru
time="2025-03-13T16:12:54Z" level=info msg="Successfully updated image 'swr.ru-moscow-1.hc.sbercloud.ru/data1861-uat/mailhog-uat:0' to 'swr.ru-moscow-1.hc.sbercloud.ru/data1861-uat/mailhog-uat:100105', but pending spec update (dry run=false)" alias=uat-img-mailhog application=mailhog image_name=data1861-uat/mailhog-uat image_tag=0 registry=swr.ru-moscow-1.hc.sbercloud.ru
time="2025-03-13T16:12:54Z" level=info msg="Committing 1 parameter update(s) for application mailhog" application=mailhog
time="2025-03-13T16:12:54Z" level=info msg="Successfully updated the live application spec" application=mailhog
time="2025-03-13T16:12:54Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"


```
