### ISSUE TITLE
How to configure ArgoCD Image Updater to update the Helm image tag in application yaml?

### ISSUE THREAD

**Issue by NitishGupta9282** [argoproj-labs/argocd-image-updater#1072]
I am trying to configure ArgoCD Image Updater to automatically update the image tag in the HELM_VALUES section of my ArgoCD application and commit the changes back to my Git repository. However, I am unsure if my configuration is correct or if any additional steps are needed.

```
# yamllint disable rule:line-length
applications:
  data-engine-02:
    namespace: argocd
    project: data-platform
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "3"
      argocd-image-updater.argoproj.io/image.data-engine.update-strategy: semver:~0.1
      argocd-image-updater.argoproj.io/image.data-engine.write-back-method: git
      argocd-image-updater.argoproj.io/image.data-engine.git-branch: main
    source:
      repoURL: git@gitlab.text/data-engine-helm-chart.git
      path: ./
      targetRevision: main
      plugin:
        env:
          - name: HELM_VALUES
            value: |
              image:
                repository: "image/data-engine"
                tag: "0.1.103"  # This should be updated automatically
```

Issue:
The image tag does not get updated in the Git repository.
No commit appears in the repository when a new image version is available.
I want to ensure that the tag field in HELM_VALUES is updated in Git whenever a new image is available.
