### ISSUE TITLE
If Application annotations are removed, parameter overrides are not removed

### ISSUE THREAD

**Issue by hobbsh** [argoproj-labs/argocd-image-updater#110]
**Describe the bug**
I was configuring annotations for a helm app in Argo (via the argo-cd helm chart values) and forgot to specify the helm image tag/name paths, so it populated `image.tag` and `image.name` instead of `my.custom.path`.

I added the correct name/tag paths for the images but `image.name` and `image.tag` parameter overrides still exist in the rendered application manifest.

**To Reproduce**

Add the following annotations to the Application and let the controller update it:
```
argocd-image-updater.argoproj.io/image-list: backend=some.repo/backend frontend=some.repo/frontend
argocd-image-updater.argoproj.io/backend.update-strategy: latest
```

Now go back to the Application and update the annotations to use the correct helm paths:
```
argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^dev-.*$
```

My application manifest still shows both parameter overrides:
```
  helm:
    parameters:
      - name: image.name
        value: some.repo/backend
        forceString: true
      - name: image.tag
        value: dev-94fc3a6c73367f950935ac0e872e2d31de02f110
        forceString: true
      - name: backend.image.repository
        value: some.repo/backend
        forceString: true
      - name: backend.image.tag
        value: dev-94fc3a6c73367f950935ac0e872e2d31de02f110
        forceString: true
```

**Expected behavior**
I would expect to only see:

```
  helm:
    parameters:
      - name: backend.image.repository
        value: some.repo/backend
        forceString: true
      - name: backend.image.tag
        value: dev-94fc3a6c73367f950935ac0e872e2d31de02f110
        forceString: true
```

**Version**
`v0.8.0+961de70`
