### ISSUE TITLE
Helm multiple sources

### ISSUE THREAD

**Issue by onesb23** [argoproj-labs/argocd-image-updater#1122]
I'm not sure if this is a bug or if this behavior hasn't been implemented yet.

**Describe the bug**
Only the first source is updated.

**To Reproduce**
I created a repository specifically to reproduce this behavior:
https://github.com/onesb23/aiu-demo

To reproduce the behavior, you need a helm chart and the argocd application, which has several sources specified.
For example:
```
...
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/library/nginx:latest,redis=docker.io/library/redis:latest
    argocd-image-updater.argoproj.io/nginx.write-back-target: "helmvalues:./values/nginx.yaml"
    argocd-image-updater.argoproj.io/redis.write-back-target: "helmvalues:./values/redis.yaml"
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: default
  sources:
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/nginx.yaml
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/redis.yaml
...
```
At the same time, the helm chart should create several deployments in which images are repeated.

After the argocd image updater program has worked, the "aiu-test" application resource looks like this:
```
Spec:
...
  Sources:
    Helm:
      Parameters:
        Force String:  true
        Name:          image.name
        Value:         docker.io/redis
        Force String:  true
        Name:          image.tag
        Value:         latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09
      Value Files:
        values/nginx.yaml
    Path:             helm/
    Repo URL:         https://github.com/onesb23/aiu-demo
    Target Revision:  HEAD
    Helm:
      Value Files:
        values/redis.yaml
    Path:             helm/
    Repo URL:         https://github.com/onesb23/aiu-demo
    Target Revision:  HEAD
...
```
or in yaml:
```
spec:
...
  sources:
  - helm:
      parameters:
      - forceString: true
        name: image.name
        value: docker.io/redis
      - forceString: true
        name: image.tag
        value: latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09
      valueFiles:
      - values/nginx.yaml
    path: helm/
    repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
  - helm:
      valueFiles:
      - values/redis.yaml
    path: helm/
    repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
...
```
In this case, the nginx image was updated, but the redis image was not.

**Expected behavior**
All sources will be updated and there will be no cyclical argocd image updater log

**Additional context**
Argocd Server Version
2.14.11

**Version**
0.16.0

**Logs**
Cyclical argocd image updater log:
```
...
time="2025-05-01T16:01:55Z" level=info msg="Starting image update cycle, considering 11 annotated application(s) for update"
time="2025-05-01T16:01:57Z" level=info msg="New image docker.io/redis:latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09 already set in spec" alias=redis application=aiu-test image_name=redis image_tag=dummy registry=docker.io
time="2025-05-01T16:01:57Z" level=info msg="Processing results: applications=11 images_considered=14 images_skipped=1 images_updated=0 errors=0"
time="2025-05-01T16:02:27Z" level=info msg="Starting image update cycle, considering 11 annotated application(s) for update"
time="2025-05-01T16:02:28Z" level=info msg="New image docker.io/redis:latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09 already set in spec" alias=redis application=aiu-test image_name=redis image_tag=dummy registry=docker.io
time="2025-05-01T16:02:28Z" level=info msg="Processing results: applications=11 images_considered=14 images_skipped=1 images_updated=0 errors=0"
time="2025-05-01T16:02:59Z" level=info msg="Starting image update cycle, considering 11 annotated application(s) for update"
time="2025-05-01T16:03:00Z" level=info msg="New image docker.io/redis:latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09 already set in spec" alias=redis application=aiu-test image_name=redis image_tag=dummy registry=docker.io
time="2025-05-01T16:03:00Z" level=info msg="Processing results: applications=11 images_considered=14 images_skipped=1 images_updated=0 errors=0"
...
```

**Comment by chengfang** [comment]
From the docs on `write-back-target` configuration, https://argocd-image-updater.readthedocs.io/en/latest/basics/update-methods/#git-write-back-target, all examples show the use of `write-back-target` as an application-wide (not per image alias). Although it's not listed as explicit application-wide config in https://argocd-image-updater.readthedocs.io/en/latest/configuration/images/#appendix, it seems intended to be application-wide.

Also looking at the code such as https://github.com/argoproj-labs/argocd-image-updater/blob/7e4c52ac2885731d501af770bb05ef58f9cb18ed/pkg/argocd/update.go#L478, it just assumes the annotation is on the application.

Not sure how wide it is to use `write-back-target` for each image alias, but this is the first time I come across this. Any reason the values have to be in 2 different values files?

**Comment by onesb23** [comment]
> Any reason the values have to be in 2 different values files

Actually, I have one helm chart for a large number of different deployments. They have the same essence, but some parameters are different, so it was convenient to make just one helm chart. Even if several deployments of one helm chart use the same docker image, it is still updated only for the first value.

I updated the annotation to use write-back-target globally:
```
  annotations:
    #argocd-image-updater.argoproj.io/image-list: nginx=docker.io/library/nginx:latest,redis=docker.io/library/redis:latest
    argocd-image-updater.argoproj.io/image-list: docker.io/library/redis:latest
    #argocd-image-updater.argoproj.io/nginx.write-back-target: "helmvalues:./values/nginx.yaml"
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./values/redis.yaml"
    argocd-image-updater.argoproj.io/update-strategy: digest
```
But the update still didn't go through correctly:
```
    sources:
    - helm:
        parameters:
        - forceString: true
          name: image.name
          value: docker.io/redis
        - forceString: true
          name: image.tag
          value: latest@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09
        valueFiles:
        - values/nginx.yaml
      path: helm/
      repoURL: https://github.com/onesb23/aiu-demo
      targetRevision: HEAD
    - helm:
        valueFiles:
        - values/redis.yaml
      path: helm/
      repoURL: https://github.com/onesb23/aiu-demo
      targetRevision: HEAD
```
That is, the nginx application has the redis image installed.

**Comment by dkarpele** [comment]
@onesb23 Do you think your issue is the same as #1096?

**Comment by onesb23** [comment]
@dkarpele There are indeed some similarities, but there are also a lot of differences. I suppose that solving your issue may solve part of mine, but it's still worth waiting for at least some ideas.
Additionally, my problem may turn out to be a request for new functionality.

**Comment by dkarpele** [comment]
@onesb23 Could you please also check if your scenario works with `argocd-image-updater.argoproj.io/write-back-method: git`?

like this
```
    argocd-image-updater.argoproj.io/image-list: redis=docker.io/library/redis:latest
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./values/redis.yaml"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/redis.helm.image-name: image.name
    argocd-image-updater.argoproj.io/redis.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/git-repository: https://10.42.0.1:30003/testdata.git
```

**Comment by dkarpele** [comment]
@onesb23 I'm asking because if it works with `argocd-image-updater.argoproj.io/write-back-method: git` then you faced #821: `argocd-image-updater.argoproj.io/write-back-method: argocd` (default) and multiple helm sources. Image updater fails in this case =(

**Comment by onesb23** [comment]
@dkarpele Yes, by updating just one image from just one value file, even if it's not the first one in the list, everything worked.

**Comment by dkarpele** [comment]
@onesb23 Do you mean multiple `argocd-image-updater.argoproj.io/<alias>.write-back-target: "helmvalues:..."`?

like
```
    argocd-image-updater.argoproj.io/nginx.write-back-target: "helmvalues:./values/nginx.yaml"
    argocd-image-updater.argoproj.io/redis.write-back-target: "helmvalues:./values/redis.yaml"
```

**Comment by onesb23** [comment]
> argocd-image-updater.argoproj.io/nginx.write-back-target: "helmvalues:./values/nginx.yaml"
>     argocd-image-updater.argoproj.io/redis.write-back-target: "helmvalues:./values/redis.yaml"

That's right. It seems that there is currently no way to update different images from different value files.

**Comment by dkarpele** [comment]
Yes, as Cheng mentioned `write-back-target` should be probably used application-wide.
Regarding `write-back-method: argocd` with multiple images: I plan to prioritize fixing this issue.

**Comment by dkarpele** [comment]
@onesb23 Have you looked into [ApplicationSet](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/)

**Comment by onesb23** [comment]
@dkarpele I'll try to investigate this possibility, thanks for the tip 🤝

**Comment by onesb23** [comment]
I found a way to replace the functionality i needed.
It's not at all convenient, but it's possible.
The `image.name` and `image.tag` data had to be moved to a separate file.
For example file `images.yaml`: 
```
nginx:
  image:
    name: docker.io/nginx
     tag: latest
redis:
  image:
    name: docker.io/redis
     tag: latest
```
And argocd application should look like this:
```
...
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/nginx:latest,redis=docker.io/redis:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: git@github.com:onesb23/aiu-demo.git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./values/images.yaml"
    argocd-image-updater.argoproj.io/nginx.helm.image-name: nginx.image.name
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: nginx.image.tag
    argocd-image-updater.argoproj.io/redis.helm.image-name: redis.image.name
    argocd-image-updater.argoproj.io/redis.helm.image-tag: redis.image.tag
spec:
  project: default
  sources:
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/nginx.yaml
      - values/images.yaml
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/redis.yaml
      - values/images.yaml
...
```
And you also need to redo the logic for getting `image` and `tag` values ​​in the helm chart.
@dkarpele @chengfang  This behavior should work for `write-back-method: argocd`?
