### ISSUE TITLE
Does Image updater support App of Apps pattern with helm chart?

### ISSUE THREAD

**Issue by kalpesh-pathlock** [argoproj-labs/argocd-image-updater#1133]
I'm using app of apps patterns and then utilising the image updater using git write-back method. It seems pushes the spec param file in git repo specified but it doesn't update the deployment with below warning or info log.

time="2025-05-15T10:42:34Z" level=info msg="Successfully updated image 'plock.azurecr.io/nginx:v1.3' to 'plock.azurecr.io/nginx:v1.4', but pending spec update (dry run=false)" alias=nginx application=nginx-app image_name=nginx image_tag=v1.3 registry=plock.azurecr.io

**Parent app**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: demo-inf-sh
spec:
  destination:
    namespace: demo-inf-sh
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: az-demo-plc-demo-infra/Applications/
    repoURL: git@github.com:PLock/plock-argocd.git
    targetRevision: HEAD

```

App in parent app

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: rk-tnt
  annotations:
    argocd-image-updater.argoproj.io/image-list: ptdwebapp=plock.azurecr.io/nginx
    argocd-image-updater.argoproj.io/ptdwebapp.update-strategy: latest
    argocd-image-updater.argoproj.io/ptdwebapp.helm.image-tag: "images.PTD_WEB_APP.tag"
    argocd-image-updater.argoproj.io/ptdwebapp.helm.image-name: "images.PTD_WEB_APP.repository"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/ptdwebapp.platforms: linux/arm64,windows/amd64
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/git-repository: git@github.com:PLockMigration/plock-argocd.git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:

  destination:
    name: ''
    namespace:  rk-tnt
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: plock.azurecr.io/helm
    targetRevision: 0.0.15
    chart: grc-app
    helm:
      valuesObject: 
        images:
          ECR_URL: "plock.azurecr.io"
          PTD_WEB_APP:
            name: servercore
            tag: DD_22578
            container_name: ptd-web-app
            repository: plock.azurecr.io/ptd-web-app
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Can you please help me clarify if this is feasible? Argocd write back method just works fine with changing the annotation.

Thanks
