### ISSUE TITLE
Cannot select target repo when using multi-source Applications?

### ISSUE THREAD

**Issue by CiucurDaniel** [argoproj-labs/argocd-image-updater#1142]
I'm using multi source applications. In my case the sources are 2 Git repositories. 
One points to some helm chart. The other to the values files used to override the default values. 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/bgd.git-branch: main
    argocd-image-updater.argoproj.io/bgd.helm.image-name: bgdDeployment.image
    argocd-image-updater.argoproj.io/bgd.helm.image-tag: bgdDeployment.tag
    argocd-image-updater.argoproj.io/bgd.pull-secret: secret:argocd-image-updater/acr-admin-creds#creds
    argocd-image-updater.argoproj.io/bgd.update-strategy: newest-build
    argocd-image-updater.argoproj.io/bgd.write-back-target: helmvalues:/test1/project-bgd-values.yaml
    argocd-image-updater.argoproj.io/image-list: bgd=projectcrgwc.azurecr.io/project-devops/bgd
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds-org
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: test1-project-bgd
  namespace: argocd
spec:
  destination:
    namespace: test1
    server: https://kubernetes.default.svc
  project: default
  sources:
  # This source is used to provide different values
  - ref: values
    repoURL: https://github.com/org/project-argocd-az-deployconfig-solution-2.git
    targetRevision: main
  # This source is the helm chart
  - helm:
      valueFiles:
      - $values/test1/project-bgd-values.yaml
      - $values/test1/operational.yaml
    path: project-bgd/1.0.0
    repoURL: https://github.com/org/project-argocd-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
```

With above manifest Image Updater will always update the repo with the helm chart. Not the repo with the values files.  

Is there a way to tell ImageUpdater to target the other source (repository) for the commits?

Version used: quay.io/argoprojlabs/argocd-image-updater:v0.15.2
