### ISSUE TITLE
Matching image not found in application

### ISSUE THREAD

**Issue by michelle-avery** [argoproj-labs/argocd-image-updater#1143]
I'm trying to configure argocd-image-updater to always update the latest image tagged `main`, but I'm struggling with persistent "image seems not to be live in this application" issues, despite many attempts to resolve the issue by reading through similarly reported problems.

I've configured my application annotations like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caffeinated-wardrobe
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: cw-backend:ghcr.io/michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-backend:main
    argocd-image-updater.argoproj.io/cw-backend.update-strategy: digest
    argocd-image-updater.argoproj.io/cw-backend.pull-secret: argocd/github-registry-credentials
spec:
  project: caffeinated-wardrobe
  source:
    repoURL: git@github.com:michelle-avery/home-ops.git
    targetRevision: HEAD
    path: projects/caffeinated-wardrobe
  destination:
    server: https://kubernetes.default.svc
    namespace: caffeinated-wardrobe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

My kustomization file for that application is pretty straightforward, with no `image` overrides:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - ingressroute.yaml
  - gatus.yaml
  - database.yaml
  - secrets.yaml
```

The deployment (truncated below) specifies the image name:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caffeinated-wardrobe-backend
  namespace: caffeinated-wardrobe
  labels:
    app.kubernetes.io/name: caffeinated-wardrobe-backend
    app.kubernetes.io/instance: caffeinated-wardrobe-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: caffeinated-wardrobe-backend
      app.kubernetes.io/instance: caffeinated-wardrobe-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caffeinated-wardrobe-backend
        app.kubernetes.io/instance: caffeinated-wardrobe-backend
    spec:
      imagePullSecrets:
        - name: github-registry-credentials
      containers:
        - name: caffeinated-wardrobe-backend
          image: ghcr.io/michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-backend:main
          imagePullPolicy: IfNotPresent
```

The Application has images that do seem to match:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/cw-backend.pull-secret: argocd/github-registry-credentials
    argocd-image-updater.argoproj.io/cw-backend.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: >-
      cw-backend:ghcr.io/michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-backend:main
    argocd.argoproj.io/tracking-id: argocd:argoproj.io/Application:argocd/caffeinated-wardrobe
 < Truncated information >
  sourceType: Kustomize
  summary:
    images:
      - ghcr.io/cloudnative-pg/cloudnative-pg:1.25.0
      - ghcr.io/cloudnative-pg/postgresql:17.2
      - >-
        ghcr.io/michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-backend:main
      - >-
        ghcr.io/michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-frontend:main
```
But it still seems to not be able to find it:

```
time="2025-05-27T14:30:42Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2025-05-27T14:30:42Z" level=debug msg="Processing application argocd/caffeinated-wardrobe"
time="2025-05-27T14:30:42Z" level=debug msg="Image 'michelle-avery/caffeinated-wardrobe/caffeinated-wardrobe-backend' seems not to be live in this application, skipping" application=caffeinated-wardrobe
time="2025-05-27T14:30:42Z" level=info msg="Processing results: applications=1 images_considered=0 images_skipped=1 images_updated=0 errors=0"
```
The log message notably does not contain the 'ghcr.io' registry part itself, but looking at the code it seems like that's intentionally split out from the image name in the message, so I think that's to be expected.

Other things I've tried, which didn't work:
* Adding an override to the kustomization file anyway and using the `kustomize.image-name` annotation
* Using a shorter image name that doesn't cause the image name in the Application manifest to be multi-line

Any idea what else might be wrong here? Is there some mismatch that I'm just not seeing?
