### ISSUE TITLE
Cannot authenticate to GitLab Image registry

### ISSUE THREAD

**Issue by fcyron2025** [argoproj-labs/argocd-image-updater#1162]
Hi,

sorry, I'm very new to this DevOps world, so excuse if this is a dumb question ;) And please tell me, if you are needing more information.

I'm trying to connect to a gitlab registry using:
```
argocd-image-updater test registry.xxx.de/malkasten/backend --credentials pullsecret:argocd/gitlab-registry-backend 
```
in the argocd-image-updater pod. This works fine. 

But when I try to get this to work with an application, I get the following Log output:

Log output:
```
time="2025-06-07T17:05:36Z" level=debug msg="Considering this image for update" alias=backend application=malkasten-store image_name=malkasten/backend image_tag=1.0.0 registry=registry.xxx.de
time="2025-06-07T17:05:36Z" level=debug msg="setting rate limit to 20 requests per second" prefix=registry.xxx.de registry="https://registry.xxx.de"
time="2025-06-07T17:05:36Z" level=debug msg="Inferred registry from prefix registry.xxx.de to use API https://registry.xxx.de"
time="2025-06-07T17:05:36Z" level=debug msg="Using no version constraint when looking for a new tag" alias=backend application=malkasten-store image_name=malkasten/backend image_tag=1.0.0 registry=registry.xxx.de
time="2025-06-07T17:05:36Z" level=warning msg="Invalid credential reference specified: argocd/gitlab-registry-backend" image_alias=backend image_name=registry.dewango.de/malkasten/backend registry_url=registry.xxx.de
```

argocd-image-updater-values.yml:
```
argocd:
  serverAddress: http://argocd-server.argocd.svc

config:
  logLevel: debug

  registries:
    - name: backend
      prefix: registry.xxx.de/malkasten/backend
      api_url: https://registry.xxx.de
      credentials: "pullsecret:argocd/gitlab-registry-backend"

  rbac:
    policy.csv: |
      g, system:serviceaccount:argocd:argocd-image-updater, role:admin
      g, system:serviceaccount:argocd:argocd, role:admin
      g, system:authenticated, role:admin
    policy.default: role:readonly

serviceAccount:
  create: true
  name: argocd-image-updater
```

Application definition for ArgoCD:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: malkasten-store
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "backend=registry.xxx.de/malkasten/backend, frontend=registry.xxx.de/malkasten/frontend"
    argocd-image-updater.argoproj.io/backend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/frontend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/backend.pull-secret: argocd/gitlab-registry-backend
    argocd-image-updater.argoproj.io/frontend.pull-secret: argocd/gitlab-registry-frontend
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^\\d{14}$
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^\\d{14}$
spec:
  project: default
...
```

I created the secret in a terraform file (where argocd is installed via helm):
```
resource "kubernetes_secret" "gitlab_registry_backend" {
  depends_on = [ helm_release.argocd ]
  
  metadata {
    name      = "gitlab-registry-backend"
    namespace = "argocd"
  }

  type = "kubernetes.io/dockerconfigjson"

  data = {
    ".dockerconfigjson" = jsonencode(
      {
        auths = {
          "registry.xxx.de" = {
            username = "argocd-deployment-token"
            password = "${var.gitlab_registry_backend_token}"
            email    = "argo@argo.de"
            auth     = base64encode("argocd-deployment-token:${var.gitlab_registry_backend_token}")
          }
        }
      }
    )
  }
}
```
