### ISSUE TITLE
do not support standard kustomization format

### ISSUE THREAD

**Issue by 13567436138** [argoproj-labs/argocd-image-updater#1167]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

when write back with follow go panic

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gulimall-auth-server

# 添加 images 字段用于镜像更新
images:
  - name: gulimall-auth-server
    newName: harbor.mark.demo/guli/gulimall-auth-server
    newTag: ac47eef


resources:
  - deployment.yaml
  - service.yaml
  - propagationpolicy-deployment.yaml
  - propagationpolicy-svc.yaml
  - configmap.yaml

```

with code
```
switch appType {
	case ApplicationTypeKustomize:
		if appSource.Kustomize == nil {
			return []byte{}, nil
		}

		var params kustomizeOverride
		newParams := kustomizeOverride{
			Kustomize: kustomizeImages{
				Images: &appSource.Kustomize.Images,
			},
		}

		if len(originalData) == 0 {
			override, err = marshalWithIndent(newParams, defaultIndent)
			break
		}
		err = yaml.Unmarshal(originalData, &params)
		if err != nil {
			override, err = marshalWithIndent(newParams, defaultIndent)
			break
		}
		mergeKustomizeOverride(&params, &newParams)
		override, err = marshalWithIndent(params, defaultIndent)
```

params is nil
