### ISSUE TITLE
argocd-image-updater commits all overridden argocd parameters

### ISSUE THREAD

**Issue by GRusla-n** [argoproj-labs/argocd-image-updater#1174]
I'm using the git write-back method. When I override any parameters in argocd, the argocd-image-updater commits all overridden parameters — not just those related to the image.

![Image](https://github.com/user-attachments/assets/e1ec1fa6-d335-4940-be1c-b1af0a2761ea)

**Comment by chengfang** [comment]
Is this `.argocd-source-*.yaml` file? Can you post the whole file? Which image-updater versions?

**Comment by GRusla-n** [comment]
Version: v0.15.2 (using helm  chart  v0.12.0)
Yes, it's `.argocd-source-preprod-lts.yaml` in my case
```
helm:
  parameters:
  - name: image.frontend.tag
    value: 2024.11.1-67
    forcestring: true
  - name: image.backend.tag
    value: 2024.11.4.8
    forcestring: true
  - name: image.worker.tag
    value: 2024.11.4.8
    forcestring: true
  - name: image.fileservice.tag
    value: 2024.11.4.8
    forcestring: true
  - name: image.websocket.tag
    value: 2024.11.4.8
    forcestring: true
  - name: image.scheduler.tag
    value: 2024.11.4.8
    forcestring: true
  - name: replicas
    value: "0"
    forcestring: false
```
