### ISSUE TITLE
Defined parameters in Application getting overwritten

### ISSUE THREAD

**Issue by szucsitg** [argoproj-labs/argocd-image-updater#132]
**Describe the bug**
If you have a parameter in the Application, and there's a new image that's triggering an update of the Argo Application, it'll create an infinite sync loop.

**To Reproduce**
Add this to a Helm deployment's Application manifest:
```
spec:
  source:
    helm:
      parameters:
      - name: customVariable
        value: customValue
```

**Expected behavior**
Should not be an infinite loop of sync.

**Additional context**
N/A

**Version**
v0.8.0 - sha256:e31a6c1dce2cfbe12b84f1a68b6e6c85f4ca227c32a6c5bab20e2dc053457e2e

**Logs**
N/A
