### ISSUE TITLE
Multiple tag on same image with latest strategies will in loop update image

### ISSUE THREAD

**Issue by matthisholleville** [argoproj-labs/argocd-image-updater#147]
Hi,

I use Google Container Registry for hosting my docker images. When I tag my docker image with SHA1 tag and latest tag, `argocd-image-updater` found two tag for `latest` strategy image.

So it first updates the pod image with the tag `SHA1` .... then it updates with the `latest` tag... 

This operation is executed in a loop

**To Reproduce**

```
# Build with two tag
docker build -t eu.gcr.io/<gcp-project-id>/<image-name>:07bfd2596 -t eu.gcr.io/<gcp-project-id>/<image-name>:latest .

# Push image with two tag
docker push eu.gcr.io/<gcp-project-id>/<image-name>:07bfd2596
docker push eu.gcr.io/<gcp-project-id>/<image-name>:latest
```

Application YAM
```yaml
apiVersion: argoproj.io/v1alpha1
...
    annotations:
    argocd-image-updater.argoproj.io/image-list: my_alias=eu.gcr.io/<gcp-project-id>/<image-name>
    argocd-image-updater.argoproj.io/my_alias.update-strategy: latest
....
```

**Expected behavior**
I think argocd-image-updater should be based on `image digest` for determine the really latest image.

**Version**
`argocd-image-updater:0.8`

**Workaround**

I use `ignore_tags` for explicitly ignoring latest tag

```yaml
apiVersion: argoproj.io/v1alpha1
...
    annotations:
    argocd-image-updater.argoproj.io/image-list: my_alias=eu.gcr.io/<gcp-project-id>/<image-name>
    argocd-image-updater.argoproj.io/my_alias.update-strategy: latest
    argocd-image-updater.argoproj.io/my_alias.ignore-tags: latest
....
```

**Logs**
```
time="2021-01-27T16:51:24Z" level=debug msg="Cache hit for eu.gcr.io/<gcp-project-id>/<image-name>:07bfd2596"
time="2021-01-27T16:51:24Z" level=debug msg="Cache hit for eu.gcr.io/<gcp-project-id>/<image-name>:latest"
time="2021-01-27T16:51:24Z" level=debug msg="found 2 from 2 tags eligible for consideration" image="eu.gcr.io/<gcp-project-id>/<image-name>:07bfd2596"
```
