### ISSUE TITLE
Missing SSH client in Docker image

### ISSUE THREAD

**Issue by eplightning** [argoproj-labs/argocd-image-updater#163]
**Describe the bug**
Currently built `argoprojlabs/argocd-image-updater` images lack SSH client resulting in errors when trying to use git write back feature with SSH git repositories.

**To Reproduce**
- Create ArgoCD application using SSH repository with annotations required by argocd-image-updater:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: image=[...]
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image.update-strategy: latest
    argocd-image-updater.argoproj.io/image.ignore-tags: latest
 spec:
  destination:
    namespace: some-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: some-path
    repoURL: git@repo.org:repopath.git
    targetRevision: HEAD
```
- Wait for argocd-image-updater to attempt git writeback
- argocd-image-updater executes git which errors out due to missing ssh binary

**Expected behavior**
- Git write back succeeds

**Additional context**
```
FROM argoprojlabs/argocd-image-updater@sha256:a7f435f888d2f98f0bd477a36f3d4903d92755ee347365d33e414ee37c34ff26

USER 0

RUN apk update && apk add openssh-client && adduser --home "/app" --disabled-password --uid 1000 argocd

USER 1000
```

Above changes in addition to mounting `ssh_known_hosts` file to `/app/config/ssh` directory (probably needs to be documented) fix the issue.

**Version**
master - commit https://github.com/argoproj-labs/argocd-image-updater/commit/457b52f60e21f48977eb6b5c06323bd2f564bfd1
