### ISSUE TITLE
Add update strategy to restart deployment if digest for same tag has changed

### ISSUE THREAD

**Issue by starcraft66** [argoproj-labs/argocd-image-updater#174]
**Is your feature request related to a problem? Please describe.**
I would like to use argocd-image-updater to update some container images I have pinned to the `latest` tag (specifically linuxserver.io container images) because some image have "specific" tags are very long and nonsensical e.g. `linuxserver/qbittorrent:version-14.3.4.99202103270406-7346-81a7b0c03ubuntu20.04.1`. I realize this locking an image tag to `latest` isn't usually a good idea but it's necessary in this case. I can't use the "latest" update strategy because the latest images are pre-release builds I don't want to use.

I initially thought I could do something like:
```
annotations:
    argocd-image-updater.argoproj.io/image-list: "qbittorrent=linuxserver/qbittorrent"
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: name
    argocd-image-updater.argoproj.io/qbittorrent.allow-tags: "regexp:^latest$"
```
But then I quickly realized that that will only check that the deployment is locked to `linuxserver/qbittorrent:latest` but doesn't check the digest to see if that tag has been updated upstream at the registry since they are mutable.

**Describe the solution you'd like**
I'd like to see a new strategy added that just watches a single tag for digest updates and then restarts the relevant deployment (given that it is using `ImagePullPolicy: Always`) so that it pulls an updated image.
