### ISSUE TITLE
write-back fails on SSH repo

### ISSUE THREAD

**Issue by iamnoah** [argoproj-labs/argocd-image-updater#183]
**Describe the bug**

SSH authentication fails when checking out the repo for write-back:

```
time="2021-04-02T01:20:07Z" level=error msg="Could not update application spec: `git fetch origin --tags --force` failed exit status 128: git@github.com: Permission denied (publickey).\r
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists." application=my-app
```

**To Reproduce**

Create the ssh key secret using a GitHub deploy key with read & write access:

```shell
kustomize create secret generic k8s-repo-deploy-key --from-file=sshPrivateKey -n argocd
```

Create an app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-app=xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-app
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/k8s-repo-deploy-key
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
    argocd-image-updater.argoproj.io/my-app.allow-tags: "regexp:develop-.+"

spec:
  project: default
  source:
    repoURL: git@github.com:my-org/my-repo.git
    targetRevision: master
    path: my-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
```

**Expected behavior**

A new image results in a write-back commit to the repo.

**Additional context**

I know the key is valid because this kustomize patch let me workaround it:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-image-updater
spec:
  selector: {}
  template:
    spec:
      volumes:
        - name: ssh-key
          secret:
            secretName: k8s-repo-deploy-key
            items:
              - key: sshPrivateKey
                path: id_rsa
      containers:
        - name: argocd-image-updater
          env:
            - name: GIT_SSH_COMMAND
              value: "ssh -o StrictHostKeyChecking=no"
          volumeMounts:
            - mountPath: /app/.ssh/
              name: ssh-key
```

If I mount the key like this, it all works fine, so something is wrong with how the key is read from a secret and passed to git/ssh.

**Version**

v0.9.2 and HEAD:

```
resources:
  - github.com/argoproj-labs/argocd-image-updater/manifests/base?ref=f1cc8e4542b0531f66fc5546f7467833b1d08ebe
```
