### ISSUE TITLE
image alias with kustomize generates wrong override file

### ISSUE THREAD

**Issue by r0bj** [argoproj-labs/argocd-image-updater#184]
**Describe the bug**
Image alias used with kustomize generates wrong override file.

**To Reproduce**
Application source.
resources.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      - image: nginx:1.19.3-alpine
        name: nginx
```
kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

Argo Application (kustomize type) with annotation:
```
argocd-image-updater.argoproj.io/image-list: nginx=example.com/dockerhub/nginx
```
argocd-image-updater generates override file `.argocd-source-myapp.yaml`:
```
kustomize:
  images:
  - example.com/dockerhub/nginx:1.19.9
```
Note, override syntax is missing `nginx` alias, proper syntax should be `nginx=example.com/dockerhub/nginx:1.19.9`. In this case kustomize won't override `nginx` -> `example.com/dockerhub/nginx:1.19.9`

**Expected behavior**
argocd-image-updater should generate override file with syntax `.argocd-source-myapp.yaml`:
```
kustomize:
  images:
  - nginx=example.com/dockerhub/nginx:1.19.9
```

**Version**
argocd-image-updater: v0.9.2
