### ISSUE TITLE
Using image alias for two different purposes: kustomize custom image and argo custom options could limit use cases

### ISSUE THREAD

**Issue by r0bj** [argoproj-labs/argocd-image-updater#185]
**Describe the bug**
After argocd-image-updater documentation:
```
Assigning an alias name to an image is necessary in these scenarios:

- If you want to use custom images with Kustomize. In this case, the name must match to what is defined in your Kustomize base.
[...]
- If you want to set custom options for a given image's update strategy, or require referencing unique pull secrets for each image
```
So image alias can be used for two different purposes:
1. kustomize custom image
2. argo custom options (like e.g. update-strategy)

Coupling those two purposes together with alias can limit use cases.

Example:
resources.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      - image: example.com/myapp:1.19.3-alpine
        name: nginx
```
kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

Let's say that I would like to use argocd-image-updater custom strategy for image `example.com/myapp`. I would need to use annotation similar to:
```
argocd-image-updater.argoproj.io/<image_name>.update-strategy: <strategy>
```
In order to use it I would need to have image alias (<image_name>) but I cannot use alias because It would be interpreted as kustomize alias (which is not true in this case, I just want to use newer image as is).
So I don't see any option to set custom `update-strategy` for image `example.com/myapp`.

Am I wrong here?

There is additional limitation to alias allowed characters (alpha-numerical characters) which can be too limited for kustomize aliases.

**Expected behavior**

argocd-image-updater image aliases (which are used for different purposes, e.g. custom `update-strategy`) are decoupled from kustomize aliases.
I suspect that fixing it would require changing argocd-image-updater annotation syntax.

Just a side note, It would probably be much easier to define all argocd-image-updater options with custom CRD (or as an extension to Application CRD) instead of using annotations.

**Version**
argocd-image-updater: v0.9.2
