### ISSUE TITLE
Annotated application not considered for update

### ISSUE THREAD

**Issue by andrei-dascalu** [argoproj-labs/argocd-image-updater#188]
**Describe the bug**
Application seems to be ignored by the image updater.

**To Reproduce**
Application (Helm application where the chart comes from git repository, created via UI and it's recognised as a Helm application, with values yaml, etc)

```yaml
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'gcr.io/qappstools/testapi:~1.0'
  destination:
    namespace: mytestapi
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: manifests/argoapi
    repoURL: '<ssh git repo>'
    targetRevision: HEAD
  syncPolicy: {}
```

**Expected behavior**
Applicatoin detected and considered for update

**Additional context**

image not considered for update

```
level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"
```

**Version**
```
argoprojlabs/argocd-image-updater:latest
```

**Logs**

```
time="2021-04-09T23:05:03Z" level=info msg="Starting health probe server TCP port=8080"
time="2021-04-09T23:05:03Z" level=info msg="Starting metrics server on TCP port=8081"
time="2021-04-09T23:05:03Z" level=info msg="Warming up image cache"
time="2021-04-09T23:05:03Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 5 registries"
time="2021-04-09T23:05:03Z" level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"
time="2021-04-09T23:05:03Z" level=info msg="Processing results: applications=0 images_considered=0 images_skipped=0 images_updated=0 errors=0"
```
