### ISSUE TITLE
Could not get aws public registry endpoint

### ISSUE THREAD

**Issue by jeff51419** [argoproj-labs/argocd-image-updater#204]
**Describe the bug**
could not get image from public.ecr.aws registry.

**To Reproduce**
1. create argocd-image-updater
2. kubectl exec -it argocd-image-updater-bb9c65fbd-rdfgn -- sh
3. $ argocd-image-updater test public.ecr.aws/nginx/nginx
```
INFO[0000] getting image                                 image_name=nginx/nginx registry=public.ecr.aws
FATA[0000] could not get registry endpoint: no registry with prefix 'public.ecr.aws' configured
```
![image](https://user-images.githubusercontent.com/18411883/117107174-befdfe00-adb3-11eb-9058-d89c30a695ee.png)

***
**Following the [Configuring Container Registries]**(https://argocd-image-updater.readthedocs.io/en/v0.9.0/configuration/registries/#configuring-container-registries)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Public amazon ECR Hub
      api_url: https://public.ecr.aws
      prefix: public.ecr.aws
      ping: no
      tagsortmode: latest-first
      credsexpire: 6h
```

![image](https://user-images.githubusercontent.com/18411883/117107508-464b7180-adb4-11eb-895e-04ddd414d6ef.png)

**verified in pod**
![image](https://user-images.githubusercontent.com/18411883/117107920-05a02800-adb5-11eb-9473-b682a35ee112.png)

**Expected behavior**
argocd-image-updater can access public.ecr.aws, then update the images.

**Additional context**
aws doc
https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

**Version**
$ argocd-image-updater version
```
argocd-image-updater: v0.9.3+06cbc09
  BuildDate: 2021-05-05T07:24:04Z
  GitCommit: 06cbc097ae3b7a77458ba657d0ef7e3028477a54
  GoVersion: go1.14.13
  GoCompiler: gc
  Platform: linux/amd64
```
**Logs**
pod log
![image](https://user-images.githubusercontent.com/18411883/117108441-c2928480-adb5-11eb-8f13-38cf50c03841.png)

If there is anything I set up in wrong way, please let me know.
