### ISSUE TITLE
write-back-target: kustomization bug

### ISSUE THREAD

**Issue by xriser** [argoproj-labs/argocd-image-updater#208]
I have kuztomization file like this:
```
resources:
- frontend.yaml

images:
- name: frontend
  newName: gcr.io/project/frontend
  newTag: v0.0.75-dev
 ```

When the image updater writes changes it adds lines instead of merge.
The final result like this:

```
resources:
- frontend.yaml

images:
- name: frontend
  newName: gcr.io/project/frontend
  newTag: v0.0.75-dev
- name: gcr.io/project/frontend
  newTag: v0.0.76-dev
 ```
also, it skip the image name

**Version**
0.0.94

**Comment by jannfis** [comment]
@iamnoah Would you mind taking a look please?

**Comment by iamnoah** [comment]
@xriser can you post your Application annotations?

**Comment by xriser** [comment]
Actually, I have removed newName and it is working as expected.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend.yaml

images:
- name: gcr.io/project/frontend
  newTag: v0.0.78-dev
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xdev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=gcr.io/project/frontend, ...
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:\d+\.\d+\.\d+-dev$
    argocd-image-updater.argoproj.io/write-back-method: git:repocreds
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: development
  source:
    path: dev/deployments
    repoURL: git@bitbucket.org:xdev/k8s-deployments.git
    targetRevision: HEAD
    kustomize:
      # Optional kustomize version. Note: version must be configured in argocd-cm ConfigMap
      # version: v3.5.4
      # Optional image name prefix
      # namePrefix: prod-
      # Optional images passed to "kustomize edit set image".
      # images:
      #  - gcr.io/heptio-images/ks-guestbook-demo:0.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
```
