### ISSUE TITLE
Image doesnt seem to update with helm image name and tags

### ISSUE THREAD

**Issue by suraj2410** [argoproj-labs/argocd-image-updater#218]
I always see the message 
`time="2021-06-16T17:14:03Z" level=debug msg="Image 'org/example' seems not to be live in this application, skipping" application=myapp`

**To Reproduce**
the source path for the application resource looks like

```
source:
    path: charts/apps/myapp
    repoURL: git@github.com:/org/charts
    targetRevision: HEAD
    # helm specific config
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - ../../values-env/env.yaml
      releaseName: myapp
```

The annotations are:
```
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myrepo=dockerhub.io/org/app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/myrepo.allow-tags: 'regexp:^master_.*$'
    argocd-image-updater.argoproj.io/myrepo.update-strategy: latest
    argocd-image-updater.argoproj.io/myrepo.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myrepo.helm.image-tag: tag_version
```
Te values file are:

values-env/env.yaml

```
tag_version: master_abc
replicaCount: 2
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 64m
    memory: 256Mi
```

default values.yaml file
```
image:
  pullPolicy: IfNotPresent
  repository: org/app
tag_app: NONE
```

The image tag in deployment.yaml inside the app looks like:
```
image: {{ .Values.image.repository }}:{{  template "tag_name" . }}
```
The template that produces this tag is in _helpers.tpl below:
```
{{- define "tag_name" -}}
{{- if .Values.tag_version -}}
{{- .Values.tag_version -}}
{{- else -}}
{{- .Values.tag_app -}}
{{- end -}}
{{- end -}}
```

**Expected behavior**
There should be some logs that says that the particular version has been picked up but i always get the  message 
```
`time="2021-06-16T17:14:03Z" level=debug msg="Image 'org/example' seems not to be live in this application, skipping" application=myapp`
```

**Additional context**
What should be done in order to have the app get the updated tag. I feel like its not fetching latest tags from the dockerhub repo or something with the filter of allow tags.

This works directly if i use argocd cli to update the app set for example
```
argocd app set --helm-set tag_version=master_abc myapp

argocd app set --helm-set image.repository=org/app myapp
```
So this kinda means that the annotations for the following are correct since its picked up by argocli above when tested manually
```
    argocd-image-updater.argoproj.io/myrepo.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myrepo.helm.image-tag: tag_version
``` 

**Version**
argoprojlabs/argocd-image-updater:latest

**Logs**
`time="2021-06-16T17:14:03Z" level=debug msg="Image 'org/example' seems not to be live in this application, skipping" application=myapp`

What am i doing wrong here. any idea or help would be much appreciated!

**Comment by jannfis** [comment]
Hey, sorry for coming so late to this one. I think you may have success with the `force-update` annotation, i.e.

```
argocd-image-updater.argoproj.io/myrepo.force-update: "true"
```

https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#forcing-image-updates

**Comment by saurabh3460** [comment]
@jannfis  How the image-updater find an image is in use, because I am also getting this issue:

`time="2021-11-29T11:46:51Z" level=info msg="Loaded 1 registry configurations from /app/config/registries.conf"
time="2021-11-29T11:46:51Z" level=debug msg="Creating in-cluster Kubernetes client"
time="2021-11-29T11:46:51Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=false, plaintext=false]"
time="2021-11-29T11:46:51Z" level=info msg="Starting health probe server TCP port=8080"
time="2021-11-29T11:46:51Z" level=info msg="Starting metrics server on TCP port=8081"
time="2021-11-29T11:46:51Z" level=info msg="Warming up image cache"
time="2021-11-29T11:46:51Z" level=debug msg="Processing application demo"
time="2021-11-29T11:46:51Z" level=debug msg="Image 'saurabh3460/demo' seems not to be live in this application, skipping" application=demo`

**Comment by tjordan170** [comment]
@suraj2410 You shouldn't have to use the force-update annotation if your application manifest and chart are correct. It looks like your image-list value includes `dockerhub.io/` and `image: {{ .Values.image.repository }}:{{  template "tag_name" . }}` in your deployment.yaml is rendered to a value that does not include `dockerhub.io/`. You can check the value under images in the summary for your application in the Argo CD UI.

For your question on how the image-updater determines whether or not an image is in use, the image updater compares the image-list value to the images in the status summary for the running application. Refer [here](https://github.com/argoproj-labs/argocd-image-updater/blob/89daab684fcdac4c4d3a0683fe4764a9c1abd0b4/pkg/argocd/argocd.go#L478).

**Comment by flogiston007** [comment]
@suraj2410 
What exactly was your problem - you used argocd-image-updater.argoproj.io/write-back-method: git
You should use argocd-image-updater.argoproj.io/write-back-method: argocd

In general, the working configuration looks like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=registry-host.com/app-dev-registry/app-base-image:main
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/app.helm.image-name: app.image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/app-dev-registry
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    chart: app-chart
    repoURL: https://app-dummy-helm.github.io/charts
    targetRevision: 10.2.2
    helm:
      values: |
        app:
          image:
            repository: repo
            tag: latest
```
You can delete values from the values field, argocd will modify your chart on the fly
