### ISSUE TITLE
It would be nice to have Harbor registry supported

### ISSUE THREAD

**Issue by Igor992** [argoproj-labs/argocd-image-updater#220]
Hello,

I am not aware if someone here uses Harbor as a private registry but I assume that it would be a nice feature to add that one also into the list described here - https://argocd-image-updater.readthedocs.io/en/latest/configuration/registries/#configuring-a-custom-container-registry

I currently trying to test ArgoCD with my private Harbor registry and wasn't able to pull images/charts from it.

If there is some other way to include Harbor to be used at the custom registry, so Argo can point to it, please advise me.

Thanks for review this ticket!

Sincerely,
Igor

**Comment by jannfis** [comment]
Hey @Igor992, have you tried configuring your Harbor registry in the `registries.conf`? If yes, what did not work?

**Comment by Igor992** [comment]
Hey @jannfis, this was my mistake with configuration a fresh new k8s cluster, somehow I forgot to add my private registry into the service account. Gladly ArgoCD provides good logs output and I was able to see what is missing there.

Thanks for the reply tho, keep doing a great job with Argo.

Sincerely,
Igor

**Comment by vishnuhd** [comment]
Hey @Igor992, I know its been a long time since this issue was closed but can you please help with the `registries.conf` for harbor. We have the configmap but failing with the below error :

```
registries.conf: |
    registries:
    - name: Harbor registry
      api_url: https://harbor.example.net
      credentials: pullsecret:argocd/regcred
      ping: no
```

and the logs says : 

```
time="2021-11-30T10:14:39Z" level=error msg="Could not get registry endpoint from configuration: no registry with prefix 'harbor.example.net' configured" alias= application=backend-example-dev image_name=backend-example/development image_tag=latest registry=harbor.example.net
```

**Comment by Igor992** [comment]
Hello @vishnuhd, I can't tell what is the problem here is from this "short" stderr output, but maybe you can use this trick to debug it further on the container itself.

https://github.com/argoproj-labs/argocd-image-updater/issues/204#:~:text=%24%20./dist/argocd%2Dimage%2Dupdater%20test%20public.ecr.aws/nginx/nginx%20%2D%2Dregistries%2Dconf%20registries.conf

There should be some FATA[0001] output code for problems that you have.
I hope this helps with your needs. 

Sincerely,
Igor

**Comment by jannfis** [comment]
@vishnuhd You will need to set the appropriate prefix in your registries.conf, i.e.

```
registries.conf: |
    registries:
    - name: Harbor registry
      prefix: harbor.example.net
      api_url: https://harbor.example.net
      credentials: pullsecret:argocd/regcred
      ping: no
```
