### ISSUE TITLE
Incorrect image update

### ISSUE THREAD

**Issue by ykizin** [argoproj-labs/argocd-image-updater#228]
**Describe the bug**
Hello! I have problem with Amazon ECR, argocd-image-updater don't use latest image at registry, but see all available images
ps: latest image tag 339

**Version**
Image:         argoprojlabs/argocd-image-updater:latest
Image ID:      docker-pullable://argoprojlabs/argocd-image-updater@sha256:5176770f8a5c7267032115f8fbb9db653b8f86264744ae401dd57d3a61d47f97
```
Use "argocd-image-updater [command] --help" for more information about a command.
/ $ /usr/local/bin/argocd-image-updater version
argocd-image-updater: v99.9.9+d714b98
  BuildDate: 2021-07-20T07:31:29Z
  GitCommit: d714b989e46c635d1dd492beab379f61f55e19cd
  GoVersion: go1.14.13
  GoCompiler: gc
  Platform: linux/amd64
/ $ 
```

**Logs**

```
time="2021-07-20T07:25:55Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2021-07-20T07:25:55Z" level=debug msg="Processing application frontend"
time="2021-07-20T07:25:55Z" level=debug msg="Considering this image for update" alias=node application=frontend image_name=some_service_name/node image_tag=330 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:55Z" level=debug msg="Using no version constraint when looking for a new tag" alias=node application=frontend image_name=some_service_name/node image_tag=330 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:56Z" level=debug msg="found 12 from 12 tags eligible for consideration" image="000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/node:330"
time="2021-07-20T07:25:56Z" level=debug msg="target parameters: image-spec= image-name=nginx_node.nodeContainer.registry.image, image-tag=nginx_node.nodeContainer.registry.tag" application=frontend image=000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/node
time="2021-07-20T07:25:56Z" level=debug msg="Image '000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/node:330' already on latest allowed version" alias=node application=frontend image_name=some_service_name/node image_tag=330 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:56Z" level=debug msg="Considering this image for update" alias=nginx application=frontend image_name=some_service_name/nginx image_tag=331 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:56Z" level=debug msg="Using no version constraint when looking for a new tag" alias=nginx application=frontend image_name=some_service_name/nginx image_tag=331 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:56Z" level=debug msg="found 12 from 12 tags eligible for consideration" image="000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/nginx:331"
time="2021-07-20T07:25:56Z" level=debug msg="target parameters: image-spec= image-name=nginx_node.nginxContainer.registry.image, image-tag=nginx_node.nginxContainer.registry.tag" application=frontend image=000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/nginx
time="2021-07-20T07:25:56Z" level=debug msg="Image '000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/nginx:331' already on latest allowed version" alias=nginx application=frontend image_name=some_service_name/nginx image_tag=331 registry=000000000000.dkr.ecr.us-east-2.amazonaws.com
time="2021-07-20T07:25:56Z" level=info msg="Processing results: applications=1 images_considered=2 images_skipped=0 images_updated=0 errors=0"
```

Annotations for argocd application

```
    #-- shared
    argocd-image-updater.argoproj.io/image-list: node=000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/node, nginx=000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/nginx
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: feature/dev-argo-rollouts
    #--  nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/nginx.helm.image-name: nginx_node.nginxContainer.registry.image
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: nginx_node.nginxContainer.registry.tag
    argocd-image-updater.argoproj.io/nginx.allow-tags: 'regexp:^[0-9a-zA-Z]+$'
    #--  nodejs
    argocd-image-updater.argoproj.io/node.update-strategy: latest
    argocd-image-updater.argoproj.io/node.helm.image-name: nginx_node.nodeContainer.registry.image
    argocd-image-updater.argoproj.io/node.helm.image-tag: nginx_node.nodeContainer.registry.tag
    argocd-image-updater.argoproj.io/node.allow-tags: 'regexp:^[0-9a-zA-Z]+$'
```

Helm chart values
```
nginx_node:
  nodeContainer:
    registry:
      image: 000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/node
      tag: 330
  nginxContainer:
    registry:
      image: 000000000000.dkr.ecr.us-east-2.amazonaws.com/some_service_name/nginx
      tag: 330
```

argocd-image-updater-config 
```
data:
  argocd.plaintext: "true"
  log.level: debug
  registries.conf: |
    registries:
    - name: ECR 000000000000.dkr.ecr.us-east-2.amazonaws.com
      api_url: https://000000000000.dkr.ecr.us-east-2.amazonaws.com
      prefix: 000000000000.dkr.ecr.us-east-2.amazonaws.com
      ping: no
      tagsortmode: latest-first
      credsexpire: 1h
      credentials: env:REGISTRY_SECRET
```
