### ISSUE TITLE
Cannot update image tag of dependency in helm-dependency example

### ISSUE THREAD

**Issue by tuananh** [argoproj-labs/argocd-image-updater#242]
**Describe the bug**
Cannot update image tag of dependency in [helm-dependency](https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency) example 

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-helm-dep
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=tuananhorg/bitnami-nginx-demo:1.x
    argocd-image-updater.argoproj.io/myimage.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'git@github.com:tuananh/argocd-demo.git'
    path: helm-dep-example
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-demo
  syncPolicy:
    automated: {}
```

and use the above example with image repo changes to my image.

**Expected behavior**

image to be updated and write back to git.

**Additional context**

**Version**
argocd 2.0.5 and image updater 0.10.2

**Logs**

log from image updater below

```
time="2021-08-21T01:28:52Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2021-08-21T01:28:52Z" level=debug msg="Processing application example-helm-dep"
time="2021-08-21T01:28:52Z" level=debug msg="Image 'tuananhorg/bitnami-nginx-demo' seems not to be live in this application, skipping" application=example-helm-dep
```
