### ISSUE TITLE
InvalidImageName: Digest strategy setting repo/repo:sha:256 format

### ISSUE THREAD

**Issue by AndresJulia** [argoproj-labs/argocd-image-updater#245]
**Describe the bug**
Getting InvalidImageName using digest strategy. Argo seems to be setting the image in the format of `repo/repo:sha56:abcdef` instead of `repo/repo@sha256:abcdef`

This is what the Application annotations looks like 
```
    argocd-image-updater.argoproj.io/image-list: backend=example-repo/app:master
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
```
This is the error im getting on Argo:

```
Failed to apply default image tag "example-repo/app:sha256:792b2e3556d325ed4133def3ea89f67af5b879dbda6e55c5541a522ffafbdaa6": couldn't parse image reference "example-repo/app:sha256:792b2e3556d325ed4133def3ea89f67af5b879dbda6e55c5541a522ffafbdaa6": invalid reference format
```
I tried manually changing to the correct format (example-repo/app@sha256:abcdef) so i guess that is what is wrong.

This is what the .argocd-source.yaml looks like:

```
helm:
  parameters:
  - name: backend.image.repository
    value: example-repo/app
    forcestring: true
  - name: backend.image.tag
    value: sha256:792b2e3556d325ed4133def3ea89f67af5b879dbda6e55c5541a522ffafbdaa6
    forcestring: true
```
