### ISSUE TITLE
running as service account in gcr

### ISSUE THREAD

**Issue by yosefy** [argoproj-labs/argocd-image-updater#246]
**Is your feature request related to a problem? Please describe.**
running as service account in gke

**Describe the solution you'd like**
get the account token if possible and use it to access gcr
so we need to check if we can get the token with http request
and if we do, we may use it to connect to gcr without putting any creads in config

(i think same may go for aws)

**Describe alternatives you've considered**
workarond for now is to mount configmap as script and run it as ext:SCRIPT

configmap is like this:

```
data:
  registries.conf: |
    registries:
    - name: Google Container Registry
      api_url: https://gcr.io
      prefix: gcr.io
      ping: no
      credentials: ext:/app/config/script.sh
      credsexpire: 5m
  script.sh: |
    #!/bin/sh
    echo "_token:$(wget -qO- "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" --header="Metadata-Flavor: Google" | cut -d"\"" -f 4 |rev | sed -rn 's/[.]*(.*)/\1/p' | rev)"
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-image-updater
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/0/configMap/defaultMode
      value: 0777
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-image-updater
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/0/configMap/items/2
      value:
        key: script.sh
        path: script.sh
```
