### ISSUE TITLE
updater removes patch section of patchesJson6902 in existing kustomization.yaml

### ISSUE THREAD

**Issue by yosefy** [argoproj-labs/argocd-image-updater#247]
**Describe the bug**
overwriting parts of kustomization.yaml file wich not supposed to be touched
in our case it is "patch" part of patchesJson6902 being removed

before:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: prod

namespace: XXX

images:
- name: gcr.io/AAA/BBB
  newTag: "0.67"


patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: utils
  patch: |-
    - op: add
      path: /metadata/annotations/link.argocd.argoproj.io~1external-link
      value: http://my.domain.com:8080/node
```

after

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: prod

namespace: XXX

images:
- name: gcr.io/AAA/BBB
  newTag: "0.69"


patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: utils
```
