### ISSUE TITLE
Could not update repo with Git write back

### ISSUE THREAD

**Issue by vietanhduong** [argoproj-labs/argocd-image-updater#248]
**Describe the bug**
When using the WriteBack method of Git, ArgoCD does not update when checking the log, there is an error message as below. I tried adding creds by `git:secret:argocd/repo-93602063` then Git works properly. But image-updater's confingmap is not used. 

**To Reproduce**
ArgoCD image updater config map:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  namespace: argocd
  name: argocd-image-updater-config
data:
  git.user: "Update Bot"
  git.email: "vietanhduong@users.noreply.github.com"
  registries.conf: | 
    registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      ping: yes
      defaultns: library
  git.commit-message-template: |
    Automatic update image of {{ .AppName }}

    {{ range .AppChanges -}}
    Updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
```

**Expected behavior**
- There is no need to specify creds. 
- The commit message should be the same as the configmap. 

**Additional context**

**Version**
Version v0.10.1 (Install with helm)

**Logs**
```
time="2021-08-31T04:59:40Z" level=error msg="Could not update application spec: could not get creds for repo 'https://github.com/vietanhduong/my-cluster.git': credentials for 'https://github.com/vietanhduong/my-cluster.git' are not configured in Argo CD settings" application=resume
time="2021-08-31T04:59:40Z" level=info msg="configmap informer cancelled"
time="2021-08-31T04:59:40Z" level=info msg="secrets informer cancelled"
time="2021-08-31T04:59:40Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```
