### ISSUE TITLE
Digest is not working (Digest, Tag, Helm)

### ISSUE THREAD

**Issue by buddhi-desilva** [argoproj-labs/argocd-image-updater#259]
**Describe the bug**
argocd-image-updater: v0.10.3
argocd: v2.1.2
gitrepo: helm

Strategy
```
argocd-image-updater.argoproj.io/write-back-method: argocd
argocd-image-updater.argoproj.io/image-list: myimagealias=gcr.io/project-name/images-path/my-image-name:my-tag-name
argocd-image-updater.argoproj.io/myimagealias.update-strategy: digest

```

I'm using the digest strategy for image updating and from argocd-image-updater end all seems to work fine, and I'm getting the successfully updated message. Yet ArgoCD doesn't seem to update the image.

```
time="2021-09-16T19:47:35Z" level=info msg="Successfully updated the live application spec" application=dev-environment
```

When I check the Argo CD, I can see the following has been added to parameters, but it does't trigger an update.
```
image.name
  gcr.io/project-name/images-path/my-image-name
image.tag
 sha256:xxxxxxx
```

My approach / requirement is to have  argocd as the write-back method and only the team members updating the deployment repo with image details and repo tags per each environment.

1. Can anyone tell me what I might be doing wrong here?
2. Any help on fixing this issue is appreciated

**Comment by jannfis** [comment]
Hey @buddhi-desilva, I suspect that you will need a different set of parameters to be updated instead if `image.name` and `image.tag` in order for your Helm charts to be correctly rendered.

Please have a look at https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names

Also, for `digest` strategy, keep in mind that if your Chart constructs the image slug such as

```
image: {{ image-name }}:{{ image-tag }}
```

that might not work with digest, because it would result in something like `some-image:sha256:abef...`, but needs to be `some-image@sha256:abef...`. This is an outstanding bug, which will be fixed with v0.11 (because it might break workarounds in place).

**Comment by buddhi-desilva** [comment]
Hi @jannfis, i did try the helm parameters name thing as well, but it didn't work either (I think I've exhausted all the options related to digest strategy).

When I look at the image-updater logs:

Helm / Non Helm config log messages shows pretty much the same:
```
time="2021-09-17T06:57:30Z" level=info msg="Successfully updated image 'gcr.io/project-name/images-path/my-image-name@dummy' to 'gcr.io/project-name/images-path/my-image-name@sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c', but pending spec update (dry run=false)" alias= myimagealias application=some-environment image_name=project-name/images-path/my-image-name image_tag=dummy registry=gcr.io
```

However the parameters updated in the Application manifest are different:

**HELM**
```
parameters:
  - name: image.repository
    value: gcr.io/project-name/images-path/my-image-name
    forceString: true
  - name: image.tag
    value: >-
      sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c
    forceString: true
```

**Non-HELM Config**
```
parameters:
  - name: image.name
    value: gcr.io/project-name/images-path/my-image-name
    forceString: true
  - name: image.tag
    value: >-
      sha256:4e47031bd2549fca9b0d99a36fdc3ebd72022e8510e3efc21f38bc1dca47fe3c
    forceString: true
```

None of them work though..

I think I got to try the name / lexical sort strategy and name the images accordingly at the build time since this isn't seem to work.

**Comment by jannfis** [comment]
What exactly do you mean by "helm" and "non-helm" config? From the updates, it seems clear that the tag update is successful. But in order for Argo CD to render new manifests, your chart needs to consider these parameters.

What are the parameters your Chart uses for setting the image?

**Comment by buddhi-desilva** [comment]
Sorry if i wasn't clear: What i meant was "with helm parameters":
```
....
# argocd-image-updater.argoproj.io/myimagealias.helm.image-tag: image.tag
# argocd-image-updater.argoproj.io/myimagealias.helm.image-name: image.repository
...
```

and "without helm parameters being set":
```
argocd-image-updater.argoproj.io/write-back-method: argocd
argocd-image-updater.argoproj.io/image-list: myimagealias=gcr.io/project-name/images-path/my-image-name:my-tag-name
argocd-image-updater.argoproj.io/myimagealias.update-strategy: digest
```

Chart is using these parameters: 
```
image.tag
image.repository
```


As you said updating from image-updater to argocd seems successful. However, what I don't know is what are the exact params expected by ArgoCD to trigger an update from that end.

**Comment by buddhi-desilva** [comment]
@jannfis, i tried using 
```
argocd-image-updater.argoproj.io/myimagealias.helm.image-spec: image.repository:image.tag
```
and the Application gets updated this way.
```
parameters:
  - name: 'image.repository:image.tag'
    value: >-
      gcr.io/project-name/images-path/my-image-name@sha256:3a6b1c5...
    forceString: true
```

As you've mentioned it is updating to the pattern of `some-image@sha256:abef...`. However, the image isn't getting updated from the ArgoCD end.

Can someone help me out here and point me at the direction I should try to resolve the issue?
