### ISSUE TITLE
Update Kustomize to the ArgoCD Kustomize version

### ISSUE THREAD

**Issue by alexisbel1** [argoproj-labs/argocd-image-updater#268]
**Is your feature request related to a problem? Please describe.**
When the Image Updater updates the image tag in the `kustomization.yaml`, it can fail because some Kustomize v4.2 (the latest version used in ArgoCD) features are not supported in Kustomize v2.0 (current version used in Image Updater).

Example of error with the following `kustomization.yaml` which work with ArgoCD:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../kustomize/internal-api

configurations:
- kustomizeconfig/application.yaml

images:
- name: registry/configuration-data-api
  newTag: v1.5.0

patches:
- path: patch.yaml
  target:
    group: core.oam.dev
    kind: Application
    name: configuration-data-api
    namespace: internal-api
    version: v1beta1
```
Error: 
```txt
level=error msg="Could not update application spec: error unmarshaling JSON: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge" application=internal-api-dev
```

**Describe the solution you'd like**
Update the Kustomize go library to the latest used by ArgoCD.

**Describe alternatives you've considered**
Don't update the `kustomization.yaml` but the `.argocd-source-<appName>.yaml`.
