### ISSUE TITLE
Couldn't update application with helm subchart

### ISSUE THREAD

**Issue by mipsel64** [argoproj-labs/argocd-image-updater#271]
**Describe the bug**
Updater rewrite successfully on git. 
```yaml
helm:
  parameters:
  - name: image.tag
    value: master-f8b813b
    forcestring: true
  - name: image.name
    value: vietanhs0817/ota-server
    forcestring: true
```
The problem is the image tag and the image name should be base on `values.yaml`.
```yaml
# values.yaml
parent-chart:
  server:
    image:
      repository: vietanhs0817/ota-server
      tag: master
...
```

**Expected behavior**
```yaml
helm:
  parameters:
  - name: parent-chart.server.image.tag
    value: master-f8b813b
    forcestring: true
  - name: parent-chart.server.image.repository
    value: vietanhs0817/ota-server
    forcestring: true
```

**Additional context**

**Version**
ArgoCD image updater:  v0.10.1

**Logs**
*No log*
