### ISSUE TITLE
Private repos on non-standard ports image update misinterpretation 

### ISSUE THREAD

**Issue by jamison-maxwell** [argoproj-labs/argocd-image-updater#273]
**Describe the bug**
It appears when using a custom repository with a port specified in the URL, e.g. registry:5000/classic-web produces the following output when the update is attempted:
```
time="2021-10-09T19:41:15Z" level=trace msg="List of available tags found: [4]" alias=classic-web application=classic-feature-argocd image_name=registry image_tag=5000/classic-web registry=
time="2021-10-09T19:41:15Z" level=trace msg="Finding out whether to consider 4 for being updateable" image="registry:5000/classic-web"
time="2021-10-09T19:41:15Z" level=debug msg="found 1 from 1 tags eligible for consideration" image="registry:5000/classic-web"
time="2021-10-09T19:41:15Z" level=info msg="Setting new image to registry:4" alias=classic-web application=classic-feature-argocd image_name=registry image_tag=5000/classic-web registry=
time="2021-10-09T19:41:15Z" level=trace msg="Setting Kustomize parameter registry:4"
time="2021-10-09T19:41:15Z" level=info msg="Successfully updated image 'registry:5000/classic-web' to 'registry:4', but pending spec update (dry run=false)" alias=classic-web application=classic-feature-argocd image_name=registry image_ta
5000/classic-web registry=
```
Notice the following:
```
image_name=registry image_tag=5000/classic-web
```

In this line it seems to me that it is interpreting registry as the image name because it assumes the first thing before the colon and the 5000, which should be the port, 

**To Reproduce**
Have an argocd application defined that includes a port in the registry URL
```
metadata:
  annotations:
    argocd-image-updater.argoproj.io/classic-web.kustomize.image_name: classic-web
    argocd-image-updater.argoproj.io/classic-web.update-strategy: latest
    argocd-image-updater.argoproj.io/image-list: classic-web=registry:5000/classic-web
```

It's worth mentioning that I have tried aliasing and not aliasing the image name, different update strategies, and with and without the kustomize.image_name.

**Expected behavior**
I would expect the image that resolves would be classic-web:x, where x is build ID.

**Version**
```
/ $ argocd-image-updater version
argocd-image-updater: v0.10.3+22ea65e
  BuildDate: 2021-10-09T20:11:54Z
  GitCommit: 22ea65e4269bfbceccab91ca16ccd3e6454e4f7d
  GoVersion: go1.16.5
  GoCompiler: gc
  Platform: linux/arm64


AgoCD version - v2.1.2+7af9dfb
```
