### ISSUE TITLE
invalid token error when using docker pull secret with ghcr.io

### ISSUE THREAD

**Issue by SachinMaharana** [argoproj-labs/argocd-image-updater#276]
**Describe the bug**
Using ghcr.io as container registry, and adding dockerconfigjson as pull-secret , i get invalid token error and not able to update image tags in the helm chart. logs of image-updater
`Could not get tags from registry: Get \"https://ghcr.io/v2/sachinmaharana/argo-app/tags/list\": http: non-successful response (status=403 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"DENIED\\\",\\\"message\\\":\\\"invalid token\\\"}]}\\n\")"`

**To Reproduce**
Creating secret:
`kubectl create secret -n argocd docker-registry ghcr --docker-server=https://ghcr.io/ --docker-username=<githubusername> --docker-password=<githubpersonalaccesstoken> --docker-email=<githubemail>`

Adding Annotation:
```
argocd-image-updater.argoproj.io/image-list: myimage=ghcr.io/sachinmaharana/argo-app

argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^[0-9a-f]{7}$

argocd-image-updater.argoproj.io/myimage.pull-secret: pullsecret:argocd/ghcr

argocd-image-updater.argoproj.io/myimage.update-strategy: latest

argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
```

**Expected behavior**
expected to get the latest image and update the helm chart.

**Additional context**
Using this pod with the same exact secret works:
```
apiVersion: v1
kind: Pod
metadata:
  name: name
spec:
  containers:
  - name: name
    image: ghcr.io/sachinmaharana/argo-app:e9ff6a9
    imagePullPolicy: Always
  imagePullSecrets:
  - name: ghcr
```

**Version**
`argoprojlabs/argocd-image-updater:v0.10.3`

**Logs**
`Could not get tags from registry: Get \"https://ghcr.io/v2/sachinmaharana/argo-app/tags/list\": http: non-successful response (status=403 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"DENIED\\\",\\\"message\\\":\\\"invalid token\\\"}]}\\n\")"`
