### ISSUE TITLE
Support app of type 'Directory'

### ISSUE THREAD

**Issue by JesusRo** [argoproj-labs/argocd-image-updater#294]
**Is your feature request related to a problem? Please describe.**
Cannot use for application type Directory
time="2021-11-05T18:56:23Z" level=trace msg="skipping app 'argocd-image-updater' of type 'Directory' because it's not of supported source type"

**Describe the solution you'd like**
Be able to use it

**Comment by janpieper** [comment]
What exactly is the use-case for this?

ArgoCD applications of type `Directory` are groups of other applications, right? Those should not have any images :thinking: Or is it possible to have references to applications and a real application inside a `Directory`?

**Comment by JesusRo** [comment]
Hi @janpieper, 
I was actually thinking about it for a while couldn´t find an actual use case.
Indeed on groups of applications, makes no sense and in the cases I got an application with just a static deployment manifest, turned into helm with only image and tag values and move on.

Closing now,
sorry and thanks

**Comment by cgawron** [comment]
I don't actually understand why applications of type `Directory` are not supported.

We are using a 'plain' git repo with a set of yaml files to define the application. 
I  would expect that the image updater is able to pull the `latest` image in case it changes (e.g. via a GitHub action). 

In our case, a `Directory` is *not* a collection and we specify the images to pull via `argocd-image-updater.argoproj.io/image-list`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-proxy
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/fhswf/openai-proxy
spec:
  destination:
    namespace: openai-proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/fhswf/openai-proxy.git
    targetRevision: HEAD
```
