### ISSUE TITLE
Broken handling of rename images

### ISSUE THREAD

**Issue by janpieper-gcx** [argoproj-labs/argocd-image-updater#312]
**Describe the bug**

The ArgoCD Image Updater seems to not correctly handle images that have been renamed via `newName` in the `kustomization.yaml`.

**To Reproduce**

_ArgoCD application:_

```yaml
# ...
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: example.azurecr.io/example
# ...
```

_deployment.yaml:_

```yaml
# ...
spec:
  template:
    spec:
      containers:
        - name: backend
          image: example.azurecr.io/example-test
# ...
```

_kustomization.yaml:_

```yaml
# ...
images:
  - name: example.azurecr.io/example-test
    newName: example.azurecr.io/example
    newTag: v1.0.0
```

When pushing a new tag named `v1.1.0`, I get this:

```yaml
# ...
images:
  - name: example.azurecr.io/example-test
    newName: example.azurecr.io/example
    newTag: v1.0.0                    # <-- wrong
  - name: example.azurecr.io/example  # <-- wrong
    newTag: v1.1.0                    # <-- wrong
```

**Expected behavior**

```yaml
# ...
images:
  - name: example.azurecr.io/example-test
    newName: example.azurecr.io/example
    newTag: v1.1.0
```

**Additional context**

_None_

**Version**

v0.11.0

**Logs**

_None_

**Comment by janpieper-gcx** [comment]
Seems like this can be used as a workaround for the moment 🤔 

```yaml
# ...
images:
  # change `example-test:v1.0.0` to `example:v1.0.0`
  - name: example.azurecr.io/example-test
    newName: example.azurecr.io/example
  # change `example:v1.0.0` to `example:v1.1.0`
  - name: example.azurecr.io/example
    newTag: v1.1.0
```

**Comment by jannfis** [comment]
You can set a renamed Kustomize image using the annotation `argocd-image-updater.argoproj.io/<alias>.kustomize.image_name` (refer to https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#custom-images-with-kustomize). 

This works fine with the app source method, and should also work when writing Kustomization files.

**Comment by janpieper-gcx** [comment]
Okay, thanks for your answer. Will have a look 😉 

1. Wouldn't it be better to use `[...].image-name` instead of `[...].image_name`? 🤔 Using `-` everywhere, but `_` for the image name feels inconsistent.

2. Why can't we just lookup the image in the list of images by checking `name` and `newName` to find out what image needs to be updated? 🤔 Or does the image updater fully replace the list of images when it detects a new version of an image? If so, i would be interested in what happens with image definitions that are NOT managed by the ArgoCD application. For example when I have one image that is managed by me (e.g. for my application) and one generic nginx from Docker hub I don't want to update automatically?

**Example:**

```yaml
# ...
  metadata:
    annotations:
      argocd-image-updater.argoproj.io/image-list: example.azurecr.io/example
# ...
```

```yaml
# ...
images:
  - name: example.azurecr.io/example
    newTag: v1.0.0
  - name: nginx
    newTag: 1.21
```
