### ISSUE TITLE
Global filters

### ISSUE THREAD

**Issue by aprohorov-gd** [argoproj-labs/argocd-image-updater#320]
**Is your feature request related to a problem? Please describe.**
I have the `image-list` with 21 images in total. And I want to update all of them with `latest` strategy, but only if tag has `-dev-` keyword.

**Describe the solution you'd like**
I'd like to have global filtering annotation like `argocd-image-updater.argoproj.io/<pre/post>-allow-tags:` and `argocd-image-updater.argoproj.io/<pre/post>-ignore-tags` which will be applied `pre` (before)  or `post` (after) `<image_name>-allow/ignore-tags` filters.

**Describe alternatives you've considered**
Right now I have to add 21 same annotations for every image.

**Comment by janpieper-gcx** [comment]
I do not have 21 images in a single application and I would maybe rethink this, because I can't really come up with any idea why I should have a single application with more than 1-2 images 🤔 But maybe I am just missing something.

I already had a similar idea and I already have a PoC implemented locally 😉 But it differs a bit from your idea... I am a bit unsure if I get your idea correct 🤔 What do you want to achieve with these `pre` and `post` prefixes? I thought about having an annotation without the alias to specify one application-wide default.

* Update strategy
  * Default: `argocd-image-updater.argoproj.io/update-strategy`
  * per Image: `argocd-image-updater.argoproj.io/<alias>.update-strategy`

```yaml
# ...
  metadata:
    annotations:
      argocd-image-updater.argoproj.io/image-list: init=example.azurecr.io/backend-init backend=example.azurecr.io/backend, frontend=example.azurecr.io/frontend
      argocd-image-updater.argoproj.io/update-strategy: latest
      argocd-image-updater.argoproj.io/frontend.update-strategy: semver
```

| Image | Update Strategy |
| --- | --- |
| `example.azurecr.io/backend-init` | latest |
| `example.azurecr.io/backend` | latest |
| `example.azurecr.io/frontend` | semver |

My PoC implements this for `update-strategy`, `ignore-tags`, `allow-tags` and `force-update`.

Maybe I find some time during my xmas vacation to create a PR for this 😉
