### ISSUE TITLE
Loglevel setting not working

### ISSUE THREAD

**Issue by andrei-dascalu** [argoproj-labs/argocd-image-updater#321]
**Describe the bug**
I am starting the image updater pod such:

```yaml
      containers:
        - name: argocd-image-updater
          image: argoprojlabs/argocd-image-updater:v0.11.0
          command:
            - /usr/local/bin/argocd-image-updater
            - run
            - --loglevel
            - warn

```

**Problem**
the update still outputs info messages, instead of just warning.
Note: while the help for the --loglevel flag mentions `warn` as the correct log level name, the level name as show in log is `warning` (though using warning as flag value results in error)

**Expected behavior**

**Additional context**

**Version**
v0.11.0
