### ISSUE TITLE
can't authenticate to dockerhub in v0.11

### ISSUE THREAD

**Issue by jdomag** [argoproj-labs/argocd-image-updater#329]
**Describe the bug**
Can't authenticate in v0.11 to dockerhub with following error:
level=error msg="Could not get tags from registry: unauthorized: authentication required"

**To Reproduce**
Use below config for docker hub credentials. It worked fine in v0.10 release. 
```
    registries: 
      - name: Docker Hub
        api_url: https://index.docker.io/
        ping: yes
        credentials: pullsecret:argocd/regsecret
        defaultns: library

```
**Expected behavior**
argocd image updater can access dockerhub

**Additional context**
Is it related to the latest changes in v0.11? 
`Support for OCI images and registries! We have replaced the pretty old docker-registry-client by Docker's more modern distribution/v3 API.`
There was no information in release notes that it could be breaking change. 

**Version**
0.11.0

**Logs**
```
time="2022-01-04T13:34:21Z" level=error msg="Could not get tags from registry: unauthorized: authentication required"
```
