### ISSUE TITLE
Image updater with Kustomize doesn't work when openapi is used in kustomize

### ISSUE THREAD

**Issue by anjuls** [argoproj-labs/argocd-image-updater#330]
**Describe the bug**
We are hitting a bug in Kustomize (open PR https://github.com/kubernetes-sigs/kustomize/pull/4294#issuecomment-1004784588) which is all together removing `openapi` specs from Kustomize for argo rollout. This is triggered when argo image updater emulates `kustomize edit set image` command. 

**To Reproduce**
1. Use openapi in Kustomization.yaml 
2. Use argocd-image-updater to automatically update the image
3. 🐛  kustomization.yaml's openapi section will be removed which is then applied by argocd. 

**Expected behavior**
kustomization.yaml openapi section is not removed

**Additional context**
Following annotations are used:
```
    argocd-image-updater.argoproj.io/image-list: beecash-api=gcr.io/xxxxx-prod/xxxxx-api
    argocd-image-updater.argoproj.io/xxxxx-api.update-strategy: latest
    argocd-image-updater.argoproj.io/xxxxx-api.allow-tags: regexp:^develop-[0-9a-z]*$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
```

**Version**
```
  argocd-image-updater version
  argocd-image-updater: v99.9.9+d714b98
  BuildDate: 2022-01-05T05:36:51Z
  GitCommit: d714b989e46c635d1dd492beab379f61f55e19cd
  GoVersion: go1.14.13
  GoCompiler: gc
  Platform: linux/amd64
```

**Logs**
Rollout object doesn't have image spec section or corrupted yaml is generated.

----

I understand it is not an argocd-image-updater bug but directly impacted by kustomize bug. I would like to know if there is a way to avoid the current behavior where we avoid `kustomize edit set image` and still update the image?

**Comment by jannfis** [comment]
I believe this also affects Argo CD, because Image Updater does not run `kustomize set ...` on its own.

Have you tried writing to the kustomization.yaml directly, i.e. https://argocd-image-updater.readthedocs.io/en/stable/configuration/applications/#git-write-back-target?

**Comment by anjuls** [comment]
@jannfis sorry for the delay, I have tried with below but still it tries to simulate `kubectl edit set image` command and created a malformed `Rollout` manifest. 

My annotation is like below:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo=gcr.io/heptio-images/ks-guestbook-demo
    argocd-image-updater.argoproj.io/demo.update-strategy: latest
    # argocd-image-updater.argoproj.io/demo.allow-tags: regexp:^[0-9]*[0-9z]*$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-repo-manyfests
    argocd-image-updater.argoproj.io/write-back-target: kustomization
```
