### ISSUE TITLE
Image pull secret not working with gitlab registry

### ISSUE THREAD

**Issue by timdah** [argoproj-labs/argocd-image-updater#345]
Hi 👋 
I'm trying to use the `<image_name>.pull-secret` annotation to work with the gitlab container registry, but my configuration results in the following error:

`
level=error msg="Could not get registry endpoint from configuration: no registry with prefix 'registry.gitlab.com' configured" alias=it application=image-test image_name=cluster9/applications/image-test image_tag=1.0.0 registry=registry.gitlab.com
`

As far as I understand the docs (https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-pull-secrets) no globally configured registry is necessary if the annotation is used?

The secret is also used as image pull secret for the deployment and works for this purpose.

Kind regards

---

__Update:__ \
I forgot, that the Chart (and thus the secret) is deployed in a different cluster, but through argocd.

> If a secret is referenced, the secret must exist in the cluster where Argo CD Image Updater is running in (or has access to).

According to the documentation, access to the cluster is sufficient, but then the secret must be referenced differently I suppose?

__Update 2:__\
Also not working with the secret deployed to argocd namespace and each of these changed annotations:
```yaml
argocd-image-updater.argoproj.io/it.pull-secret: pullsecret:argocd/gitlab-registry-credentials
argocd-image-updater.argoproj.io/it.pull-secret: pullsecret:gitlab-registry-credentials
```

---

__Annotations:__
```yaml
argocd-image-updater.argoproj.io/write-back-method: git
argocd-image-updater.argoproj.io/image-list: it=registry.gitlab.com/cluster9/applications/image-test:^1
argocd-image-updater.argoproj.io/it.pull-secret: pullsecret:image-test/gitlab-registry-credentials
```

__Versions:__
```yaml
argocd: v2.2.1
argocd-image-updater: v0.11.0
```
