### ISSUE TITLE
feat: Synchronize changes back to Git

### ISSUE THREAD

**Issue by jannfis** [argoproj-labs/argocd-image-updater#35]
**Is your feature request related to a problem? Please describe.**

We need to find a proper way how we can synchronize our changes back to Git. Currently, we leverage Argo CD API to set the application parameters for image override, and Argo CD will update the Application resource with parameter overrides in the Kubernetes cluster. These changes need to be persisted somehow.

**Describe the solution you'd like**

I think the details about this need to be discussed and designed properly. This issue is open to collect all kind of ideas & discussions.

**Comment by jannfis** [comment]
There's some ongoing discussion in https://github.com/argoproj/argo-cd/pull/4084

**Comment by hawksight** [comment]
So in my setup, I'm using a directory inside a particular repo to define all my argocd projects / applications in yaml.
General pattern is to update the application yaml in that subdirectory tree in a PR and have that reviewed / merged to master.

```
applications/
  <argocd-project>/<namespace>/<application>.yaml
  stg-eu/default/track.yaml
```

The argocd project == an environment == a k8s cluster. (A declarative setup.)

So my use case would be to reflect the auto image updates back to this single git repository but into the correct application crd yaml file. The feeling I get is that for the general community on slack, they all use a similar 1 repo setup, so perhaps the first iteration of this feature could just target this use case?

Some overall thoughts I've had:

* Allow a default global `git-secret` for the image-updater. 
* Also use an annotation to override the secret for a given application `argocd-image-updater.argoproj.io/git-secret: <my-specific-secret>` - probably limited to secrets that reside where the image-updater is running (not other clusters)
* Some method of defining how to writeback the change. Branch and PR the change, but chose whether it's auto merged or left for review. This probably gets tricky with permissions, depending on how the credentials to git are setup (permissions). Maybe first time round, just create a PR and log in the image-updater.
* If someone rolls back an auto update, there should be something to go and close the PR or update it to say it was rolled back.
* Perhaps auto merge depending on whether auto-sync is enabled. If enabled, auto merge PR. If not, its needs approval. That would make sense matching git to reality.
* Some way to scope which file, either an application crd.yaml or maybe a helm `values.yaml` if people are doing that. Or will image updater always create a parameter that overrides meaning it only ever needs to edit an application crd yaml file?
* As well as opening a PR, show a diff of the changes in the message, so it obvious to humans what changed.
* Specify a commit message / pr title format, or be able to construct it somehow?

I followed the discussion [here](https://github.com/argoproj/argo-cd/pull/4084) and liked the suggested annotations (if i understand them correctly).

Maybe some additions based on some of the points above:
```
annotations:
  # store parameters in crd
  argocd-image-updater.argoproj.io/writeback: crd
  # update parameters in app manifest file
  argocd-image-updater.argoproj.io/writeback: app-manifest-file:./apps/guestbook-app.yaml
  # parameters file
  argocd-image-updater.argoproj.io/writeback: parameters-file
  # Specific secret to use for git: <namespace>/<secret>
  argocd-image-updater.argoproj.io/git-secret: argocd-image-update/git-update
  # Chose whether to auto merge PRs or not. Default will match argcocd sync policy? This will override.
  argocd-image-updater.argoproj.io/git-auto-merge: false
```
