### ISSUE TITLE
Argo CD Image Updater in a different namespace

### ISSUE THREAD

**Issue by AbbasHallal** [argoproj-labs/argocd-image-updater#352]
**Describe the bug**
Argo CD Image Updater in a different namespace is unable to list applications and getting a permission denied error
**To Reproduce**
Create an Argo CD server in argocd namespace
Create ArgoCD Image Updater in a different namespace
Create a role and rolebinding 
Set Serviceaccount in  ArgoCD Image Update deployment
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-image-updater-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
      - services
  - verbs:
      - get
      - list
      - update
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - applications
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - events
```
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-image-updater-rb
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater-sc
    namespace: test-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater-role
  ```
  ```
  apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: argocd-image-updater-config
data:
    argocd.server_addr: argocd-server.argocd.svc.cluster.local
    argocd.insecure: true
    log.level: debug
 ```
**Expected behavior**
`oc auth can-i get applications -n argocd --as system:serviceaccount:test-argo:argocd-image-updater-sc` 
The answer is yes so I expect that my ArgoCD Image Updater instance should have access to Argo CD instance and be able list applications. However, I am getting this error: Error: applications.argoproj.io is forbidden: User \"system:serviceaccount:test-argo:argocd-image-updater-sc\" cannot list resource \"applications\" in API group \"argoproj.io\" in the namespace \"test-argo\""
and I am unable to see applications

**Additional context**
`oc auth can-i get applications -n argocd --as system:serviceaccount:test-argo:argocd-image-updater-sc` 
The answer is yes but the error shows that Argo CDImage updater is not looking in argocd namespace. It's looking in the current namespace where it's running.
**Version**
Argo CD: v2.0.5
Argo CD Image Updater: v0.11.2

**Logs**
Error: applications.argoproj.io is forbidden: User \"system:serviceaccount:test-argo:argocd-image-updater-sc\" cannot list resource \"applications\" in API group \"argoproj.io\" in the namespace \"test-argo\
