### ISSUE TITLE
Fails to update image if the destination uses a name

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj-labs/argocd-image-updater#374]
**Describe the bug**

I'm trying to use image-updater on a Kubernetes Job that needs to run before the actual Deployment comes up (run-once DB setup).

For some reason, the image isn't being updated, and I'm seeing an error in the image-updater logs complaining about the destination cluster URL/Name. Even when I change the Name to a URL in the ArgoCD UI, the error persists.

**To Reproduce**

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-demo1
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      my-api=registry/my-api

    argocd-image-updater.argoproj.io/my-api.force-update: "true"
    argocd-image-updater.argoproj.io/my-api.update-strategy: latest
    argocd-image-updater.argoproj.io/my-api.kustomize.image-name: my-api

spec:
  destination:
    name: in-cluster # this is the name shown in the UI for 
    namespace: core-demo1
  source:
    path: kustomize/env/nonprod/my-demo1
    repoURL: 'https://github.com/org/repo'
    targetRevision: nonprod-demo-env
  project: my-proj
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

To update the image

**Additional context**

![image](https://user-images.githubusercontent.com/10092581/152794267-637b4818-478b-4b32-aae9-2516e09b9b9c.png)

**Version**

```
argocd-image-updater: v0.11.3+f62b7d7
  BuildDate: 2022-02-07T13:12:20Z
  GitCommit: f62b7d7841a42030fe4c75de1951c46b0e7fca2e
  GoVersion: go1.16.13
  GoCompiler: gc
  Platform: linux/amd64

```

**Logs**

```
time="2022-02-07T12:59:55Z" level=error msg="Could not update application spec: rpc error: code = InvalidArgument desc = application destination spec for my-demo1 is invalid: application destination can't have both name and server defined: in-cluster https://kubernetes.default.svc" application=my-demo1     
```
