### ISSUE TITLE
Can't acknowledge the valid credential for image pulling in private registry

### ISSUE THREAD

**Issue by mirdsmulya** [argoproj-labs/argocd-image-updater#376]
**Describe the bug**
Can't acknowledge the valid credential for image pull secret in private registry
Secret for pulling the image from docker hub is working fine and locate on the same namespace as the service

**Expected behavior**
The image will updating to the latest when there are new image pushed to our docker repository

**Additional context**

**Version**
Argocd bitnami chart v3.0.4 ( app version 2.2.5)
Argocd Image Updater v0.11.3

**Logs**

Argocd Image updater logs
```console
time="2022-02-09T06:31:51Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-02-09T06:31:51Z" level=debug msg="Processing application test-paygate-with-ns-paygate-dev"
time="2022-02-09T06:31:51Z" level=debug msg="Considering this image for update" alias=paygate application=test-paygate-with-ns-paygate-dev image_name=yesbossnow/paygate image_tag=cb3e4fd5 registry=
time="2022-02-09T06:31:51Z" level=debug msg="Using no version constraint when looking for a new tag" alias=paygate application=test-paygate-with-ns-paygate-dev image_name=yesbossnow/paygate image_tag=cb3e4fd5 registry=
time="2022-02-09T06:31:51Z" level=error msg="Could not set registry endpoint credentials: no valid auth entry for registry https://registry-1.docker.io found in image pull secret" alias=paygate application=test-paygate-with-ns-paygate-dev image_name=yesbossnow/paygate image_tag=cb3e4fd5 registry=
time="2022-02-09T06:31:51Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```

# argocd application yaml script
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-pagate
  argocd-image-updater.argoproj.io/image-list: paygate=yesbossnow/paygate # <alias>=<organisation>/<image name>
  argocd-image-updater.argoproj.io/paygate.update-strategy: latest
  argocd-image-updater.argoproj.io/paygate.pull-secret: pullsecret:paygate-dev/kataregkey # pullsecret:<namespace>:<secret_name>
spec:
  destination:
    name: ''
    namespace: <namespace>
    server: 'https://kubernetes.default.svc'
  source:
    path: paygate/paygate
    repoURL: '<url repo>'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
```

Also trying using configmap definition but no luck
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  # log.level can be one of trace, debug, info, warn or error
  log.level: debug
  registries.conf: |
    registries:
      - name: Docker Hub
        api_url: https://registry-1.docker.io
        ping: yes
        credentials: pullsecret:argocd/kataregkey
```
