### ISSUE TITLE
Could not set registry endpoint credentials: invalid secret definition: git-creds

### ISSUE THREAD

**Issue by detox3r** [argoproj-labs/argocd-image-updater#414]
While generating generic **git-creds** with private github registry using **ssh** as the docs suggest [here](https://argocd-image-updater.readthedocs.io/en/stable/install/installation/): 

EDIT: I did this , sorry i referenced the wrong link

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/76015484/162101449-0f389f95-0f23-42af-9b92-9e7ef0518612.png">

I get

```
time="2022-04-06T17:47:01Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"                              
time="2022-04-06T17:47:01Z" level=debug msg="Processing application kanban-app"                                                                         
time="2022-04-06T17:47:01Z" level=debug msg="Considering this image for update" alias= application=kanban-app image_name=org/kanban-app image_tag=1
time="2022-04-06T17:47:01Z" level=debug msg="Using no version constraint when looking for a new tag" alias= application=kanban-app image_name=org/k
time="2022-04-06T17:47:01Z" level=error msg="Could not set registry endpoint credentials: invalid secret definition: git-creds" alias= application=kanba
time="2022-04-06T17:47:01Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```

configmap:

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Github Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      ping: no
      credentials: pullsecret:git-creds
      default: true
```

my app:

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/org/kanban-app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
  name: kanban-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:org/board-kanban-helm.git
    targetRevision: HEAD
    path: kanban-app
  destination:
    name: 'arn:aws:xxxxxxxxx'
    namespace: testnamespace
 syncPolicy:
    automated:
      prune: true
```

do I need to use a PAT token and generate another secret to make this work ? if I do writeback per app it also fails

**Comment by jannfis** [comment]
You need to be explicit about the namespace where your secret is at, i.e.
```
credentials: pullsecret:argocd/git-creds
```

**Comment by detox3r** [comment]
so I've created a new PAT token and that worked.
```bash
kubectl create -n argocd secret docker-registry dockerhub-secret \
  --docker-username someuser \
  --docker-password s0m3p4ssw0rd \
  --docker-server "https://ghcr.io"
```
Not a big issue but now I have an **ssh private key** to pull images in my app definition and a **PAT** token that I use for argocd image updater. can I use the ssh token here instead ? I mean Im happy that worked, but now I got 2 ways to do the same thing

@jannfis tried that but same error I was specifying the same secrets on different namespaces anyway

I created a new secret for that PAT token which is called dockerhub-secret

```YAML
Name:         dockerhub-secret
apiVersion: v1
Namespace:    argocd
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/dockerconfigjson

Data
====
.dockerconfigjson:  211 bytes
```
and this is git-creds

```YAML
Name:         git-creds
Namespace:    argocd
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
sshPrivateKey:  411 bytes
```
