### ISSUE TITLE
Image updater does not try to deploy with non-existent image

### ISSUE THREAD

**Issue by maggiedeuitch** [argoproj-labs/argocd-image-updater#415]
I have an app that deploys an applicationset and I've configured image updater using git writeback.

The use case is that if a user updates the image tag with a tag that doesn't exist (example, because of a typo), I want the deployment to fail. However, it seems that it will just deploy a new pod with the existing working image.

Example:

The application is currently set with an image `thisImageExists.v123`.
From the console, specify an image that doesn't exist, `thisdoesntexist.blah`. It will update the applicationset manifest accordingly:

```
template:
  metadata:
      annotations:
        argocd-image-updater.argoproj.io/my-app-service.allow-tags: 'regexp:^thisdoesntexist.blah$'
        argocd-image-updater.argoproj.io/my-app-service.update-strategy: latest
        argocd-image-updater.argoproj.io/image-list: my-app-service=example.azurecr.io/my-app-service
        argocd-image-updater.argoproj.io/write-back-method: git
...
...
  spec:
      destination:
        namespace: mynamespace
        server: 'redacted'
      project: myproject
      source:
        helm:
          parameters:
            - name: image.tag
              value: thisdoesntexist.blah
```

The application manifest is then also updated with the image that doesn't exist.

```
source:
  repoURL: 'redacted'
  path: 'redacted'
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: image.tag
        value: thisdoesntexist.blah
```

However, this doesn't reach the deployment manifest and it starts a new deployment, but using the current image, and not the new one that doesn't exist.

```
containers:
    ...
    ...
          image: >-
            example.azurecr.io/my-app-service:thisImageExists.v123
          imagePullPolicy: Always
```

Logs from image updater show it doesn't try to get the new image.

```
 time="2022-04-05T12:41:31Z" level=debug msg="target parameters: image-spec= image-name=image.name, image-tag=image.tag" application=my-app-service image=example.azurecr.io/my-app-service                                                                                                                                ││time="2022-04-05T12:41:31Z" level=debug msg="Image 'example.azurecr.io/my-app-service:thisImageExists.v123' already on latest allowed version" alias=my-app-service application=my-app-service image_name=my-app-service image_tag=thisImageExists.v123 registry=example.azure.io
```

Is there configuration that I'm missing that will force image updater to try to deploy with the non-existent image, or, alternatively, some workaround that will let my user know that the deployment was unsuccessful with the image they specified?

Note: This works as expected if the user updates with an image tag that exists.
