### ISSUE TITLE
Update loop between latest and specified tags when muiltiple tags for the same image are defined

### ISSUE THREAD

**Issue by ScOut3R** [argoproj-labs/argocd-image-updater#418]
**Describe the bug**
When multiple tags for the same image are defined with the `digest` strategy there's an update loop between the specified tags and `latest` while the digest remains the same.

**To Reproduce**
```
argocd-image-updater.argoproj.io/image-list: track=[...]/track:develop,track-chromium=[...]/track:develop-chromium
argocd-image-updater.argoproj.io/track.update-strategy: digest
argocd-image-updater.argoproj.io/track-chromium.update-strategy
```

Diff:
```
[...]/track:develop-chromium@sha256:96a6edfcf1d1b5102893da3300ce01f6510e6f88cecc4d72201f6bc138cb0ebb -> [...]/track:latest@sha256:96a6edfcf1d1b5102893da3300ce01f6510e6f88cecc4d72201f6bc138cb0ebb
```
```
[...]/track:latest@sha256:7f2b1668c172e08fb5170ad593530f7d79a7c2d229d968315937577d36f638a8 -> [..]/track:develop@sha256:7f2b1668c172e08fb5170ad593530f7d79a7c2d229d968315937577d36f638a8
```

If I were to apply this diff then a few minutes later they'd be reversed, moving from `latest` to `develop-chromium` and `develop` to `latest` respectively.

**Expected behavior**
The specified tags are retained and a difference is picked up only when the digest behind the tags change.

**Additional context**
The feature works as expected with only one image/tag defined.

**Version**
ArgoCD: 2.3.3
Image updater: 0.12.0

**Logs**
```
level=info msg="Starting image update cycle, considering 23 annotated application(s) for update"
level=info msg="Setting new image to [...]/track@sha256:7f2b1668c172e08fb5170ad593530f7d79a7c2d229d968315937577d36f638a8" alias=track application=track-bv-dev image_name=track image_tag="sha256:96a6edfcf1d1b5102893da3300ce01f6510e6f88cecc4d72201f6bc138cb0ebb" registry=[...]
level=info msg="Successfully updated image [...]/track@sha256:96a6edfcf1d1b5102893da3300ce01f6510e6f88cecc4d72201f6bc138cb0ebb to [...]/track@sha256:7f2b1668c172e08fb5170ad593530f7d79a7c2d229d968315937577d36f638a8' but pending spec update (dry run=false)" alias=track application=track-bv-dev image_name=track image_tag="sha256:96a6edfcf1d1b5102893da3300ce01f6510e6f88cecc4d72201f6bc138cb0ebb" registry=[...]
```

Based on the logs and the outcome my suspicion is that using the same image with different tags is the source of the issue?

**Comment by GaeGreco** [comment]
I have a similar problem but with different images and same tag: 
```
argocd-image-updater.argoproj.io/image-list: alias1=registry1/image1:dev, alias2=registry2/image2:dev
argocd-image-updater.argoproj.io/alias1.update-strategy: digest
argocd-image-updater.argoproj.io/alias2.update-strategy: digest
```

If a new image1 with dev tag is pushed:
image1:dev@sha --> image1:dev@new_sha 
BUT 
image2:dev@sha --> image2:latest@same_sha.

The same happens in reverse.
News about this bug?

**Comment by ktzsolt** [comment]
I have something similar (using helm), seemingly randomly in .argocd-source-myapp-develop.yaml file one of the image tags - also seems random to me which image - gets changed to or from latest when it should stay develop
 - name: myapp.image.tag
    value: develop@sha256:a3f06c6dd00c1b5...
to
 - name: myapp.image.tag
    value: latest@sha256:a3f06c6dd00c1b5...

Also sometimes when the digest is changing when it is supposed to the tag is also changing to or from latest, instead of staying develop that triggers an unnecessary rolling update. 

my config in Applications is:
```
annotations:
  argocd-image-updater.argoproj.io/image-list: myapp1=myregistry/myapp1:develop, myapp1=myregistry/myapp2:develop

  argocd-image-updater.argoproj.io/myapp1.helm.image-name: myapp1.image.name
  argocd-image-updater.argoproj.io/myapp1.helm.image-tag: myapp1.image.tag
  argocd-image-updater.argoproj.io/myapp1.update-strategy: digest
  
  argocd-image-updater.argoproj.io/myapp2.helm.image-name: myapp2.image.name
  argocd-image-updater.argoproj.io/myapp2.helm.image-tag: myapp2.image.tag
  argocd-image-updater.argoproj.io/myapp2.update-strategy: digest
  
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/git-branch: main
```
**Version**
ArgoCD: 2.3.3
Image updater: 0.12.0
