### ISSUE TITLE
Not able to use GIT write back with chart from helm chart repo in repoURL

### ISSUE THREAD

**Issue by flozzone** [argoproj-labs/argocd-image-updater#423]
**Describe the bug**

Using GIT write back together with Helm Chart from Helm Chart repository in repoURL isn't supported, because the ArgoCD image-updater tries to resolve the URL under `spec.source.repoURL` as the GIT repository to create update-commits, but since its a Helm repository, this fails with:

```
time="2022-04-22T09:47:06Z" level=error msg="Could not update application spec: could not get creds for repo 'https://nexus.helm.repo.test-app.nwe.org/repository/helm-charts': credentials for 'https://nexus.helm.repo.test-app.nwe.org/repository/helm-charts' are not configured in Argo CD settings" application=test-app
```

**To Reproduce**

Create a Application resource like the following one:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd-gitops
  annotations:
    # configure ArgoCD image updater which updates image.name and image.tag according to latest tag in container registry
    argocd-image-updater.argoproj.io/image-list: frontend=test-repo/test-app
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.helm.image-name: image.name
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/frontend.force-update: "true"

    # write ArgoCD image updater updates back to a separate GIT branch
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: :update-next
spec:
  destination:
    namespace: test-app
    server: https://kubernetes.default.svc
  project: apps
  source:
    chart: room-catalogue
    repoURL: 'https://nexus.helm.repo.test-app.nwe.org/repository/helm-charts'
    targetRevision: 0.1.5
    helm:
      parameters:
        - name: global.hostname
          value: test-app.nwe.org
        - name: image.name
          value: test-repo/test-app
```

**Expected behavior**

Having ArgoCD image updates committed to GIT

**Additional context**

One would expect to have a annotation based configuration alternative to set repoURL to a separate GIT repository url, looking like:

```yaml
argocd-image-updater.argoproj.io/git-repository: https://github.com/nwe/argocd-gitops-repo.git
```

**Version**

quay.io/argoprojlabs/argocd-image-updater:v0.12.0

**Logs**

```
time="2022-04-22T09:47:06Z" level=error msg="Could not update application spec: could not get creds for repo 'https://nexus.helm.repo.test-app.nwe.org/repository/helm-charts': credentials for 'https://nexus.helm.repo.test-app.nwe.org/repository/helm-charts' are not configured in Argo CD settings" application=test-app
```

**Comment by ugurarpaci** [comment]
+1

**Comment by tomsozolins** [comment]
+1

**Comment by karma-git** [comment]
I have the same issue.

Found several treads in slack related to it: [1](https://cloud-native.slack.com/archives/C0296T47CHY/p1641581001004100), [2](https://cloud-native.slack.com/archives/C0296T47CHY/p1652349039905569)

And also think that this feature (git writeback method + external helm repo) could be implemented via additional anotations.

**Comment by filiprafaj** [comment]
hi, my workaround is using app-of-apps pattern:
- add image updater annotations to _app-of-apps.yaml_ 
- source of _app-of-apps.yaml_ is kustomize containing several _Application_ manifests with Helm source
- inside those _Application_  manifests set image using helm parameter
```
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  source:
    ...
    helm:
      parameters:
      - name: image
        value: image_name:image_tag
```
- to tell kustomize to overwrite those values use following configuration (_kustomconfig.yaml_):
```
# kustomconfig.yaml 
images:
- path: spec/source/helm/parameters[]/value
  kind: Application
```
- and inside _kustomization.yaml_
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomconfig.yaml
```

**Comment by flozzone** [comment]
Looks interesting! @filiprafaj could you please complete your example, its kind of hard to understand:
* you refer to app-of-apps.yaml but none is marked as such
* could you put the respective image updater annotations with the git-writeback setting inside the app-of-apps.yaml resource

**Comment by filiprafaj** [comment]
_app-of-apps.yaml_ is something like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=registry.gitlab.com/...:~1
    argocd-image-updater.argoproj.io/myalias.pull-secret: pullsecret:argocd/regcreds
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/image-updater-repocreds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: prod
  source:
    repoURL: https://gitlab.com/some/repo.git
    targetRevision: HEAD
    path: app-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
```
I haven't tested, whether the _force-update_ is necessary
