### ISSUE TITLE
Cannot update image

### ISSUE THREAD

**Issue by pravin-yipl** [argoproj-labs/argocd-image-updater#458]
Images are not updated.
The log from argocd-image-updater pod is:
```
time="2022-07-14T04:36:21Z" level=warning msg="skipping app 'my-app' of type 'Directory' because it's not of supported source type" application=my-app
```
I'm using private gitlab registry for pulling images. Config map is:
```
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Gitlab Container Registry
      prefix: gitlab.yipl.com.np:5050
      api_url: https://gitlab.yipl.com.np:5050
      ping: no
      credentials: pullsecret:argocd/git-creds
      default: true
```
