### ISSUE TITLE
Cannot pull image from GitHub Container Registry

### ISSUE THREAD

**Issue by kaikiat** [argoproj-labs/argocd-image-updater#474]
**Describe the bug**

Hi team, I am trying to integrate argocd with GitHub container registry such that whenever there is a new image, the k8s cluster in argocd will get updated. However, I cannot access the ghcr even though I have added my GitHub PAT token, did I miss out on any steps ?

Run `kubectl logs -n argocd -l app.kubernetes.io/name=argocd-image-updater -f`
```
time="2022-08-24T10:17:51Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-08-24T10:17:51Z" level=debug msg="Processing application sgdecoding-online-scaled"
time="2022-08-24T10:17:51Z" level=debug msg="Considering this image for update" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
time="2022-08-24T10:17:51Z" level=debug msg="Using no version constraint when looking for a new tag" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
time="2022-08-24T10:17:52Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
time="2022-08-24T10:17:52Z" level=error msg="Could not get tags from registry: Get \"https://ghcr.io/v2/kaikiat/python-docker/tags/list\": unauthorized" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
```

**To Reproduce**
1. This is my application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ntuasr=ghcr.io/kaikiat/python-docker
    argocd-image-updater.argoproj.io/ntuasr.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
```
2. Apply configmap. Run `kubectl apply -f configmap.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      api_url: https://ghcr.io
      prefix: ghcr.io
```
3. Create secrets
```
kubectl create secret generic git-creds \
  --from-literal=username=kaikiat \
  --from-literal=password=<github-pat-token> \
  -n argocd
```
4. Set debug level 
```
kubectl patch configmap/argocd-image-updater-config \
  -n argocd \
  --type merge \
  -p '{"data":{"log.level":"debug"}}'
```

5. Restart rollout `kubectl -n argocd rollout restart deployment argocd-image-updater`

**Comment by kaikiat** [comment]
In my other attempt, I tried to use the following configurations

1. Config map
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      api_url: https://ghcr.io
      prefix: ghcr.io
      credentials: secret:argocd/git-creds
```

2. Application 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ntuasr=ghcr.io/kaikiat/python-docker
    argocd-image-updater.argoproj.io/ntuasr.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
```

3. Secrets 
```
kubectl create secret generic git-creds \
  --from-literal=username=kaikiat \
  --from-literal=password=<github_access_token> \
  -n argocd
```

## Error from logs
```
time="2022-08-24T15:41:23Z" level=error msg="Could not set registry endpoint credentials: invalid secret definition: argocd/git-creds" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
time="2022-08-24T15:41:23Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-08-24T15:41:23Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```

**Comment by jannfis** [comment]
Please refer to https://argocd-image-updater.readthedocs.io/en/stable/basics/authentication/#using-a-generic-secret on how to properly create and reference a generic secret for storing registry credentials.

**Comment by kaikiat** [comment]
Hi @jannfis , I tried refining my configuration but I still cannot get the image from ghcr. I have added `#field` when referencing my secret (`credentials: secret:argocd/git-creds#data`) , it seems like it is the wrong field name. So what is the correct field name ? 

This is the logs
```
time="2022-08-26T03:32:07Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-08-26T03:32:07Z" level=debug msg="Processing application sgdecoding-online-scaled"
time="2022-08-26T03:32:07Z" level=debug msg="Considering this image for update" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
time="2022-08-26T03:32:07Z" level=debug msg="Using no version constraint when looking for a new tag" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
time="2022-08-26T03:32:07Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
time="2022-08-26T03:32:07Z" level=error msg="Could not set registry endpoint credentials: could not fetch secret 'git-creds' from namespace 'argocd' (field: 'data'): secret 'argocd/git-creds' does not have a field 'data'" alias=ntuasr application=sgdecoding-online-scaled image_name=kaikiat/python-docker image_tag=latest registry=ghcr.io
```

argocd-image-config.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      api_url: https://ghcr.io
      prefix: ghcr.io
      credentials: secret:argocd/git-creds#data
```

Generic secrets
```
kubectl create secret generic git-creds \
  --from-literal=username=kaikiat \
  --from-literal=password=<pat_token> \
  -n argocd
```

application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ntuasr=ghcr.io/kaikiat/python-docker
    argocd-image-updater.argoproj.io/ntuasr.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
```
