### ISSUE TITLE
Self hosted gitlab registry, custom settings needed?

### ISSUE THREAD

**Issue by yevon** [argoproj-labs/argocd-image-updater#477]
I was trying to setup a self hosted gitlab registry, but I don't really know if I must setup a custom registry or it will work right away. What i have done so far:

Annotations:

```
  annotations:
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/gitlab-registry-secret
    argocd-image-updater.argoproj.io/image-list: mydomain.com/group/project/image
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
```

```
kubectl create -n argocd secret docker-registry gitlab-registry-secret \
  --docker-username "username" \
  --docker-password "password" \
  --docker-server "mydomain.com"
```

And I'm getting:

`time="2022-08-30T17:28:11Z" level=error msg="Could not get tags from registry: Get \"https://mydomain.com/v2/group/project/image/tags/list\": denied: access forbidden"`

I don't really know it that url is really correct for gitlab.

**Comment by yevon** [comment]
Just solved this by setting up the registry as custom in the configmap. I didn't read that it was necessary to restart the pod in the documentation.

Applied:

`kubectl edit configmap argocd-image-updater-config -n argocd`

Added:

```
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Gitlab
      api_url: https://domain.com
      prefix: domain.com
      ping: yes
      credentials: pullsecret:argocd/gitlab-registry-secret
      default: true
```

I just realized that it is unable to write back changes if the repository is based on helm and standard Gitlab artifact repository, and now I'm just changing my repo to just store plain yaml files.
