### ISSUE TITLE
Could not get tag from private registry

### ISSUE THREAD

**Issue by zzbmmbzz** [argoproj-labs/argocd-image-updater#483]
**Version**
`argocd-image-updater:v0.12.0`

**Describe the bug**
I have installed argocd-image-updater and use gitlab private registry. The registry secret is correct (verified), but get the error related to `access denied` . 

**My configurations:**
```
apiVersion: v1
data:
  registries.conf: |
    registries:
    - name: GitRegistry
      api_url: https://registry.privategit.example
      credentials: pullsecret:argocd/test
      default: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
```
After update registry I have rollout restart deployment
```
kubectl rollout restart deployment argocd-image-updater
```
Then check the log:
```
time="2022-10-04T09:40:24Z" level=error msg="Could not get tags from registry: Get \"https://registry.privategit.example/v2/project/dev/test/example-app/tags/list\": denied: access forbidden" alias=test application=test-apps image_name=project/dev/test/example-app image_tag=v22.10.03-1 registry=registry.privategit.example
time="2022-10-04T09:40:24Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```
Could you please help guide/explain me to fix the issue?
Thanks

**Comment by zzbmmbzz** [comment]
resolved issue by add more value to registries.conf
prefix: registry.privategit.example
```
apiVersion: v1
data:
  registries.conf: |
    registries:
    - name: GitRegistry
      api_url: https://registry.privategit.example
      prefix: registry.privategit.example
      credentials: pullsecret:argocd/test
      default: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
```
