### ISSUE TITLE
OpenTelemetry

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj-labs/argocd-image-updater#487]
**Is your feature request related to a problem? Please describe.**

I would like this controller to support OpenTelemetry trace exports in the same fashion as the other controllers.

**Describe the solution you'd like**

Add the `--otlp-address` CLI argument, and allow the `ARGOCD_APPLICATION_CONTROLLER_OTLP_ADDRESS` environment variable.

For Kubernetes (Kustomize) manifests, read in the `otlp.address` from the `argocd-cmd-params-cm`, eg:

```yml
   env:
    - name: ARGOCD_APPLICATION_CONTROLLER_OTLP_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: otlp.address
          name: argocd-cmd-params-cm
          optional: true
```

**Describe alternatives you've considered**
N/A

**Additional context**

- [Application Controller CLI Arguments](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-application-controller/)
- [Declarative Setup](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/)
  - [`argocd-cmd-params-cm`](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cmd-params-cm.yaml)
