### ISSUE TITLE
Application does not update after successful git update 

### ISSUE THREAD

**Issue by ekhaydarov** [argoproj-labs/argocd-image-updater#488]
**Describe the bug**
An application has these image updater annotations, which are exactly the same in all other apps that do work as seen from the logs below saying 13 application but 1 error.
```
annotations:
  argocd-image-updater.argoproj.io/image-list: models=gcr.io/xxx/xxx
  argocd-image-updater.argoproj.io/models.update-strategy: latest
  argocd-image-updater.argoproj.io/models.allow-tags: regexp:^master-[0-9a-z]+$
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/write-back-target: kustomization
```

**To Reproduce**
Not sure how to repro

**Expected behavior**
Image to be updated using git and then argocd to sync the new image tag

**Additional context**

**Version**
This has been happening unnoticed since march and we updated many argo versions. latest one
```
argocd-image-updater: v0.12.0+aee153d
  BuildDate: 2022-03-14T12:45:27Z
  GitCommit: aee153dabeb8b592e4d091c933ae4f77181db653
  GoVersion: go1.17.8
  GoCompiler: gc
  Platform: linux/amd64
```

**Logs**
```
level=error msg="`git commit -a -F /tmp/image-updater-commit-msg3012110323` failed exit status 1" execID=b57b4
level=info msg=Trace args="[git commit -a -F /tmp/image-updater-commit-msg3012110323]" dir=/tmp/git-xxx1605374741 operation_name="exec git" time_ms=300.665167
level=error msg="On branch master\nYour branch is up to date with 'origin/master'.\n\nnothing to commit, working tree clean"
level=info msg="Processing results: applications=13 images_considered=13 images_skipped=0 images_updated=0 errors=1"
level=error msg="Could not update application spec: `git commit -a -F /tmp/image-updater-commit-msg3012110323` failed exit status 1" application=xxx
```
