### ISSUE TITLE
Image updater and sealedSecret

### ISSUE THREAD

**Issue by rkashasl** [argoproj-labs/argocd-image-updater#493]
Hey guys!
i noticed that image updater cannot use sealedSecret as a pullsecret to access a private repository(ACR) even the sealedSecret exists

image-updater log:
> time="2022-11-09T15:39:55Z" level=warning msg="Could not fetch credentials: could not fetch secret 'acrcreds' from namespace 'argo-cd' (field: '.dockerconfigjson'): secrets \"acrcreds\" not found" alias=nginx application=nginx-cd image_name=nginx image_tag=26 registry=unhackgitrepo.azurecr.io

sealedSecret:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acrcreds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCu8EuhYkRv/XR0iQ22vwiaEkybQUz8vbOqMXMNt4stAq7uJS8L8Ox6lyhAC8YF7oFarGwZvdrfICBUnN6PUqeP5jEumjaPsjGYIK0NTbkzS4zYKAOfRJH+TiEBy5tjvdwsVqRLpCN1Dl4EL751ZO3NTib1WkIOu5yFmETTqQ0bEkMBRHvWHOG3qvuppcm0e5YDrkU+uDvPooa7NZjhMlKBCxNAXa2GwV/F3+hIFcfbFKVlm2EjHISGbHI0RxorTytbYtQjwpipojztv5dQsq7LJ93X1mr4is1FH4TAZB+Hg6iQm8pHxzp+FZUifpx8huvpdvWoSCUV9cKJYTsA/bwA0Ihh0hogq7IBz3jdBAFlcapKPbupiTZ7C8hGo84MCpduSBV2MyZpGvOmeIfLAJWvEP6Wq80+bf8FryJs0TmhRtFo4gBf+VJDKJU3rRFCmG6jzZ5Sf3V4qSs+eM4PIlf4h8IJu9NCOfvXu9siOQ1i7HQsACiWXcXsmaZRYfHNO0AD0YuF0wjuxGBM4mhCKuPrXmdsP3QkFWAiAN8SeEhCV6jjxmi5RovhV6r3+L3VcxjeJhNClPfOADH0Zajq673x1SP76wc7lM+d0rcj3sh1aEqd/OUHMPxlJFfsGhOslJSZlEBnzCwl9t3005F2UZpihiByPdqtDw5bZ00JXXz0ALptPuQTUR3MDZzy+P/GtpP6PZ/k0Lw0NASIHLjCo5Eg9TfXKCBrcyV1ObsfmqiHRbHKejiOpFEd6omyitMh7mO+fgqcpKg5E/P7Wcvxl+SZSdjZ06Nuoy2XgTBa5diHs0eBq9wSDDnvn/6GTqfUhkAydsgoS/sU7X5ZUR9RmKkGPtZQhtrrGJPCERBO2MTJwICeAJPBW5CCwz+wXM2k/D3t3+SkKfSW83sG5duK1ZiQhNM08qoCEyBN8bbRqv4TNuNdRaFXL3BuOFBj
  template:
    metadata:
      creationTimestamp: null
      name: acrcreds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
```
here is declarative application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cd
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=unhackgitrepo.azurecr.io/nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/nginx.pull-secret: pullsecret:argo-cd/acrcreds
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://unhackgitrepo.azurecr.io/helm/v1/repo
    targetRevision: 0.1.1
    helm:
      values: |
        replicaCount: 1
        image:
          repository: unhackgitrepo.azurecr.io/nginx
        imagePullSecrets: 
          - name: acrcreds
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-cd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

Might be i missed some part of setting it up correctly but seems now i can't just using pullsealedSecret:namespace:sealedSecret instead according to [repo](https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/image/credentials.go)
any help of securely handling pullsecrets highly appreciated(not with script to generate tokens)
Thanks!
