### ISSUE TITLE
Doesn't Update Image Transformer Correctly

### ISSUE THREAD

**Issue by KrisJohnstone** [argoproj-labs/argocd-image-updater#495]
**Describe the bug**
There's no reference to whether there is support for image transformers or not, but given it supports kustomize and image transformers have been around for yonks and its using a transformer itself figured I'd raise a bug.

The auto updater doesn't recognise/update the image transformer correctly. It instead appends another line item:
```
images:
- name: some-server
  newName: image.com/product-sample-app
  newTag: 5.0.12
- name: image.com/product-sample-app
  newTag: 5.0.14
```

**To Reproduce**
```
images:
- name: some-server
  newName: image.com/product-sample-app
  newTag: 5.0.12
```

**Expected behavior**
```
images:
- name: some-server
  newName: image.com/product-sample-app
  newTag: 5.0.14
```

**Version**
v0.12.0
