### ISSUE TITLE
Cannot authorize with ECR

### ISSUE THREAD

**Issue by hoangduy1912** [argoproj-labs/argocd-image-updater#500]
**Describe the bug**
I tried to configure argocd image updater following this guide https://github.com/argoproj-labs/argocd-image-updater/issues/112#issuecomment-1058465942

But there're some errors

Below is argocd-image-updater pod log
```

time="2022-12-05T09:33:14Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-12-05T09:33:14Z" level=debug msg="Processing application ui-connectivity"
time="2022-12-05T09:33:14Z" level=debug msg="Considering this image for update" alias= application=ui-connectivity image_name=qa image_tag=latest registry=<aws-number>.dkr.ecr.eu-central-1.amazonaws.com
time="2022-12-05T09:33:14Z" level=debug msg="Using version constraint 'latest' when looking for a new tag" alias= application=ui-connectivity image_name=qa image_tag=latest registry=<aws-number>.dkr.ecr.eu-central-1.amazonaws.com
time="2022-12-05T09:33:14Z" level=info msg=/scripts/ecr-login.sh dir= execID=657b6
time="2022-12-05T09:33:15Z" level=error msg="Could not set registry endpoint credentials: invalid script output, must be single line with syntax <username>:<password>" alias= application=ui-connectivity image_name=qa image_tag=latest registry=<aws-number>.dkr.ecr.eu-central-1.amazonaws.com
time="2022-12-05T09:33:15Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"

```

When I execute the script within the pod, the following error was returned
```
/ $ ./scripts/ecr-login.sh
An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

I have checked that the pod is using correct service account. Policy AmazonEC2ContainerRegistryReadOnly was added to that AWS role

Trust relationship added

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:AssumeRoleWithWebIdentity"
            ]
        }
    ]
}
```

Here's my value file

```
config:
  registries:
  - name: ECR
    api_url: https://<aws-number>.dkr.ecr.eu-central-1.amazonaws.com
    prefix: <aws-number>.dkr.ecr.eu-central-1.amazonaws.com   # before v0.12 this needed to be set empty, prefix: ""
    default: true  # not supported before v0.12
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh  #script name should match here and in authScripts 
    credsexpire: 11h
  logLevel: debug
authScripts:
  enabled: true
  scripts: 
    ecr-login.sh: |   # notice script name matches above    
      #!/bin/sh

      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
      
extraEnv:
  - name: AWS_REGION
    value: "eu-central-1"
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws-number>:role/eksWorker
  name: "argocd-image-updater"
metrics:
  serviceMonitor:
    namespace: argocd
```
