### ISSUE TITLE
When pull rate limit is reached application should not be processed

### ISSUE THREAD

**Issue by michalschott** [argoproj-labs/argocd-image-updater#511]
**Describe the bug**

```
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:47Z" level=error msg="error fetching metadata for twingate/connector:1.43.0: could not fetch manifest sha256:4fa7723a70c955819f75d398718b6bf84b457638fa8fa3a0be47c44ab275df3c: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:47Z" level=error msg="error fetching metadata for twingate/connector:1.44.0: could not fetch manifest sha256:0ebc62338d9579f5dd134c2ee46bce77ad43c73766f98cf088de371ec426151f: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:47Z" level=error msg="error fetching metadata for twingate/connector:1.45.0: could not fetch manifest sha256:6e4a5e0cd444534bd4f808b90a65c0d47d49275fb13785e32d16ea5b8e674521: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:48Z" level=error msg="error fetching metadata for twingate/connector:1.46.0: could not fetch manifest sha256:6e8480f87c2c1ea48a946427b8da881fac95387a8aed31f7bf00c6e02feb31bb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:48Z" level=error msg="error fetching metadata for twingate/connector:1.47.0: could not fetch manifest sha256:77cb2cd45bb9a001ee780f51011054722e4f5d9a1a30b478c95a17d70b8de8af: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
argocd-image-updater-5b589d4576-8lqvx argocd-image-updater time="2022-12-27T13:31:51Z" level=error msg="Error fetching metadata for twingate/connector:1.47.0 - neither V1 or V2 or OCI manifest returned by registry: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" alias=twingate application=twingate-k8s-connector image_name=twingate/connector image_tag=1.47.0 registry=
```

A push to repo with 1.42 tag as the newest available was performed. 

Here's app configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: development:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}
    argocd-image-updater.argoproj.io/image-list: twingate=twingate/connector
    argocd-image-updater.argoproj.io/twingate.allow-tags: regexp:^1\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/twingate.kustomize.image-name: twingate/connector
    argocd-image-updater.argoproj.io/twingate.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/bitbucket-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization:/bases/twingate-k8s-connector
  name: twingate-k8s-connector
  namespace: argocd
```

**Expected behavior**

Application should not be processed when pull rate limit is reached because otherwise it will produce misleading pushes.

**Version**
v0.12.1
