### ISSUE TITLE
Could not log in with ECR

### ISSUE THREAD

**Issue by huy-phan-of** [argoproj-labs/argocd-image-updater#514]
**Describe the bug**
I tried to configure argocd image updater following this guide https://github.com/argoproj-labs/argocd-image-updater/issues/112#issuecomment-1058465942

But there're some errors

Below is argocd-image-updater pod log
```
time="2023-01-04T15:58:26Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2023-01-04T15:58:26Z" level=debug msg="Processing application ordinaryfolk-dev-sg1"
time="2023-01-04T15:58:26Z" level=debug msg="Considering this image for update" alias=of-backend application=ordinaryfolk-dev-sg1 image_name=app image_tag=dev-da384e9 registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
time="2023-01-04T15:58:26Z" level=debug msg="Using no version constraint when looking for a new tag" alias=of-backend application=ordinaryfolk-dev-sg1 image_name=app image_tag=dev-da384e9 registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
time="2023-01-04T15:58:26Z" level=info msg=/scripts/auth1.sh dir= execID=98c2c
time="2023-01-04T15:58:26Z" level=error msg="Could not set registry endpoint credentials: invalid script output, must be single line with syntax <username>:<password>" alias=of-backend application=ordinaryfolk-dev-sg1 image_name=app image_tag=dev-da384e9 registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
time="2023-01-04T15:58:26Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```

When I execute the script within the pod, the following error was returned
```
/ $ ./scripts/ecr-login.sh
An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

I have checked that the pod is using the correct service account. that AWS role has full permissions
![image](https://user-images.githubusercontent.com/111115548/210597461-78006fc9-38de-46f4-9476-eff39935b8ab.png)

**My value file**
```
config:
  registries:
  - name: ECR
    api_url: https://xxx.dkr.ecr.eu-central-1.amazonaws.com
    prefix: xxx.dkr.ecr.eu-central-1.amazonaws.com
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/auth1.sh
    credsexpire: 10h
  logLevel: debug
authScripts:
  enabled: true
  scripts: 
    auth1.sh.sh: |   # notice script name matches above    
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
      
extraEnv:
  - name: AWS_REGION
    value: "ap-southeast-1"
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws-number>:role/terraform-pipeline
  name: "argocd-image-updater"
```
