### ISSUE TITLE
Argocd-image updater not deploying new image

### ISSUE THREAD

**Issue by SegunRova** [argoproj-labs/argocd-image-updater#525]
**Describe the bug**
I have deployed argocd-image updater and the pod is running fine, however when I pushed a new image to the container registry argocd-image updater does not deploy the new image. 

Below is yaml file;

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: ms-argocd-poc
spec:
  generators:
  - list:
      elements:
      - cluster: rova-infra-dev
        url: https://kubernetes.default.svc

  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: ms-argocd-poc=<registry-url>:develop
        argocd-image-updater.argoproj.io/ms-argocd-poc.update-strategy: alphabetical
        argocd-image-updater.argoproj.io/ms-argocd-poc.helm.image-name: ms-argocd-poc
        argocd-image-updater.argoproj.io/ms-argocd-poc.helm.image-tag: develop
        #argocd-image-updater.argoproj.io/ms-argocd-poc.allow-tags: regexp:^[0-9]{4}-[0-9]{2}[0-9]{2}$
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/alias.force-update: "true"
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-token
        argocd-image-updater.argoproj.io/git-branch: develop
      name: '{{cluster}}-ms-argocd-poc'
    spec:
      project: default
      source:
        repoURL: <repo-url>
        targetRevision: develop
        path: ms-argocd-poc/overlays/{{cluster}}
        plugin:
          name: argocd-vault-plugin-kustomized
      destination:
        server: '{{url}}'
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**To Reproduce**
Deploy argocd using this [guide](https://argo-cd.readthedocs.io/en/stable/getting_started/) and I deployed argocd-image update using this [guide](https://argocd-image-updater.readthedocs.io/en/stable/install/installation/)

**Expected behavior**
What is expected is that argocd-image-updater grabs the latest image and deploy.

**Additional context**
I did exec into the argocd-image-update pod and executed this command `argocd-image-updater test eu.gcr.io/admin-roava-io/roava.io/services/ms.argocd-poc:develop  --update-strategy alphabetical` it returned the following output

```
DEBU[0000] Creating in-cluster Kubernetes client
INFO[0000] retrieving information about image            image_alias= image_digest= image_name=<registry-url> image_tag=develop registry_url=eu.gcr.io
DEBU[0000] setting rate limit to 20 requests per second  prefix=eu.gcr.io registry="https://eu.gcr.io"
DEBU[0000] Inferred registry from prefix eu.gcr.io to use API https://eu.gcr.io
INFO[0000] Fetching available tags and metadata from registry  application=test image_alias= image_digest= image_name=eu.gcr.io/admin-roava-io/roava.io/services/ms.argocd-poc image_tag=develop registry_url=eu.gcr.io
INFO[0000] Found 4 tags in registry                      application=test image_alias= image_digest= image_name=<registry-url> image_tag=develop registry_url=eu.gcr.io
DEBU[0000] found 4 from 4 tags eligible for consideration  image="eu.gcr.io/admin-roava-io/roava.io/services/ms.argocd-poc:develop"
INFO[0000] latest image according to constraint is eu.gcr.io/admin-roava-io/roava.io/services/ms.argocd-poc:latest  application=test image_alias= image_digest= image_name=<registry-url> image_tag=develop registry_url=eu.gcr.io

```
So I believe this is not a permission issue, as argocd could reach the container registry and retrieve some metadata about the image

**Version**
Deploying the latest version of argocd-image-updater

**Logs**
when I check the logs of the argocd-image updater pod, here is what I get

```
time="2023-01-24T08:23:37Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2023-01-24T08:23:37Z" level=debug msg="Processing application rova-infra-dev-ms-onboarding"
time="2023-01-24T08:23:37Z" level=debug msg="Processing application rova-infra-dev-ms-argocd-poc"
time="2023-01-24T08:23:37Z" level=debug msg="Image 'admin-roava-io/roava.io/ms-argocd-poc' seems not to be live in this application, skipping" application=rova-infra-dev-ms-argocd-poc
time="2023-01-24T08:23:37Z" level=debug msg="Image 'admin-roava-io/roava.io/ms.onboarding' seems not to be live in this application, skipping" application=rova-infra-dev-ms-onboarding
time="2023-01-24T08:23:37Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"

```

Please what am i doing wrong?
