### ISSUE TITLE
Cannot pull images from private ECR repository

### ISSUE THREAD

**Issue by WildEgor** [argoproj-labs/argocd-image-updater#528]
**Describe the bug**
ArgoCD image updater cannot pull image. 
AWS .env blow have access to ECR and may pull/push images locally with docker-compose.

**To Reproduce**
1) Install minikube;
2) Install ArgoCD (using helm);
3) Add own repo with Application-s;
4) Install ArgoCD Image Updater (using helm) with these values:
```
config:
  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      prefix: docker.io
    - name: ECR
      api_url: https://***.dkr.ecr.ap-south-1.amazonaws.com
      prefix: ***.dkr.ecr.ap-south-1.amazonaws.com 
      default: true 
      ping: yes
      tagsortmode: none
      insecure: no
      credentials: ext:/scripts/ecr-login.sh 
      credsexpire: 6h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |   # notice script name matches above    
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

extraEnv:
  - name: AWS_REGION
    value: "ap-south-1"
  - name: AWS_ACCESS_KEY_ID
    value: "****"
  - name: AWS_SECRET_ACCESS_KEY
    value: "****"

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::***:role/***
  name: "argocd-image-updater"
```

5) Find argocd image updater pod and see logs

**Expected behavior**
Successfully pull images from private ECR 

**Version**
Windows 10
Minikube v1.28.0
Docker 20.10.22, build 3a2c30b
Kubernetes 1.25

**Logs**
```
time="2023-01-29T11:15:46Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2023-01-29T11:15:48Z" level=error msg="Could not get tags from registry: Get \"https://***.dkr.ecr.***.amazonaws.com/v2/***/tags/list\": no basic auth credentials" alias=*** application*** image_name=*** image_tag=latest registry=***.dkr.ecr.***.amazonaws.com
time="2023-01-29T11:15:48Z" level=error msg="Could not get tags from registry: Get \"https://***.dkr.ecr.***.amazonaws.com/v2/***/tags/list\": no basic auth credentials" alias=gateway application=*** image_name=*** image_tag=latest registry=***.dkr.ecr.***.amazonaws.com
time="2023-01-29T11:15:48Z" level=info msg="Processing results: applications=2 images_considered=2 images_skipped=0 images_updated=0 errors=2"
```
