### ISSUE TITLE
Image updater changing the tag from the version to "latest" during multiple app image update

### ISSUE THREAD

**Issue by aditya-tanwar** [argoproj-labs/argocd-image-updater#531]
**Describe the bug**
Hello Everyone , How are you all ? Needed help from you guys regarding the image updater when using it for updating multiple images.
I am trying to handle multiple apps by using the capabiltites of  argocd application sets and image updater combined .
In one folder i have my argoaoo.yaml , config.json and all the helm charts in helm repo
```
Directory
|_Charts/ 
|_argoapp.yaml
|_config.json
|_values-dev.yaml
|_values.yaml
|_values-prod.yaml
```
My argoapp.yaml consist "applicationsets" config
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testimage06
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/ooplabs/dps-helm-chart.git'
      revision: imageupdater-test
      files:
      - path: "common/config.json"
  template:
    metadata:
      name: testimage06
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: dop-java-devops-service=prgxuseacrgbl01.azurecr.io/dop-java-devops-service:{{dop_java_devops_service.image_version}}, dps-fanout-service=prgxuseacrgbl01.azurecr.io/dps-fanout-service:{{dps_fanout_service.image_version}}
        argocd-image-updater.argoproj.io/write-back-method: git
        # dop-java-devops-service
        argocd-image-updater.argoproj.io/dop-java-devops-service.force-update: 'true'
        argocd-image-updater.argoproj.io/dop-java-devops-service.helm.image-tag: dop-java-devops-service.image.tag
        argocd-image-updater.argoproj.io/dop-java-devops-service.pull-secret: '{{dop_java_devops_service.pull_secret}}'
        argocd-image-updater.argoproj.io/dop-java-devops-service.update-strategy: '{{dop_java_devops_service.update_strategy}}'
        argocd-image-updater.argoproj.io/dop-java-devops-service.allow-tags: regexp:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}
        # dps-fanout-service
        argocd-image-updater.argoproj.io/dps-fanout-service.force-update: 'true'
        argocd-image-updater.argoproj.io/dps-fanout-service.helm.image-tag: dps-fanout-service.image.tag
        argocd-image-updater.argoproj.io/dps-fanout-service.pull-secret: '{{dps_fanout_service.pull_secret}}'
        argocd-image-updater.argoproj.io/dps-fanout-service.update-strategy: '{{dps_fanout_service.update_strategy}}'
        argocd-image-updater.argoproj.io/dps-fanout-service.allow-tags: regexp:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}
    spec:
      project: default
      source:
        repoURL: '{{app.repourl}}'
        path: '{{app.app_path}}'
        targetRevision: imageupdater-test
        helm:
          valueFiles:
            - '{{app.helm_value_file}}'
      destination:
        server: 'https://kubernetes.default.svc/'
        namespace: dop-java
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m0s
```
config.json file that is being used by argoapp.yaml
```
{  
   "app": {
      "repourl": "https://github.com/ooplabs/dps-helm-chart.git",
      "app_path": "common",
      "helm_value_file": "values-dev.yaml"
   },
   "dop_java_devops_service": {
      "image_version": "2.40.1.0",
      "update_strategy": "digest",
      "pull_secret": "pullsecret:argocd/acr-gbl-dev"
   },
   "dps_fanout_service": {
      "image_version": "1.1.1.0",
      "update_strategy": "digest",
      "pull_secret": "pullsecret:argocd/acr-gbl-dev"
   }
}
```
So basically any edit/modification done on config.json will automatically gets picked up by the argoCD .

I am able to create the application with it initially , but if i update tag for one image lets say according to the above config.json , if i change the image tag of dop_java_devops-service from 2.40.1.0 to 2.41.1.0 or anything.

ArgoCD changes the tag for the other image to latest automatically but the digest remains the same after some time .

Here the tag for dps_fanout-service changes from 1.1.1.0  to latest but the digest (SHA ) remains same as that of 1.1.1.0 only
Not sure why this is happening ? CAN ANYONE HELP AND GUIDE ME IN THE RIGHT DIRECTION IF I AM DOING ANYTHING WRONG (edited)
Need Guidance on this Scenario

**To Reproduce**
I have tried the annotations to only allow the tags with version numbers
 ` argocd-image-updater.argoproj.io/dop-java-devops-service.allow-tags: regexp:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}`
 Also have tried this with both application and applications sets
 I have also tried changing the write back method from git to the argocd one but this bug persists .

**Expected behavior**
Image updater should not change the tag other than what is specified. 

**Additional context**

**Version**
I am using 2.5.6 of argocd and latest version of image updater pluign

**Logs**
![image](https://user-images.githubusercontent.com/86700210/215713070-2ed215e6-ff5d-4a78-8fe8-b2cc2a19d8fd.png)

As you can see it is changing the tag from version number to latest but the digest remains the same
