### ISSUE TITLE
[BUG] Fetch image from private registry error "Could not get tags from registry, x509 certificate signed by unknown authority"

### ISSUE THREAD

**Issue by Alendill** [argoproj-labs/argocd-image-updater#536]
**Describe the bug**
Hello, we are facing a problem that argocd-image-updater cannot pull image from our own docker registry.
This is registries.conf
```
registries:
- name: nexus3-demo1
  api_url: https://nexus3.demo1:8888
  prefix: nexus3.demo1
  insecure: yes
  credentials: secret:argocd/argocd-nexus3
- name: nexus3-demo2
  api_url: https://nexus3.demo2:8888
  prefix: nexus3.demo2
  insecure: yes
  credentials: pullsecret:argocd/argocd-nexus3
```
We have tried add root-ca to /etc/ssl/certs/ and /usr/local/share/ca-certificates/ but it still report x509 error.
Please to help, thank you very much.

**To Reproduce**

**Expected behavior**

**Additional context**

**Version**
Please tell us about the version you encountered the issue with
argocd-image-updater:v0.12.0

**Logs**
Please paste any relevant logs here
```
level=error msg="Could not get tags from registry: Get \"https://nexus3.demo1:8888\":  x509 certificate signed by unknown authority" alias= application=spring-demo image_name=spring-demo image_tag=1.1 registry="nexus3.demo1:8888""
```
