### ISSUE TITLE
Image updater does not work with bitnami helm charts

### ISSUE THREAD

**Issue by danielfoglio** [argoproj-labs/argocd-image-updater#543]
**Is your feature request related to a problem? Please describe.**
[All bitnami charts](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_images.tpl#L6) have 3 values for specifying the image: `{{ registry }}/{{ repository }}:{{ tag }}`, but ArgoCD image updater [requires that only two values are used](https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names): `{{ registry+repository }}:{{ tag }}`.

**Describe the solution you'd like**
Add an an additional annotation to specify the image registry:
`argocd-image-updater.argoproj.io/{{ALIAS}}.helm.image-registry`

**Describe alternatives you've considered**
We have tried the below  helm configuration
```
api:
  image:
    registry: ghcr.io
    repository: path/api
    tag: v1.0.0
```
with the ArgoCd Application Custom Resource annotated like
```
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/path/api:~1.0
    argocd-image-updater.argoproj.io/api.helm.image-name: api.image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: api.image.tag
```
to no avail.

The above configuration will update the image once, but sets the image to `ghcr.io/ghcr.io/path/api:v1.0.x` and this results in the image not being considered for update again.  

**Additional context**
N/A

**Comment by delaskoff** [comment]
Hey @danielfoglio
I've met with the same problem making PoC with image-updater & bitnami and found the workaround specified in code block and it worked for me (for latest v0.12.2, not tested for others)
You can use the following structure:
```
    argocd-image-updater.argoproj.io/image-list: nginx=custom/nginx/repo
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.registry/image.repository
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: image.tag
```

**Comment by jp1337** [comment]
Hi there! Two years later I came across the same issue.
There is still no way to use argocd-image-updater with bitnami helm charts and a custom registry.

The example from @delaskoff is not working anymore using both variables in one string.
In the current version this is completely ignored when the update runs.

My helm values look like this:
```yaml
        mariadb:
          # https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml
          enabled: true
          image:
            registry: harbor.private.registry
            repository: bitnami/mariadb
            tag: "sometag"
            pullPolicy: Always
```

Please add an option to specify the registry and repository in different variables.
