### ISSUE TITLE
ArgoCD application getting out of sync after image update

### ISSUE THREAD

**Issue by saansh45** [argoproj-labs/argocd-image-updater#554]
When we create ArgoCD application, by default we add below ignore differences configuration 
```
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - rollouts-controller
```
These applications have "AutoImageUpdates" configuration enabled. So whenever there is image update, image updater goes and update the argocd application. And when it updates the application, it's removing 

managedFieldsManagers:
        - rollouts-controller

This happens every time whenever there is image update. This causes ArgoCD application to be out of sync. 

![Screen Shot 2023-04-14 at 12 24 23 PM](https://user-images.githubusercontent.com/99209256/232101831-878e50d7-36da-40fa-9135-7f40e63b8e8b.png)
