### ISSUE TITLE
Multiple helm sources: skipping app of type '' because it's not of supported source type

### ISSUE THREAD

**Issue by admssa** [argoproj-labs/argocd-image-updater#558]
**Describe the bug**
The problem is that when you store helm values files in a separate repo you use `spes.sources` instead of `spes.source` in your Application manifests. Thus instead of `sourceType`  string in application status we will have `sourceTypes` array. 

```
status:
  sourceTypes:
  - Helm
```
Unfortunately argocd-image-updater check for `sourceType` only:
https://github.com/argoproj-labs/argocd-image-updater/blob/49825ec4df76b3d2571515525ac71b83efd30acc/pkg/argocd/argocd.go#L520-L533

**To Reproduce**
Replace values surrounded by << >> and create Application with 2 sources and follow the logs:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: test=<<REPO_URL/test>>
    argocd-image-updater.argoproj.io/test.force-update: "true"
    argocd-image-updater.argoproj.io/test.helm.image-tag: deployment.image.tag
    argocd-image-updater.argoproj.io/test.helm.image-name: deployment.image.repository
    argocd-image-updater.argoproj.io/test.update-strategy: latest
    argocd-image-updater.argoproj.io/test.allow-tags: regexp:(tested-dev-)
spec:
  project: default
  sources:
    - repoURL: <<rREPO_URL>>
      chart: test
      targetRevision: 0.1.0
      helm:
        releaseName: test
        valueFiles:
          - $values/dev/values/test.yaml
    - repoURL: "git@github.com:<<YOUR_ORG>>/gitops-backend.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

```

**Version**
0.12.2

**Logs**
```
time="2023-04-24T08:48:37Z" level=info msg="Processing results: applications=0 images_considered=0 images_skipped=0 images_updated=0 errors=0"
time="2023-04-24T08:50:38Z" level=warning msg="skipping app 'test' of type '' because it's not of supported source type" application=test
```

**Comment by amgonzalezf** [comment]
I have the same issue, thanks for reporting it @admssa 

Until this problem gets fixed, the only thing we can do in order to continue using the image updater with helm is to use only one source repository in the application manifest.

**Comment by natalicot** [comment]
Thank you for reporting!
We have the same problem

**Comment by TheDukeDK** [comment]
Same problem here. Pretty important for us as it breaks our preferred development flow.

**Comment by LarsBingBong** [comment]
Any news on this one?

**Comment by TheDukeDK** [comment]
What's the status on this one? We would really like to be able to use a common helm chart and the image updater together and this is blocking.

**Comment by SunnyBerlin** [comment]
First time today wanted to play with image-updater , but we also plan to use multiple sources : (((

**Comment by filipprosovsky** [comment]
Tested @deferraz [PR#578](https://github.com/argoproj-labs/argocd-image-updater/pull/578) by building image from feature branch. However, `sources` worked, but only with `argocd-image-updater.argoproj.io/write-back-method: argocd`.
If the first source is helm repository, it cannot push file to git. I further edited the code to try override repoURL (I can imagine adding an annotation to specify to which repository to push the image updater source file). The file was pushed to git (you also need to specify `spec.sources[0].path` so it is placed to correct location in git. This could possibly be set by annotation when using helm? as path is "ignored" as described in ArgoCD documentation). However, even after file is pushed with correct image and tags specified in annotations, the image is not changed in application, no error shown.

**Comment by askhari** [comment]
@filipprosovsky , I opened this PR #636 that may help with the "git" write back method. Just let me know if that helps.

**Comment by unfernandito** [comment]
Hi. 

It's there any workaroun to make multiple sources work with this tool?

**Comment by Danielkiss9** [comment]
2024 here :)
I see a fix was merged to master - any news on when it will be released as a stable version?

**Comment by larssb** [comment]
Any news?

**Comment by bashirmindee** [comment]
any news ?

**Comment by bart-braidwell** [comment]
looking forward for that fix.

**Comment by TheDukeDK** [comment]
Checking in as well. Can see that PR #636 is merged. Does that cover all the needed use cases? Is there a release where this functionality is targeted?

**Comment by dominykasn** [comment]
Update please?

**Comment by rounakdatta** [comment]
A new release has been published a few days back, please check if it solves for you. For me, the fix is working!

**Comment by zagr0** [comment]
Hi @mecsys , could you please share application example that works for your scenario. Because for me when values.yaml file with tag field is in separate repo I got error like described in the [issue](https://github.com/argoproj-labs/argocd-image-updater/pull/663)

**Comment by mecsys** [comment]
@zagr0 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: podinfo=ghcr.io/stefanprodan/podinfo:6.x.x
    argocd-image-updater.argoproj.io/podinfo.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/podinfo.helm.image-tag: image.tag
    # argocd app strategy
    argocd-image-updater.argoproj.io/write-back-method: argocd
    # git strategy
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/argocd-repo-creds-ops-mecsys    
    # argocd-image-updater.argoproj.io/git-repository: git@github.com:mecsys/mecsys-gitops.git
    # argocd-image-updater.argoproj.io/git-branch: main:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}
spec:
  destination:
    namespace: podinfo
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: podinfo
      repoURL: https://stefanprodan.github.io/podinfo
      targetRevision: 6.5.1
      path: infrastructure/production/apps/ # this is for image updater to know where to store the .argocd-source-appName.yaml file.
      helm:
        releaseName: podinfo
        valueFiles:
          - $values/infrastructure/production/infra-values/podinfo/values.yaml        
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

**Comment by zagr0** [comment]
@mecsys , thank you! It becomes more clear now. I see it still works with parameter overrides, but my expectations were to have changes commited directly in values.yaml file in the image.tag

**Comment by askhari** [comment]
Hi @zagr0 ,

I think that the annotation "argocd-image-updater.argoproj.io/write-back-target: helmvalues" is missing in the configuration. This annotation is used to specify the values file you want to use for the writeback.

I checked the argocd-image-updater documentation for release v0.13.0 and it seems that it's not updated with the changes of the PR #636 . [This is a direct link](https://github.com/askhari/argocd-image-updater/blob/cfbb5c3d0b95a94bacf45ab364b0c45323cd915b/docs/basics/update-methods.md) to the file of that PR with the "helmvalues" documentation. I hope this helps.

Cheers!

**Comment by zagr0** [comment]
Hi @askhari , thank you! I tried it, but it leads to error: "Could not update application spec: could not find an image-name annotation for image foo/bar". Hoping this [issue](https://github.com/argoproj-labs/argocd-image-updater/pull/663) should be a fix for that

**Comment by askhari** [comment]
@zagr0 , could you please share the current configuration you are using for the application manifest please? That may help to understand if there is some misconfiguration or the code does not support it yet.

**Comment by zagr0** [comment]
sure, my app is:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=my.repo.domain:5353/common/app
    argocd-image-updater.argoproj.io/main.pull-secret: pullsecret:argocd/registry
    argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/main.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:./stage/app-helm/values.yaml
    argocd-image-updater.argoproj.io/git-repository: https://my.repo.domain/deploy.git
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: stage
  sources:
    - repoURL: https://my.repo.domain/api/v4/projects/123/packages/helm/stable
      chart: common
      targetRevision: 2.*
      helm:
        releaseName: app
        valueFiles:
          - $values/stage/app-helm/values.yaml
    - repoURL: https://my.repo.domain/deploy.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

the repo tree:
```
stage
  app-helm
    values.yaml
```

values file content:
```
image:
  repository: "my.repo.domain:5353/common/app"
  tag: "dev"
```

**Comment by askhari** [comment]
@zagr0 , maybe [this comment](https://github.com/argoproj-labs/argocd-image-updater/pull/636#issuecomment-1833270712) will help to understand the behaviour.

The thing is that argocd-image-updater uses to different pieces of information that should match in order to work properly, one is the "alias" name that you use for the image and the other one is the docker image name. If those names do not match, then it will throw that error.
You may tray to change the alias name and see what happens. If you do that, you'll also need to change the references to the alias name in the rest of the annotations. I don't know if this changes have a big impact on your configurations, but you may try.

I understant that this is a bug that should be addresses, I just did not have more time to spend since the last time I did the PR. I'm sorry about that.

I hope the info will help.

**Comment by zagr0** [comment]
@askhari , thank you very much to make it clear! Unfortunately I'm not able use alias with the value of image name `common/app`. Because of annotations key naming constrains:
```
metadata.annotations: Invalid value: a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```

**Comment by askhari** [comment]
Hi @zagr0 ,

I did a quick read to the code again and I'm not really quite sure if this will work, but could you try to use this configuration for your annotations and see what happens please?

`
annotations:
    argocd-image-updater.argoproj.io/image-list: my.repo.domain:5353/common/app
    argocd-image-updater.argoproj.io/common_app.pull-secret: pullsecret:argocd/registry
    argocd-image-updater.argoproj.io/common_app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/common_app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/common/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/common/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/common_app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:./stage/app-helm/values.yaml
    argocd-image-updater.argoproj.io/git-repository: https://my.repo.domain/deploy.git
    argocd-image-updater.argoproj.io/git-branch: master
`

I know that this configuration is a bit crappy as there are two annotations that just repeat themselves with a slight different syntax. There is a function called _normalizedSymbolicName()_ that substitutes the "/" character for "_", but it's not used in all the references used to build annotation names in the code. For what I read in the code I think it may work only for this case and configuration.
This behaviour comes from the details explained in [this conversation](https://github.com/argoproj-labs/argocd-image-updater/pull/636/files#r1415418188) on the original PR. I may change the _c.ImageName_ for a _img.normalizedSymbolicName()_ . It may solve the duplicated annotations, but it won't solve the problem of using an alias name for the images. That would need some more digging and changes into the code.

Not sure if this helps. I'm sorry for the inconveniences.

**Comment by zagr0** [comment]
hi @askhari , 

I tried the example but got error complaining about annotation key names: `metadata.annotations: Invalid value...`
To be honest I didn't catch the idea, could you please check if formatted annotations I applied are correct?
```
annotations:
  argocd-image-updater.argoproj.io/image-list: my.repo.domain:5353/common/app
  argocd-image-updater.argoproj.io/common_app.pull-secret: pullsecret:argocd/registry
  argocd-image-updater.argoproj.io/common_app.helm.image-name: image.repository
  argocd-image-updater.argoproj.io/common_app.helm.image-tag: image.tag
  argocd-image-updater.argoproj.io/common/app.helm.image-name: image.repository
  argocd-image-updater.argoproj.io/common/app.helm.image-tag: image.tag
  argocd-image-updater.argoproj.io/common_app.update-strategy: newest-build
  argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
  argocd-image-updater.argoproj.io/write-back-target: helmvalues:./stage/app-helm/values.yaml
  argocd-image-updater.argoproj.io/git-repository: https://my.repo.domain/deploy.git
  argocd-image-updater.argoproj.io/git-branch: master
```

**Comment by askhari** [comment]
Hi @zagr0 ,

It was my mistake thinking that I could use the "/" character. I'm sorry for the error.

I though it was worth to try it because the code reads the annotations in multiple parts. But in some of them uses a function which replaces the "/" from the image name with "_" characters. And in other parts of the code uses directly the ImageName value without replacing the "/".
In the end it's not possible to use another slash in the annotation name because it just allows one.

Again, sorry because I may wasted some of your time with this tests. I'll try to free some time to work on a fix for this asap, but I'm not sure if it will be this week.

**Comment by askhari** [comment]
@zagr0 , I opened #725 which aims to fix the problem of not finding the right annotations.

Let's see if I did the PR in the right way, because it's the first time I try to send a fix for a specific version.

**Comment by askhari** [comment]
@zagr0 , the PR #725 has been merged into master but there isn't a new tag yet. You may try building the master branch or the code of the PR. It should solve the issue when using image aliases.

**Comment by zagr0** [comment]
Thank you very much @askhari ! Most probably there are image builds with latest tag from master, I will check it.

**Comment by zagr0** [comment]
Hi @askhari ,

I have verified with my scenario and now there is no issues with finding image name, this part works, but the changes committed to `values.yaml` file looks really strange.

Image updater was not able to discover `image:` hierarchy and tag inside and just added new entries of `image.tag` and `image.repository` in the file:
```
...
image:
  pullPolicy: IfNotPresent
  repository: my.repo.domain/common/app
  tag: 0.0.6-SNAPSHOT_3ced321a
image.repository: my.repo.domain/common/app
image.tag: 0.0.5
...
```

In addition to that image updater recreated content of the `values.yaml` to format it, ordered all values alphabetically.

**Comment by zagr0** [comment]
here is the [issue](https://github.com/argoproj-labs/argocd-image-updater/issues/744)

**Comment by askhari** [comment]
@zagr0 , thank you for the feedback.

As I understood there are two different issues (please correct me if I'm wrong):
1. Right now, this feature does not search into the YAML hierarchy. Instead, it searches for a key that includes the dots.
2. And it messes up with the order of the keys in the YAML file when writing it back to the repository.

The first thing was fine for us, but I understand that it makes more sense to navigate the hierarchy.
The second one it a bit trickier to solve because it's the natural behaviour of the golang YAML library. To solve it we need to use MapSlice type and it makes more complicated (at least for me).

I'm already working to solve this two issues on this branch of my fork and I'll make a PR shortly: [https://github.com/askhari/argocd-image-updater/tree/fix/helm-values-wbc](https://github.com/askhari/argocd-image-updater/tree/fix/helm-values-wbc).

Again, thank you for noticing it.

Cheers!

**Comment by askhari** [comment]
Hi @zagr0 ,

I opened #748 to solve these problems. Let's see if it gets approved :)

Cheers!

**Comment by askhari** [comment]
@admssa , now that #725 and #748 have been merged into master, could you please test if they solve the problem you  explained in this issue?
If the problem is solved, we may close this issue :) .

**Comment by larssb** [comment]
@askhari thank you so much for working on this! Aren't we waiting for a new version of the image-updater here...to get the fixes you've done?

Thanks.

**Comment by mimartin12** [comment]
Just to follow up before this gets closed, is there any way to get the updater to publish the `.yaml` config in the second provided source? 

From @mecsys example:
```   
 - ref: values
    repoURL: git@github.com:mecsys/mecsys-gitops.git
    targetRevision: main
```

**Comment by ValentinasStormGeo** [comment]
Any updates on this one?

**Comment by fed-col** [comment]
Hi all – I am unsure whether this has been fixed or not, but I still get this error:

```bash
❯ kubectl logs -n argocd deployment/argocd-image-updater

time="2025-04-12T15:30:37Z" level=info msg="argocd-image-updater v99.9.9+a35ad14 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2025-04-12T15:30:37Z" level=warning msg="commit message template at /app/config/commit.template does not exist, using default"
time="2025-04-12T15:30:37Z" level=warning msg="Registry configuration at /app/config/registries.conf could not be read: stat /app/config/registries.conf: no such file or directory -- using default configuration"
time="2025-04-12T15:30:37Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=false, plaintext=false]"
time="2025-04-12T15:30:37Z" level=info msg="Starting health probe server TCP port=8080"
time="2025-04-12T15:30:37Z" level=info msg="Starting metrics server on TCP port=8081"
time="2025-04-12T15:30:37Z" level=info msg="Warming up image cache"
time="2025-04-12T15:30:37Z" level=warning msg="skipping app 'argocd/backend-dev' of type '' because it's not of supported source type" application=backend-dev namespace=argocd
time="2025-04-12T15:30:37Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 1 registries"
```

I have tried the following unsuccessfully:

```bash
❯ kubectl annotate application backend-dev -n argocd \
  argocd-image-updater.argoproj.io/source-type=helm \
  --overwrite
```

My ArgoCD application definition is

```yaml
# Argo CD Application for the Django backend (dev environment)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
  annotations:
    # Image updater annotations
    argocd-image-updater.argoproj.io/image-list: backend=docker.io/<dockerhub_username>/<dockerhub_repo>:backend-dev
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag

    # Tell Argo CD what type of source this is
    argocd.argoproj.io/sync-options: Helm

spec:
  project: default

  source:
    repoURL: https://github.com/<org-or-account>/<github_repo_name>.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

In terms of versions I am running `argocd` with

```bash
❯ argocd version
argocd: v2.14.9+38985bd.dirty
  BuildDate: 2025-04-02T22:58:27Z
  GitCommit: 38985bdcd6c3b031fb83757a1fb0c39a55bf6a24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
```

and `argocd-image-updater`

```bash
❯ kubectl logs -n argocd deployment/argocd-image-updater | grep starting

time="2025-04-12T16:59:36Z" level=info msg="argocd-image-updater v0.16.0+da7ee95 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
```

Note that even with the app created via the Argo CD CLI, latest stable Image Updater, Helm source, and correct annotations — it’s still showing `type: ''`. That is to say running (after login with admin account):

```bash
❯ argocd app create backend-dev \
  --repo https://github.com/<org-or-account>/<github_repo_name>.git \
  --path helm/backend \
  --revision main \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace dev \
  --helm-set image.repository=docker.io/callumleach/dollai-core,image.tag=backend-dev \
  --sync-policy automated
```

Any help (be it a fix, a workaround or a catch in something I've done wrongly) would be super appreciated and welcome!

Many thanks in advance!
