### ISSUE TITLE
ArgoCD Image Updater sync interval not working in v2.7.1

### ISSUE THREAD

**Issue by drensokoli** [argoproj-labs/argocd-image-updater#563]
**Describe the bug**
I recently deployed argocd in a development cluster, where I configured the argocd image updater to sync faster with my docker registry (in intervals of 5 seconds) and the argocd repo server to sync faster with my git repo (timeout reconciliation of also 5 seconds). This configuration was done in argocd version 2.6.7 and it worked really well. 
By the time I deployed it in my production cluster, version 2.7.1 had come out where my development configuration doesn't work and there is no updated documentation for the new version.

**To Reproduce**

- Edit the `argocd-image-updater deployment`:
```
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      containers:

# Edit  the interval at which the argocd image updater checks for latest image in docker registry

      - args:
        - --interval
        - 0m5s
...

```
- Restart the `argocd-image-updater` deployment.

**Expected behavior**

I have connected the `argocd-image-updater` deployment to my docker registry. 
It should also have an `args` key in the container configuration as seen above, but it does NOT, so the image sync time is always by default 180s.

**Additional context**

**Version**
`2.7.1`
