### ISSUE TITLE
Can't pull all images from private ECR repository

### ISSUE THREAD

**Issue by strelok29** [argoproj-labs/argocd-image-updater#567]
**Describe the bug**
ArgoCD can't detect all types of images on Private ECR.
In my case, the `argocd-image-updater` only detect image with `application/vnd.oci.image.index.v1+json` Image manifest media type (our image mainly have `application/vnd.docker.distribution.manifest.v2+json`).

**To Reproduce**
Deploy image updater using helm with theses values
```
config:
  logLevel: "trace"
  registries:
    - name: ECR
      api_url: https://xxx.dkr.ecr.ap-south-1.amazonaws.com 
      prefix: xxx.dkr.ecr.ap-south-1.amazonaws.com
      default: true
      ping: yes
      tagsortmode: none
      insecure: no
      credentials: ext:/scripts/ecr-login.sh
      credsexpire: 10h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: 
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

extraEnv:
  - name: AWS_REGION
    value: "ap-southeast-1"
  - name: AWS_ACCESS_KEY_ID
    value: xxx
  - name: AWS_SECRET_ACCESS_KEY
    value: xxx

extraArgs:
  - --interval
  - 30s
```

**Expected behavior**
All image media type can be pulled successfully 

**Version**
argocd-image-updater v0.12.2
argocd v2.6.7+5bcd846
Kubernetes v1.25

**Logs**
Full log when argocd-image-updater fetch ECR repository
```
level=info msg=/scripts/ecr-login.sh dir= execID=f9ded
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/tags/list"
level=debug msg="Cache hit for xxx:otel" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Getting manifest for image xxx:new (operation 2/4)" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="acquired metadata semaphore" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Getting manifest for image xxx:latest (operation 3/4)" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="acquired metadata semaphore" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Getting manifest for image xxx:test2 (operation 4/4)" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="acquired metadata semaphore" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/manifests/test2"
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/manifests/new"
level=trace msg="OCI SHA digest is sha256:6ced9f9c9facb187ea3f2c0ba073925f6b53745bed59fd2a59787accbb11c301" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/manifests/latest"
level=trace msg="Manifest digest is 03412fbf2bc8a6fb3bf6959842284ab22e62cb5000babee14765bdfb1341083e" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="v2 SHA digest is sha256:801c2e943d5cbe7c940a0c9f19dccd755beeda912b57e6a58355ffccc0e58810" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/blobs/sha256:308784be9e376822463bb481264ae4d2c87f4c66bede94cfd1ded79f3824cb32"
level=trace msg="Manifest digest is 03412fbf2bc8a6fb3bf6959842284ab22e62cb5000babee14765bdfb1341083e" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="v2 SHA digest is sha256:801c2e943d5cbe7c940a0c9f19dccd755beeda912b57e6a58355ffccc0e58810" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/blobs/sha256:03412fbf2bc8a6fb3bf6959842284ab22e62cb5000babee14765bdfb1341083e"
level=trace msg="Performing HTTP GET https://xxx.dkr.ecr.ap-southeast-1.amazonaws.com/v2/xxx/blobs/sha256:03412fbf2bc8a6fb3bf6959842284ab22e62cb5000babee14765bdfb1341083e"
level=debug msg="ignoring OCI manifest sha256:6ced9f9c9facb187ea3f2c0ba073925f6b53745bed59fd2a59787accbb11c301. Manifest platform: linux/arm64, requested: linux/arm64" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=debug msg="No metadata found for xxx:test2" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="released semaphore and terminated waitgroup"
level=debug msg="ignoring v2 manifest sha256:801c2e943d5cbe7c940a0c9f19dccd755beeda912b57e6a58355ffccc0e58810. Manifest platform: linux/arm64, requested: linux/arm64" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=debug msg="No metadata found for xxx:new" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="released semaphore and terminated waitgroup"
level=debug msg="ignoring v2 manifest sha256:801c2e943d5cbe7c940a0c9f19dccd755beeda912b57e6a58355ffccc0e58810. Manifest platform: linux/arm64, requested: linux/arm64" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=debug msg="No metadata found for xxx:latest" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="released semaphore and terminated waitgroup"
```

But only detected an image with the tag `otel` (which uses the image media type that I mentioned above)
```
level=trace msg="List of available tags found: [otel]" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Finding out whether to consider otel for being updateable" image="xxx.dkr.ecr.ap-southeast-1.amazonaws.com/xxx:latest"
level=debug msg="found 1 from 1 tags eligible for consideration" image="xxx.dkr.ecr.ap-southeast-1.amazonaws.com/xxx:latest"
level=info msg="Setting new image to xxx.dkr.ecr.ap-southeast-1.amazonaws.com/xxx:otel" alias=app application=xxx image_name=xxx image_tag=latest registry=xxx.dkr.ecr.ap-southeast-1.amazonaws.com
level=trace msg="Setting Kustomize parameter xxx.dkr.ecr.ap-southeast-1.amazonaws.com/xxx:otel" application=xxx
```
