### ISSUE TITLE
Image tag not updating using Helm chart

### ISSUE THREAD

**Issue by Rachiid007** [argoproj-labs/argocd-image-updater#569]
**Describe the bug**
I'm currently working on setting up a CI/CD pipeline where I'm using Argo CD alongside Argo CD Image Updater and a Helm Chart.

In the definition of one of my deployments (pertaining to the frontend), I'm using a public image from Docker Hub, specifically tagged as "0.0.1". Later, I created new versions of this image, tagged as "0.0.2" and "0.0.3". However, I'm encountering an issue: my application does not recognize these new tags and continues to use the image with the old tag.

**To Reproduce**

1.  Set up a Kubernetes cluster.
2.  Install the relevant Helm Chart. To do so, you can follow the steps provided at this link: https://github.com/Rachiid007/dtt-chart
3.  Here's the manifest of my Argo CD application :

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dtt-isj
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rachiid007/dtt_front:0.x
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Rachiid007/dtt-chart.git"
    path: charts
    targetRevision: HEAD
    helm:
      parameters:
        - name: url
          value: isj.taaltoolbox.be
        - name: namespace.name
          value: isj
        - name: frontend.deployment.replicas
          value: "2"
        - name: frontend.deployment.image.repository
          value: rachiid007/dtt_front
        - name: frontend.deployment.image.tag
          value: 0.0.1
  destination:
    server: "https://kubernetes.default.svc/"
    namespace: isj
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
```

I simply applied this manifest using the command: `kubectl apply -f filename.yaml`

Then a new file named charts/.argocd-source-dtt-isj.yaml was created in my GitHub repository which contains:

```yaml
helm:
  parameters:
  - name: url
    value: isj.taaltoolbox.be
    forcestring: false
  - name: namespace.name
    value: isj
    forcestring: false
  - name: frontend.deployment.replicas
    value: "2"
    forcestring: false
  - name: frontend.deployment.image.repository
    value: rachiid007/dtt_front
    forcestring: false
  - name: frontend.deployment.image.tag
    value: 0.0.1
    forcestring: false
  - name: image.name
    value: rachiid007/dtt_front
    forcestring: true
  - name: image.tag
    value: 0.0.3
    forcestring: true
```

**Expected behavior**
I want the image tag used by my application to be automatically updated to use the most recent tag. In this case, the application should now be using the image tagged as "0.0.3".

**Version**
- Kubernetes: 1.26.4
- HELM: 3.11.3
- Argo CD: 2.7.2
- Argo CD Image Updater: 0.12.2

**Logs**
It's worth noting that I haven't found any specific error messages in the logs that could assist in troubleshooting this issue.

I'm open to any suggestions and assistance to resolve this problem. Feel free to ask me any questions if you need more information. Thank you in advance for your help.
