### ISSUE TITLE
argocd image updater and local regsitry "harbor"

### ISSUE THREAD

**Issue by mehdi1-3** [argoproj-labs/argocd-image-updater#585]
I have a local registry 'harbor' with hostname "harbor.actia.local". 
but argocd Image updater couldn't resolve it. 
It return in logs "level=error msg="Could not get tags from registry: Get \"https://harbor.actia.local/v2/\": dial tcp: lookup harbor.actia.local on 10.96.0.10:53" .
Even though argoCD deploy from the same registry.

Any suggestion?

**Comment by identw** [comment]
For me, it works with the configuration like:
```yaml
    registries:
    - api_url: "https://harbor.example.com"
      credentials: "pullsecret:argocd/registry-secret"
      defaultns: "project-name-in-harbor"
      name: "project-name-in-harbor"
      ping: true
      prefix: "harbor.example.com"
```

**Comment by valkiriaaquatica** [comment]
There is no actual problem with Harbor as repository image source. As @identw  it works with no problem, in my case (even not with ssl) and the secret be created following the docs https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/
```
  registries:
    - name: Harbor
      api_url: http://core.harbor.domain
      defaultns: test
      credentials: pullsecret:argocd/harbor-secret 
      prefix: core.harbor.domain
      insecure: true 
```

your error @mehdi1-3  looks a dns resolution error rather than harbor error
