### ISSUE TITLE
Registry configuration is not being picked up

### ISSUE THREAD

**Issue by Zefool** [argoproj-labs/argocd-image-updater#59]
**Describe the bug**
The a-i-u does not seem to pick up the registry configuration I am providing. There are no logs to this effect at all. 

**To Reproduce**
Configmap argocd-image-updater-config with 
```
data:
  argocd.grpc_web: "false"
  argocd.insecure: "true"
  argocd.loglevel: debug
  argocd.plaintext: "false"
  argocd.server_addr: argocd-server.argocd
  registries.conf: |
    registries:
    - api_url: https://example.com/prefix
      ping: false
      credentials: something
      prefix: xxxx
```

**Expected behavior**
According to the relevant code (https://github.com/argoproj-labs/argocd-image-updater/blob/master/cmd/main.go#L174) I would expect a log line about the registries configuration, either a failure or a success report. But apparently `cfg.RegistriesConf != ""` (L184) is evaluating to false. 

**Additional context**

The registry configuration is correctly mounted in the container

```
cat app/config/registries.conf
registries:
- api_url: https://example.com/prefix
  ping: false
  credentials: something
  prefix: xxxx
```

**Version**
v0.4.0-master

**Logs**
Startup logs:
```
time="2020-08-12T12:49:00Z" level=info msg="argocd-image-updater v0.4.0-master starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2020-08-12T12:49:00Z" level=info msg="ArgoCD configuration: [server=argocd-server.argocd, auth_token=true, insecure=true, grpc_web=false, plaintext=false]"
time="2020-08-12T12:49:00Z" level=info msg="Starting health probe server TCP port=8080"
[EOF]
```
