### ISSUE TITLE
Source image.tag being updated to "latest@sha256:*" instead of just "sha256:*" in git repo

### ISSUE THREAD

**Issue by joshkent22** [argoproj-labs/argocd-image-updater#591]
I'm trying to set up argo cd image updater with digest strategy and git write back, but I'm getting unexpected results in regards to how it is updating the git repo. 

My annotations are the following: 

```
argocd-image-updater.argoproj.io/image-list: app=REPO.dkr.ecr.us-east-1.amazonaws.com/IMAGE:latest
argocd-image-updater.argoproj.io/app.helm.image-name: imagename
argocd-image-updater.argoproj.io/app.helm.image-tag: devtag
argocd-image-updater.argoproj.io/app.update-strategy: digest
argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
```

Image updater is properly picking up and seems to be updating the image with the correct format. 

```
Successfully updated image 'REPO.dkr.ecr.us-east-1.amazonaws.com/pulse360@dummy' to 'REPO.dkr.ecr.us-east-1.amazonaws.com/app@sha256:AAAAAAA', but pending spec update (dry run=false)" alias=app application=perform-integration image_name=app image_tag=dummy registry=REPO.dkr.ecr.us-east-1.amazonaws.com
```

But when it comes time to commit the change to git, I'm getting this: 

```
helm:
  parameters:
  - name: image.name
    value: REPO.dkr.ecr.us-east-1.amazonaws.com/app
    forcestring: true
  - name: image.tag
    value: latest@sha256:AAAAAA
  - name: imagename
    value: REPO.dkr.ecr.us-east-1.amazonaws.com/app
    forcestring: true
  - name: devtag
    value: latest@sha256:AAAAA
    forcestring: true
```

As you can see, it's setting the value as `latest@sha256:AAAA`, which obviously causes an image pull error. 

Any idea why it's doing this?
