### ISSUE TITLE
`managedNamespaceMetadata` is not written back to the Application object after update

### ISSUE THREAD

**Issue by 12345ieee** [argoproj-labs/argocd-image-updater#593]
**Describe the bug**
After the image updater updates the image of an app, therefore changing the fields in the Application object, it doesn't write back the `managedNamespaceMetadata` field.

**To Reproduce**
Create an Application like the one below, publish a new version of the docker image, watch as the updated spec is missing the
`managedNamespaceMetadata` part.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage
    argocd-image-updater.argoproj.io/update-strategy: newest-build
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: myns
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: mypath
    repoURL: 'myrepo.git'
    targetRevision: mybranch
  syncPolicy:
    managedNamespaceMetadata: # here lies the issue
      labels:
        app.kubernetes.io/managed-by: argocd
```

**Expected behavior**
For the `managedNamespaceMetadata` section to remain as-is.

**Additional context**
This field is a recent addition to the Application spec, the image updater needs to either update its internal Application spec or write back all the fields it doesn't know unchanged.

**Version**
Argocd v2.7.7+4650bb2.dirty
image-updater latest (id 08ee4f697f24d69b09a3)

**Logs**
None out of ordinary

**Thanks**
This project saved me a TON of work rolling out continuous delivery, I'm saddened to see less activity and no more of an active push to get it integrated into argocd proper, let me know if I can help somehow.
