### ISSUE TITLE
Kustomize install is failing

### ISSUE THREAD

**Issue by rdpa** [argoproj-labs/argocd-image-updater#61]
**Describe the bug**
`kubectl apply -k base/` install is failing on v0.3.1 because directories are listed in the `resources` section. Should either move these directories to `bases` or list each file individually.

**To Reproduce**
create base/kustomization.yaml with the following contents:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj-labs/argocd-image-updater/manifests/base/?ref=v0.3.1
```
run `kubectl apply -k base/`

**Expected behavior**
Manifests would be applied to the cluster

**Additional context**
The kustomization.yaml file is abbreviated and other resources relevant to our deployment have been omitted, but attempting install with both yields the same result.

**Version**
kubectl v1.18.6
kubernetes v1.17.9-eks-4c6976

**Logs**
```bash
$ kubectl apply -k base
error: AccumulateTarget: rawResources failed to read Resources: Load from path ./config failed: './config' must be a file (got d='/private/var/folders/pv/r1tbm8n92mx9t46kqx68bz6c0000gn/T/kustomize-669160585/manifests/base/config')
```
