### ISSUE TITLE
CronWorkflow does not get image updated

### ISSUE THREAD

**Issue by pretext-mats** [argoproj-labs/argocd-image-updater#610]
**Describe the bug**
- I use ArgoCD with Argo Image updater.
- Apps that are using CronWorkflow don't get image tags  updated in workflows
- Image tags are synced into .argo_*** kustomize file ok though

**To Reproduce**
See below for simplest set up to reproduce

**Expected behaviour**
image tag should be updated to the latest

**Additional context**
n/a

**Version**
Please tell us about the version you encountered the issue with
Argo CD: v2.7.6+00c914a.dirty 
Argo Workflow:  v3.4.8
Argo image updater: v0.12.2

**Logs**
Please paste any relevant logs here

01-cronworkflow.yaml
```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
  namespace: jobs
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      container:
        # The below never gets updatedby Argo image updater
        image: alpine:3.17.1
        command: [sh, -c]
        args: ["echo 'BAM! I am a whale'; sleep 5"]
```
kustomization.yaml
```YAML
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-cronworkflow.yaml
```

test-cron-wf-argo-app.yaml
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-cron-wf-argo-app-app
  labels:
    job: test-cron-wf-argo-app
  annotations:
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/image-list: 'alpine=alpine:~3.17.1'
    argocd-image-updater.argoproj.io/alpine.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: 'git:secret:argocd/[YOUR SECRET]'
spec:
  destination:
    name: ''
    namespace: jobs
    server: 'https://kubernetes.default.svc'
  source:
    path: [PATH/TO/THE/ABOVE/KUSTOMIZE]
    repoURL: 'git@PATH/TO/GIT/REPO'
    targetRevision: master
  sources: []
  project: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
```
Other types siuch as deployments or KEDA scalers work just fine only Argo's CronWorkflow seem to be an issue here.
