### ISSUE TITLE
IU not working as expected?

### ISSUE THREAD

**Issue by lpzdvd-packlink** [argoproj-labs/argocd-image-updater#638]
**Describe the bug**
Probably I'm missing something but just wanted to share my (frustrated) experience:
I've been able to configure IU and I'm using an `ApplicationSet` for a bunch of apps in a centralized repository:

```
  generators:
    - git:
        directories:
          - path: my-folder/*
        repoURL: https://github.com/my-org/my-repo
        revision: master
```

I expect the master tag to be updated every time a new `master` image is available like:

myapp1:master -> new @sha256..
myapp2:master -> new @sha256..

The issue I'm facing is:
- From the logs, I see IU tries to update deployments with the new master image (and I also see the delta in the UI)
- but after some seconds it terminates the new pod is trying to run
- the old pod (master) remains deployed so it never gets an update.

**Expected behavior**
I expect the master tag to be updated every time a new `master` image is available

**Additional context**
My current settings are

```
      syncPolicy:
        automated: {}
        syncOptions:
          - RespectIgnoreDifferences=false
      ignoreDifferences:
        - group: networking.k8s.io
          kind: Ingress
          jqPathExpressions:
            - ".spec.rules[0].host"
            - '.metadata.annotations["kubernetes.io/ingress.global-static-ip-name"]'
 ```

I need the `RespectIgnoreDifferences=false` setting because a mutating webhook already present in the cluster is modifying ingresses 

**Version**
v0.12.2

**Logs**
```
time="2023-11-02T16:43:43Z" level=info msg="Successfully updated image 'eu.gcr.io/< OMMITEAD >/my-app@dummy' to 'eu.gcr.io/< OMMITED >/my-app@sha256:4747239eaac6b8279e4ecc40f8de69bbfff0fbf3bec44ddd74dbb33b497272ab', but pending spec update (dry run=false)" alias=my-app-alias application=my-app image_name=< OMMITED >/my-app image_tag=dummy registry=eu.gcr.io
```
