### ISSUE TITLE
Multiple secrets for the same registry [ghcr.io]

### ISSUE THREAD

**Issue by biclighter81** [argoproj-labs/argocd-image-updater#639]
**Is your feature request related to a problem? Please describe.**
Hi together maybe this isn't a feature request rather a "How To" question. I would like to check multiple Image manifests from the ghcr.io Registry, which are not all saved on the same account. So I have to use multiple API tokens for the same registry. This is my current configuration:

```
 registries: 
      - name: Docker Hub
        api_url: https://docker.io
        ping: yes
        credentials: secret:argocd/image-updater-pullsecrets#token
      - name: A GHCR
        api_url: https://ghcr.io
        ping: yes
        prefix: ghcr.io/a <-- tried to use prefix so the image updater can decide which secret it has to use
        credentials: secret:argocd/image-updater-pullsecrets-a-ghcr#token
      - name: B GHCR
        api_url: https://ghcr.io
        ping: yes
        prefix: ghcr.io/b <-- tried to use prefix so the image updater can decide which secret it has to use
        credentials: secret:argocd/image-updater-pullsecrets-b-ghcr#token
```
But it seems like the image updater isn't able to decide which token it has to use for which image. For the example image `ghcr.io/b/image1` I get a 401 error. It's able to check `ghcr.io/a/image1`

**Describe the solution you'd like**
I would like to set the prefix f.e. `ghcr.io/biclighter81` and the image updater should pick the right secret for the job.

Is this functionality already implemented?

Thank you :)
