### ISSUE TITLE
git write-back for helm application does not work

### ISSUE THREAD

**Issue by josedev-union** [argoproj-labs/argocd-image-updater#647]
**Describe the bug**
I deploy an application as following. In `charts/superset` path, there is a helm chart manifests and it is deployed correctly.
But its `sourceType` is none so argo image updater skips this application even if I set the annotations.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: main=ortege01.azurecr.io/ortege/superset:ortege
    argocd-image-updater.argoproj.io/main.update-strategy: digest
    argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
  name: superset
  namespace: argo-cd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: superset
  source:
    path: charts/superset
    repoURL: https://github.com/ortege-xyz/gitops
    targetRevision: HEAD
    helm:
      releaseName: superset
```

To mitigate this `sourceType` issue, I released the chart to gh pages and updated the app source like this.
```yaml
spec:
  source:
    chart: superset
    repoURL: https://ortege-xyz.github.io/gitops
    targetRevision: 0.10.10
    helm:
      releaseName: superset
```
Then the `sourceType` is detected as `Helm` so image updater detects this. But now it is failing because of auth error.
```sh
level=error msg="Could not update application spec: could not get creds for repo 'https://ortege-xyz.github.io/gitops': credentials for 'https://ortege-xyz.github.io/gitops' are not configured in Argo CD settings" application=superset
```
This `ortege-xyz.github.io` gh release page url is not the git url in fact.

How can I use git write-back for helm application?

**To Reproduce**
I mentioned above.

**Expected behavior**
New image tag should be committed to git repo.

**Additional context**

**Version**
0.12.2

**Logs**
```sh

argo-cd/argocd-image-updater-79cbbdc6b4-9z527[argocd-image-updater]: time="2023-11-26T18:29:41Z" level=error msg="Could not update application spec: could not get creds for repo 'https://ortege-xyz.github.io/gitops': credentials for 'https://ortege-xyz.github.io/gitops' are not configured in Argo CD settings" application=superset
argo-cd/argocd-image-updater-79cbbdc6b4-9z527[argocd-image-updater]: time="2023-11-26T18:29:41Z" level=info msg="Processing results: applications=1 images_considered=2 images_skipped=0 images_updated=0 errors=1"
```

**Comment by kaweit** [comment]
Hi @josedev-union ， May I know how did you fix it? I also meet this issues.

**Comment by josedev-union** [comment]
> Hi @josedev-union ， May I know how did you fix it? I also meet this issues.

@kaweit i uploaded the chart manifest in the same git repository, `charts/superset` path instead of publishing via gh pages. Then updated the application spec as following;
```yaml
  source:
    path: charts/superset
    repoURL: git@github.com:Ortege-xyz/gitops
    targetRevision: main
```
