### ISSUE TITLE
git write-back-method

### ISSUE THREAD

**Issue by cacaocal** [argoproj-labs/argocd-image-updater#659]
I have an app that has multiple service images, but git writes back with only one image

```
app
  annotations:
    argocd-image-updater.argoproj.io/image-list: "stablecoin-mobile=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:stablecoin-mobile-poc4_main, stablecoin-manage=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:stablecoin-manage-poc4_main, business=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-sp-business_main ,chainsync=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-sp-chainsync_main,gateway=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-gateway_main,manage=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-sp-manage_main,message=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-message_main,rbac=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-rbac_main,transaction=aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-sp-transaction_main"


    argocd-image-updater.argoproj.io/stablecoin-mobile.update-strategy: name
    argocd-image-updater.argoproj.io/stablecoin-mobile.allow-tags: regexp:^stablecoin-mobile-poc4_V
    argocd-image-updater.argoproj.io/stablecoin-mobile.kustomize.image-name: aa45454544.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:stablecoin-mobile-poc4_main
    argocd-image-updater.argoproj.io/stablecoin-mobile.pull-secret: ext:/scripts/ecr-ap-southeast-1-login.sh
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/abc-git-ssh-creds
  ......
```
```
`.argocd-source-app.yaml
kustomize:
  images:
  - 759904182533.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-wallet_main=759904182533.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-wallet_V1.3.3
`
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: kustomize-

resources:
  - ../../base

images:
- name: 759904182533.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-business_main
  newTag: udpn-cbdc-business_V1.3.3

- name: 759904182533.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-chainsync_main
  newTag: udpn-cbdc-chainsync_V1.3.3

- name: 759904182533.dkr.ecr.ap-southeast-1.amazonaws.com/poc3:udpn-cbdc-gateway_main
  newTag: udpn-cbdc-gateway_V1.3.3

```
