### ISSUE TITLE
Image Updater never updates images - it identifies there needs to be an update

### ISSUE THREAD

**Issue by jtaleric** [argoproj-labs/argocd-image-updater#668]
**Describe the bug**
I see this constantly in the log file

```
time="2024-01-17T20:29:13Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2024-01-17T20:29:13Z" level=debug msg="Processing application dashboard-test"
time="2024-01-17T20:29:13Z" level=debug msg="Considering this image for update" alias=frontend application=dashboard-test image_name=jtaleric/frontend image_tag=latest registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="Using version constraint 'latest' when looking for a new tag" alias=frontend application=dashboard-test image_name=jtaleric/frontend image_tag=latest registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="found 1 from 1 tags eligible for consideration" image="quay.io/jtaleric/frontend:latest"
time="2024-01-17T20:29:13Z" level=info msg="Setting new image to quay.io/jtaleric/frontend@sha256:13508aa2fa1004a3567cce29e63f35bfc44553a3c239c8ba49418caada133c45" alias=frontend application=dashboard-test image_name=jtaleric/frontend image_tag=dummy registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="target parameters: image-spec= image-name=image.name, image-tag=image.tag" application=dashboard-test image=quay.io/jtaleric/frontend
time="2024-01-17T20:29:13Z" level=info msg="Successfully updated image 'quay.io/jtaleric/frontend@dummy' to 'quay.io/jtaleric/frontend@sha256:13508aa2fa1004a3567cce29e63f35bfc44553a3c239c8ba49418caada133c45', but pending spec update (dry run=false)" alias=frontend application=dashboard-test image_name=jtaleric/frontend image_tag=dummy registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="Considering this image for update" alias=backend application=dashboard-test image_name=jtaleric/backend image_tag=latest registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="Using version constraint 'latest' when looking for a new tag" alias=backend application=dashboard-test image_name=jtaleric/backend image_tag=latest registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="found 1 from 1 tags eligible for consideration" image="quay.io/jtaleric/backend:latest"
time="2024-01-17T20:29:13Z" level=info msg="Setting new image to quay.io/jtaleric/backend@sha256:98c607a23338c6256c003c1a737b21f5ec2b31eac17dd1483c932c5a47055749" alias=backend application=dashboard-test image_name=jtaleric/backend image_tag=dummy registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="target parameters: image-spec= image-name=image.name, image-tag=image.tag" application=dashboard-test image=quay.io/jtaleric/backend
time="2024-01-17T20:29:13Z" level=info msg="Successfully updated image 'quay.io/jtaleric/backend@dummy' to 'quay.io/jtaleric/backend@sha256:98c607a23338c6256c003c1a737b21f5ec2b31eac17dd1483c932c5a47055749', but pending spec update (dry run=false)" alias=backend application=dashboard-test image_name=jtaleric/backend image_tag=dummy registry=quay.io
time="2024-01-17T20:29:13Z" level=debug msg="Using commit message: "
time="2024-01-17T20:29:13Z" level=info msg="Committing 2 parameter update(s) for application dashboard-test" application=dashboard-test
time="2024-01-17T20:29:13Z" level=info msg="Successfully updated the live application spec" application=dashboard-test
time="2024-01-17T20:29:13Z" level=info msg="Processing results: applications=1 images_considered=2 images_skipped=0 images_updated=2 errors=0"
```

The Image Updater sees there should be an update, yet it never actually updates the image? 

**To Reproduce**
Annotations
```
  annotations:
    argocd-image-updater.argoproj.io/backend.force-update: '"true"'
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.force-update: '"true"'
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: frontend=quay.io/jtaleric/frontend:latest,backend=quay.io/jtaleric/backend:latest

```

**Expected behavior**
The deployment is updated with the new image.

**Comment by jtaleric** [comment]
```
  annotations:
    argocd-image-updater.argoproj.io/backend.force-update: '"true"'
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.force-update: '"true"'
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: frontend=quay.io/jtaleric/frontend:latest,backend=quay.io/jtaleric/backend:latest
```

Updated the helm parms and we are golden.
