### ISSUE TITLE
starts getting timeout errors with ECR registeries until pod is restarted

### ISSUE THREAD

**Issue by pdeva** [argoproj-labs/argocd-image-updater#679]
**Describe the bug**
seeing timeout errors with ECR from time to time. simply restarting the image-updater pod fixes it. only for the problem to randomly surface hours later...

**To Reproduce**
this is the relevant config of image updater helm chart:

```yaml
              - name: config.registries[0].name
                value: "ECR"
              - name: config.registries[0].api_url
                value: "https://xxx.dkr.ecr.us-east-1.amazonaws.com"
              - name: config.registries[0].prefix
                value: "xxx.dkr.ecr.us-east-1.amazonaws.com"
              - name: config.registries[0].default
                value: "true"
              - name: config.registries[0].ping
                value: "true"
              - name: config.registries[0].insecure
                value: "false"
              - name: config.registries[0].credentials
                value: "ext:/scripts/ecr_login.sh"
              - name: config.registries[0].credsexpire
                value: "11h"
              - name: "authScripts.enabled"
                value: "true"
              - name: 'authScripts.scripts.ecr_login\.sh'
                value: >
                  #!/bin/sh

                  aws ecr --region us-east-1 get-authorization-token --output text --query
                  'authorizationData[].authorizationToken' | base64 -d
```

**Expected behavior**
if the auth works once, it should work always. shouldnt randomly time out. shouldnt need pod restarts to fix.

**Additional context**

**Version**

0.12.2

**Logs**

```
Could not set registry endpoint credentials: error executing /scripts/ecr_login.sh: `/scripts/ecr_login.sh` failed timeout after 10s
```
