### ISSUE TITLE
Update strategy: newest-build not working 

### ISSUE THREAD

**Issue by congvan1** [argoproj-labs/argocd-image-updater#697]
**Describe the bug**
I using argocd image updater latest (sha256:b3622d981368b5dc31e7d85545c3572e4a1c990cbe2403f8bb8053aa70766672). It was working fine with update-strategy: semver (default) but when i change tag to 8 characters of SHA git commit, it not working it not even show logs (it just empty).

**To Reproduce**
Here is my yaml file:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-nexus
  namespace: argocd
  annotations: 
      argocd-image-updater.argoproj.io/image-list: image=****/voc/nodeapp
      argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
      argocd-image-updater.argoproj.io/git-branch: main
      argocd-image-updater.argoproj.io/write-back-target: kustomization
      argocd-image-updater.argoproj.io/image.force-update: "true"

      argocd-image-updater.argoproj.io/image.update-strategy: newest-build 
      argocd-image-updater.argoproj.io/image.ignore-tags: latest, master
      argocd-image-updater.argoproj.io/image.allow-tags: regexp:^[0-9a-f]{8}$
spec:
  project: default
  source:
    repoURL: https://gitlab.com/van1122/project-argocd.git 
    targetRevision: HEAD
    path: image-nexus-service/base
  destination: 
    server: https://kubernetes.default.svc
    namespace: test-image-nexus 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
``` 

**Expected behavior**
When code change in git, a workflow will run to build and push image with a tag is first 8 characters and i want argocd image updater monitoring image registry and automation update new tag to file kustomization.yaml 

**Additional context**
I also give credential of image registry for argocd-image-updater

**Version**
latest (sha256:b3622d981368b5dc31e7d85545c3572e4a1c990cbe2403f8bb8053aa70766672)

**Logs**
I don't know why but when i use update-strategy: newest-build there not print logs, it completely empty. When update-strategy is semver everything working fine (have logs)
