### ISSUE TITLE
Digest Update Strategy Incorrectly Adding "Latest" Tag

### ISSUE THREAD

**Issue by patajones** [argoproj-labs/argocd-image-updater#716]
**Describe the bug**
I'm experiencing an issue with the ArgoCD Image Updater when using the digest update strategy. The problem occurs when the image tag is set incorrectly to "latest@sha256:<hash>" instead of the expected "@sha256:<hash>" or "develop@sha256:<hash>". There is no "latest" image with the given hash.

**To Reproduce**

1. Configure the ArgoCD Image Updater with the following annotations:
```
annotations:
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/image-list: my-service=my.registry.com/project/my-service:develop
  argocd-image-updater.argoproj.io/my-service.helm.image-name: my-service.image.name
  argocd-image-updater.argoproj.io/my-service.helm.image-tag: my-service.image.tag
  argocd-image-updater.argoproj.io/my-service.update-strategy: digest
```
2. Push a new image to the registry with the tag "develop".
3. Observe the updated image parameters in the `.argocd-source-<appName>.yaml` file

**Expected behavior**

The expected image tag in the parameter file should be:

```
- name: my-service.image.tag
  value: @sha256:603a0a9768b20bc4e3494361788cb0aec4ca7239dfec93db44f2593a50ad029a
  forcestring: true
```

or at most:

```
- name: my-service.image.tag
  value: develop@sha256:603a0a9768b20bc4e3494361788cb0aec4ca7239dfec93db44f2593a50ad029a
  forcestring: true
```

but the image tag in the parameter foi a

```
- name: my-service.image.tag
  value: latest@sha256:603a0a9768b20bc4e3494361788cb0aec4ca7239dfec93db44f2593a50ad029a
  forcestring: true
```

**Additional context**
I also tried using the annotation argocd-image-updater.argoproj.io/my-service.image.allow-tags: regexp:^develop$, but the same error occurred.

**Version**
`argocd 6.7.18`
`argocd-image-updater 8.9.7`

**Logs**

**Comment by istepanov** [comment]
I have a similar issue. My ArgoCD application contains two images, and the annotations looks like this:

    argocd-image-updater.argoproj.io/image-list: >
      auth-backend=<redacted>.dkr.ecr.us-west-1.amazonaws.com/auth-backend:master,
      auth-frontend=<redacted>.dkr.ecr.us-west-1.amazonaws.com/auth-frontend:master,
    argocd-image-updater.argoproj.io/auth-backend.update-strategy: digest
    argocd-image-updater.argoproj.io/auth-backend.force-update: "true"
    argocd-image-updater.argoproj.io/auth-backend.helm.image-name: backend.image.name
    argocd-image-updater.argoproj.io/auth-backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/auth-frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/auth-frontend.force-update: "true"
    argocd-image-updater.argoproj.io/auth-frontend.helm.image-name: frontend.image.name
    argocd-image-updater.argoproj.io/auth-frontend.helm.image-tag: frontend.image.tag

For some reason the updater correctly puts `master` tag for `auth-backend` (so it looks like `.../auth-backend:master@sha256:...`), but `auth-frontend` image gets `latest` tag instead (`.../auth-frontend:latest@sha256:...`).

I'm aware that it does not affect the actual functionality since the tag name is ignored if an image digest is present. The updater puts the correct image digests.  But it is definitely makes things more confusing - we use `latest` tags for test images and `master` for prod images and seeing a "wrong" tag on a production deploy raises concerns within the team.

**Comment by str1k3r** [comment]
I have the same issue. 

Between updates image updater  changing tag value from %specified_tag% -> latest and if tag was latest -> %specified_tag%.

Seems like only cosmetic issues, but looks weird

I'm using shared annotation for digest and also tried to annotate every image with dedicated update-strategy annotation as  @istepanov did. No difference.

**Comment by Eletmetrix** [comment]
same bug appears in my configuration either. my configuration looks like this:

```
argocd-image-updater.argoproj.io/image-list: "baffserver=10.1.0.128/baff-images/baffserver:dev-latest,baffabpserver=10.1.0.128/baff-images/baffserver:dev-abp-latest"
argocd-image-updater.argoproj.io/write-back-method: git
argocd-image-updater.argoproj.io/baffserver.update-strategy: digest
argocd-image-updater.argoproj.io/baffserver.allow-tags: regexp:^dev-latest$
argocd-image-updater.argoproj.io/baffserver.ignore-tags: dev-abp-latest, latest
argocd-image-updater.argoproj.io/baffserver.container: baffserver
argocd-image-updater.argoproj.io/baffserver.pull-secret: pullsecret:argocd/harbor-cred
argocd-image-updater.argoproj.io/baffserver.helm.image-name: baff_server.name
argocd-image-updater.argoproj.io/baffserver.helm.image-tag: baff_server.tag
argocd-image-updater.argoproj.io/baffabpserver.update-strategy: digest
argocd-image-updater.argoproj.io/baffabpserver.allow-tags: regexp:^dev-abp-latest$
argocd-image-updater.argoproj.io/baffabpserver.ignore-tags: dev-latest, latest
argocd-image-updater.argoproj.io/baffabpserver.container: baffabpserver
argocd-image-updater.argoproj.io/baffabpserver.pull-secret: pullsecret:argocd/harbor-cred
argocd-image-updater.argoproj.io/baffabpserver.helm.image-name: baff_abp_server.name
argocd-image-updater.argoproj.io/baffabpserver.helm.image-tag: baff_abp_server.tag
```

`dev-abp-latest` constantly changing to `latest` and changes back again. keeps doing this infinitely.

**Comment by ceelian** [comment]
To be honest, what I observed is not just a cosmetic issue in the following setup:

- A single Helm chart deploys multiple pods, each using a different container image.

In the demo case, this was appA and appB.
The expectation is that only the pod whose image actually changed is restarted, while the other pod remains untouched.

## Configuration

This is the ImageUpdater resource I’m using (version **v1.0.1**).
The intention is that only images tagged with main (which is a moving tag updated on every commit to the main branch) are updated to the latest digest.

```yaml
applicationRefs:
  - namePattern: "demo-app-dev"
    images:
      - alias: "demo-app-a"
        imageName: "myregistry/demo-app-a:main"
        commonUpdateSettings:
          updateStrategy: "digest"
        manifestTargets:
          helm:
            name: "appA.image.repository"
            tag: "appA.image.tag"

      - alias: "demo-app-b"
        imageName: "myregistry/demo-app-b:main"
        commonUpdateSettings:
          updateStrategy: "digest"
        manifestTargets:
          helm:
            name: "appB.image.repository"
            tag: "appB.image.tag"
```
## Timeline

1. A new image is pushed: `demo-app-a:main`

1. Image Updater writes back a commit with the new digest for `demo-app-a`
1. A new image is pushed: `demo-app-b:main`
1. Image Updater writes back a commit with the new digest for `demo-app-b` **and** changes the tag of `demo-app-a` from `main` to `latest` (even though the digest did not change)

## Resulting State (after step 4)

```yaml
appA:
  image:
    repository: myregistry/demo-app-a
    tag: "main@sha256:f86ce01b5fa6f1ccf4fbf52c10297a3dfb23747e01411ed81441875f6a9fb41a"   # state at step 3
    tag: "latest@sha256:f86ce01b5fa6f1ccf4fbf52c10297a3dfb23747e01411ed81441875f6a9fb41a" # new writeback at step 4

appB:
  image:
    repository: myregistry/demo-app-b
    tag: "latest@sha256:5f67e6d0e53c9ed93f9465bca076e2ba60692eda8a2d08ee6668d4d31dcf979e"  # state at step 3
    tag: "main@sha256:dd3894f3a65c62a0982f31718cf198920e84e7f94e63cd243de6dc66b92f6661"    # new writeback at step 4

```

## Problem

Although the **image digest for appA did not change**, the **tag name changed** from main to latest.
This causes Argo CD to detect a manifest change and **restart the appA pod**, even though it is effectively running the exact same image.

This leads to **unnecessary pod restarts**, which is an undesirable side effect of this behavior.

Notably, **both image entries are modified**, even though only one image actually changed in the registry.

## Workaround / Observation

The issue disappears if latest is used explicitly:

```yaml
imageName: "myregistry/demo-app-a:latest"
```

instead of:
```yaml
imageName: "myregistry/demo-app-a:main"
```

However, this effectively forces the use of the latest tag only, which defeats the purpose of using a moving main tag with digest-based updates in this scenario.

## Expected Behavior

- Either the tag name is omitted entirely and only the image digest (`sha256:…`) is used. This would avoid any unnecessary manifest changes.
- Or, if a tag name is present, it should remain exactly as specified in `imageName`
