### ISSUE TITLE
argocd-image-updater complains that "latest" strategy has been renamed to "newest-build", even though I'm using "newest-build"

### ISSUE THREAD

**Issue by clambin** [argoproj-labs/argocd-image-updater#730]
**Describe the bug**
Weird one:  argcd-image-updater v0.13.1 complains that strategy "latest" is deprecated, even though I'm already using "newest-build":

```
time="2024-05-31T15:22:32Z" level=warning msg="\"latest\" strategy has been renamed to \"newest-build\". Please switch to the new convention as support for the old naming convention will be removed in future versions." image_alias=tado 
```

application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tado
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: tado=ghcr.io/clambin/tado-monitor
    argocd-image-updater.argoproj.io/tado.update-strategy: newest-build
spec:
...
```

**Version**
v0.13.1

**Logs**
```
time="2024-05-31T15:22:32Z" level=info msg="Starting image update cycle, considering 20 annotated application(s) for update"
time="2024-05-31T15:22:32Z" level=warning msg="\"latest\" strategy has been renamed to \"newest-build\". Please switch to the new convention as support for the old naming convention will be removed in future versions." image_alias=tado image_name=ghcr.io/clambin/tado-monitor registry_url=ghcr.io
time="2024-05-31T15:22:33Z" level=warning msg="\"latest\" strategy has been renamed to \"newest-build\". Please switch to the new convention as support for the old naming convention will be removed in future versions." image_alias=solaredge image_name=ghcr.io/clambin/solaredge registry_url=ghcr.io
time="2024-05-31T15:22:33Z" level=warning msg="\"latest\" strategy has been renamed to \"newest-build\". Please switch to the new convention as support for the old naming convention will be removed in future versions." image_alias=exporter image_name=ghcr.io/clambin/github-exporter registry_url=ghcr.io
```
