### ISSUE TITLE
cannot use helm chart from public helm chart repositories

### ISSUE THREAD

**Issue by josedev-union** [argoproj-labs/argocd-image-updater#739]
**Describe the bug**
I deploy an application using airflow helm chart from https://airflow.apache.org chart repository. I can see that argocd-image-updater tries to push `.argocd-source-<appName>.yaml` file to the apache public helm chart repository, not to my application manifest git repo.

**To Reproduce**
Here is the application spec yaml file.
```yaml
metadata:
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/image-updater-gitops-repo
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: main=mydocker/airflow:2.8.3
    argocd-image-updater.argoproj.io/main.update-strategy: digest
    argocd-image-updater.argoproj.io/main.helm.image-name: images.airflow.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: images.airflow.tag
  name: airflow-staging
spec:
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.13.1
    helm:
      releaseName: airflow-staging
      values: |
        images:
          airflow:
            repository: mydocker/airflow
            tag: 2.8.3
```

**Expected behavior**
`.argocd-source-<appName>.yaml`  should be pushed to my own git repo, not to helm chart's repo.
