### ISSUE TITLE
Only use the last Registeries

### ISSUE THREAD

**Issue by MahdadGhasemian** [argoproj-labs/argocd-image-updater#742]
**Describe the bug**
When I define multiple regsitery which all of them are from gitlab (different groups), the image updater will only use the last repository.

**To Reproduce**
configmap file:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Gilab Registry 1
        api_url: https://registry.gitlab.com
        # prefix: registry.gitlab.com
        ping: yes
        credentials: secret:argocd/gitlabregistry#token
        credsexpire: 6h
        limit: 100
        default: true
        defaultns: library
      - name: Gilab Registry 2
        api_url: https://registry.gitlab.com
        prefix: registry.gitlab.com
        ping: yes
        credentials: secret:argocd/gitlabregistry2#token
        credsexpire: 6h
        limit: 100
        default: false
        defaultns: library
```
        
**Expected behavior**
To use both resigteries

**Version**
argocd-image-updater v0.12.2+1aa317c

**Logs**
$ kubectl logs pod/argocd-image-updater-77fd667b5-nrp22 -n argocd
time="2024-06-12T23:50:46Z" level=info msg="argocd-image-updater v0.12.2+1aa317c starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2024-06-12T23:50:46Z" level=warning msg="commit message template at /app/config/commit.template does not exist, using default"
time="2024-06-12T23:50:46Z" level=info msg="Loaded 2 registry configurations from /app/config/registries.conf"
time="2024-06-12T23:50:46Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=true, plaintext=false]"
time="2024-06-12T23:50:46Z" level=info msg="Starting health probe server TCP port=8080"
time="2024-06-12T23:50:46Z" level=info msg="Starting metrics server on TCP port=8081"
time="2024-06-12T23:50:46Z" level=info msg="Warming up image cache"
time="2024-06-12T23:50:47Z" level=error msg="Could not get tags from registry: Get \"https://registry.gitlab.com/v2/project-path/master/tags/list\": denied: access forbidden"
