### ISSUE TITLE
Git write-back-target helmvalues does not replace tag and repo in the image section

### ISSUE THREAD

**Issue by zagr0** [argoproj-labs/argocd-image-updater#744]
**Describe the bug**
Image updater not able to find `tag` and `repository` within `image` hierarchy to replace values, instead it adds new entries `image.tag` and `image.repository`.

Helm `values.yaml` file used:
```
image:
  repository: my.repo.domain/common/app
  tag: 0.0.6-SNAPSHOT_3ced321a
```

The commited result by image updater in git:
```
image:
  repository: my.repo.domain/common/app
  tag: 0.0.6-SNAPSHOT_3ced321a
image.repository: my.repo.domain/common/app
image.tag: 0.0.5_b579c34b
```

**To Reproduce**
Configure application with annotations to update image tag with helmvales:
```
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=my.repo.doamin/common/app
    argocd-image-updater.argoproj.io/main.pull-secret: pullsecret:argocd/registry
    argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/main.update-strategy: newest-build
    argocd-image-updater.argoproj.io/main.allow-tags: regexp:^[0-9]+.[0-9]+.[0-9+]_[0-9a-f]{8}$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds-ssh
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:./helm/app/values.yaml
    argocd-image-updater.argoproj.io/git-repository: git@my.repo.domain:common/deploy.git
    argocd-image-updater.argoproj.io/git-branch: master
``` 
with the `./helm/app/values.yaml` file content from example above.

**Expected behavior**
We expect to have updated tag and repo inside image section in `values.yaml` like:
```
image:
  repository: my.repo.domain/common/app
  tag: 0.0.5_b579c34b
```

**Version**
This is latest build from master, because we need the latest fixes for helmvalues git write-back
