### ISSUE TITLE
Optionally allow Image Updater usage via CRD rather than just annotations

### ISSUE THREAD

**Issue by seanturner026** [argoproj-labs/argocd-image-updater#747]
**Is your feature request related to a problem? Please describe.**

I've been exploring `ApplicationSets` recently, and I am also a happy Image Updater user. Perhaps I'm not quite doing it right; however, it seems like I need to use individual generators when the e.g. ECR Repository name doesn't match up with Directory name that is templated with the `path` (`{{ index .path.segments 2 }}`). 

Consider the below `ApplicationSet`, which applies Image Updater Annotations:

<details><summary>ApplicationSet yaml</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        # This deploys an Image Updater supported application because of the presence of `values.images`.
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          - path: apps/data/http-server/overlays/staging
        values:
          name: "{{ index .path.segments 2 }}-{{ index .path.segments 4 }}"
          images: seanturner026/kube-playground-http-server:latest
          strategy: digest

    - git:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          - path: apps/infra/*/overlays/staging
        values:
          name: "{{ index .path.segments 2 }}"

  template:
    metadata:
      name: "{{ .values.name }}"
      labels:
        team: "{{ index .path.segments 1 }}"
        environment: "{{ index .path.segments 4 }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .values.name }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
        {{- if index .values "images" }}
        argocd-image-updater.argoproj.io/image-list: {{ .values.images }}
        argocd-image-updater.argoproj.io/update-strategy: {{ .values.strategy }}
        argocd-image-updater.argoproj.io/write-back-method: argocd
        {{- end }}
```

</details>

This would potentially need `n git generators` depending on how many applications are leveraging Image Updater. Additionally, even if the name is perfect every time not all images are in ECR which make template-ing more complicated. Things are also made more complicated template-wise when helm or kustomize specific annotations are needed.

**Describe the solution you'd like**

I think it would be interesting if the operating loop for Image Updater were expanded to scan for `Application` _and also_ for `ImageUpdaterApplicationConfiguration`, where `ImageUpdaterApplicationConfiguration` would be a configmap-like resource. This would likely be deployed by the corresponding Application, and would likely override any configuration on the Application annotations.

```yaml
apiVersion: argoproj.io/v1alpha1 (?)
kind: ImageUpdaterApplicationConfiguration
metadata:
  name: foo # potentially map this to the corresponding ApplicationName?
  namespace: argocd
spec:
  # https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/
  applicationName: str # Potentially used to map to the name of the associated ArgoCD Application?
  imageList: list(str)  # image_spec_list
  forceUpdate: list(str) # list of aliases to force updater
  updateStrategy: str
  allowTags: map(str) # specifies what Images are allowed to run which Tags
  pullSecrets: map(str) # specifies what Images rely on which set of credentials

  # and so on with support for the remaining Kustomize and Helm specific annotations
```

I mention linking an `ImageUpdaterApplicationConfiguration` to an Application with `spec.applicationName` or `metadata.name`, but, it would probably be best for Image Updater to manage whatever Application is managing the `ImageUpdaterApplicationConfiguration`. This would be better as linking resources with text in Kubernetes is flimsy and a leaky abstraction.

**Describe alternatives you've considered**

See above `ApplicationSet`.

**Additional context**

The necessary CRDs could likely be deployed / managed along with ArgoCD CRDs as there's interest in linking this project with ArgoCD.
