### ISSUE TITLE
Bug: repocreds do not GitHub App credentials

### ISSUE THREAD

**Issue by abatilo** [argoproj-labs/argocd-image-updater#754]
**Describe the bug**
Between version v0.12.2 and v0.13.1, it seems like some bug was introduced which is causing authentication failures when trying to write changes back to the git repository.

**To Reproduce**
I have the following `kind: Application` that works perfectly with `v0.12.2` and stops working at `v0.13.1`

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sudokurace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: app=911907402684.dkr.ecr.us-west-2.amazonaws.com/sudokurace
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/mentallyanimated/deployments.git
    targetRevision: HEAD
    path: sudokurace/base
    kustomize:

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
```

**Expected behavior**
I would expect `argocd-image-updater` could continue to write commits to the `spec.source.repoURL` after doing the upgrade.

**Additional context**
I'm using a GitHub App for authentication as documented [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/)

**Version**
v0.13.1

**Logs**
Here are trace level logs:
```
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=info msg="Setting new image to 911907402684.dkr.ecr.us-west-2.amazonaws.com/sudokurace:0004" alias=app application=sudokurace image_name=sudokurace image_tag=0003 registry=911907402684.dkr.ecr.us-west-2.amazonaws.com
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=trace msg="Setting Kustomize parameter 911907402684.dkr.ecr.us-west-2.amazonaws.com/sudokurace:0004" application=sudokurace
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=info msg="Successfully updated image '911907402684.dkr.ecr.us-west-2.amazonaws.com/sudokurace:0003' to '911907402684.dkr.ecr.us-west-2.amazonaws.com/sudokurace:0004', but pending spec update (dry run=false)" alias=app application=sudokurace image_name=sudokurace image_tag=0003 registry=911907402684.dkr.ecr.us-west-2.amazonaws.com
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=debug msg="Using commit message: build: automatic update of sudokurace\n\nupdates image sudokurace tag '0003' to '0004'\n"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=info msg="Committing 1 parameter update(s) for application sudokurace" application=sudokurace
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:28Z" level=info msg="Starting configmap/secret informers"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="Configmap/secret informer synced"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="Initializing https://github.com/mentallyanimated/deployments.git to /tmp/git-sudokurace1680072880"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="rm -rf /tmp/git-sudokurace1680072880" dir= execID=77aa9
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="configmap informer cancelled"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="secrets informer cancelled"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg=Trace args="[rm -rf /tmp/git-sudokurace1680072880]" dir= operation_name="exec rm" time_ms=1.340393
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git-sudokurace1680072880 execID=97636
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'https://github.com': terminal prompts disabled" execID=97636
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git-sudokurace1680072880 operation_name="exec git" time_ms=124.54551599999999
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=info msg="Processing results: applications=8 images_considered=1 images_skipped=7 images_updated=0 errors=1"
argocd-image-updater-7959c4f976-db76q argocd-image-updater time="2024-06-22T20:44:30Z" level=error msg="Could not update application spec: `git fetch origin --tags --force` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'https://github.com': terminal prompts disabled" application=sudokurace
```
