### ISSUE TITLE
skipping app 'xxx' of type '' because it's not of supported source type

### ISSUE THREAD

**Issue by urupaud** [argoproj-labs/argocd-image-updater#784]
Hi Team,

We keep the helm charts of the applications in a git repository and seeing the above error in image updater container logs. Looking at [https://github.com/argoproj-labs/argocd-image-updater/blob/49825ec4df76b3d2571515525ac71b83efd30acc/pkg/argocd/argocd.go#L520-L533](https://github.com/argoproj-labs/argocd-image-updater/blob/49825ec4df76b3d2571515525ac71b83efd30acc/pkg/argocd/argocd.go#L520-L533), it seems like image updater supports only for helm chart repository, but not for git. Could you please advise?. Configurations as follow.

```
metadata:
      name: "{{ index .path.segments 1 }}-{{.environment}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{.environment}}/{{ index .path.segments 1 }}"
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: master
        argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./microservices/{{ index .path.segments 1 }}/{{.environment}}/values.yaml"
    spec:
      project: "default"
      source:
        repoURL: git@gitlab.com:xxx/xxx/argocd_applicationset.git
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - "{{.environment}}/values.yaml"
            - "values.yaml"
```

**Comment by chengfang** [comment]
What does the log say exactly (you can omit your app name)? We're getting application source type from argocd `app.Status.SourceType`, and it's odd if it returns something other than helm.

Also have you tried it with the latest release 0.14.0, or latest snapshot in master?

**Comment by urupaud** [comment]
Thanks for the reply @chengfang 

Yes, using the latest helm chart 0.11.0 with the latest image quay.io/argoprojlabs/argocd-image-updater:v0.14.0. Full log as follows. 

```
time=“2024-07-17T01:46:57Z” level=info msg=“argocd-image-updater v0.14.0+af844fe starting [loglevel:INFO, interval:2m0s, healthport:8080]”
time=“2024-07-17T01:46:57Z” level=info msg=“Loaded 1 registry configurations from /app/config/registries.conf”
time=“2024-07-17T01:46:57Z” level=info msg=“ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=false, plaintext=false]”
time=“2024-07-17T01:46:57Z” level=info msg=“Starting health probe server TCP port=8080"
time=“2024-07-17T01:46:57Z” level=info msg=“Starting metrics server on TCP port=8081"
time=“2024-07-17T01:46:57Z” level=info msg=“Warming up image cache”
time=“2024-07-17T01:46:57Z” level=info msg=“Finished cache warm-up, pre-loaded 0 meta data entries from 2 registries”
time=“2024-07-17T01:46:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:46:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:48:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:48:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:50:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:50:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:52:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:52:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:54:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:54:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:56:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:56:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T01:58:57Z” level=info msg=“Starting image update cycle, considering 3 annotated application(s) for update”
time=“2024-07-17T01:58:57Z” level=info msg=“Processing results: applications=3 images_considered=0 images_skipped=3 images_updated=0 errors=0"
time=“2024-07-17T02:00:58Z” level=warning msg=“skipping app ‘xxx-dev’ of type ‘’ because it’s not of supported source type” application=xxx-dev
time=“2024-07-17T02:00:58Z” level=warning msg=“skipping app ‘xxx-testing’ of type ‘’ because it’s not of supported source type” application=xxx-testing
time=“2024-07-17T02:00:58Z” level=info msg=“Starting image update cycle, considering 1 annotated application(s) for update”
time=“2024-07-17T02:00:58Z” level=info msg=“Processing results: applications=1 images_considered=0 images_skipped=1 images_updated=0 errors=0"
time=“2024-07-17T02:02:58Z” level=warning msg=“skipping app ‘xxx-dev’ of type ‘’ because it’s not of supported source type” application=xxx-dev
time=“2024-07-17T02:02:58Z” level=warning msg=“skipping app ‘xxx-testing’ of type ‘’ because it’s not of supported source type” application=xxx-testing
time=“2024-07-17T02:02:58Z” level=info msg=“Starting image update cycle, considering 1 annotated application(s) for update”
```

**Comment by urupaud** [comment]
also, note that i'm using applicationset controller to provision applications

**Comment by urupaud** [comment]
I can see the sourceType set to Helm in application status.

```
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  reconciledAt: "2024-07-19T03:39:21Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: xxx-dev
    namespace: dev
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: xxx-dev
    namespace: dev
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: xxx-dev
    namespace: dev
    status: Synced
    version: v1
  sourceType: Helm
  ```
