### ISSUE TITLE
Not Working with Multi Source App

### ISSUE THREAD

**Issue by sashokbg** [argoproj-labs/argocd-image-updater#785]
**Describe the bug**
When using a multi source helm application as described here https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
The image updater does not seem  to work. Changing the digest of my docker image is not detected for some reason.

**To Reproduce**
```
Create a multi source application. Configure the annotations on your argocd app:
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```

```
    argocd-image-updater.argoproj.io/image-list:
    argocd-image-updater.argoproj.io/api.helm.image-name: 
    argocd-image-updater.argoproj.io/api.helm.image-tag: dev
    argocd-image-updater.argoproj.io/api.update-strategy: digest
```
Use crane to retag your tag:

crane tag gitlab-registry.mycompany.net/my-project/backend:commit-sha dev

**Expected behavior**
The image updater should update the image if the digest changes

**Additional context**

**Version**
Image Updater version v0.12.0 and ArgoCD v2.9.5
