### ISSUE TITLE
Multiple commits when using digest strategy

### ISSUE THREAD

**Issue by mostafa-rz** [argoproj-labs/argocd-image-updater#794]
**Describe the bug**
I am using the digest strategy to update the images. Sometimes the image updater pushes multiple commits with the same sha256 value but different tags. It changes the tag to the latest, however, I mentioned in the image list to just use the staging tag. In the logs, for the second commit, it says that phpcli and nginx are updated but in the commit details it updated the phpfpm details.

It is happening for all the images, not specific ones and it happens randomly. But always overwrite the tag to the latest.

This is how I configure the image updater(I removed my private repository links):
```yaml
  annotations:
    # stop reconcile of application
    argocd.argoproj.io/skip-reconcile: "false"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:staging, phpfpm=phpfpm:staging, phpcli=phpcli:staging
    argocd-image-updater.argoproj.io/nginx.update-strategy: digest
    argocd-image-updater.argoproj.io/nginx.helm.image-name: nginx.appSoftwareImage
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: nginx.appSoftwareImageVersion
    argocd-image-updater.argoproj.io/phpfpm.update-strategy: digest
    argocd-image-updater.argoproj.io/phpfpm.helm.image-name: phpfpm.appSoftwareImage
    argocd-image-updater.argoproj.io/phpfpm.helm.image-tag: phpfpm.appSoftwareImageVersion
    argocd-image-updater.argoproj.io/phpcli.update-strategy: digest
    argocd-image-updater.argoproj.io/phpcli.helm.image-name: phpcli.appSoftwareImage
    argocd-image-updater.argoproj.io/phpcli.helm.image-tag: phpcli.appSoftwareImageVersion
```

These are two commits that pushed by image updater exactly after each other:
![image](https://github.com/user-attachments/assets/9b8266cc-2428-41e8-a8ae-bd7b1de80cda)

This is the first commit details:
![image](https://github.com/user-attachments/assets/1893be83-163b-4627-abc9-74bb7b870c7c)

This is the second commit details, as you can see it just changed the tag to the latest but the sha256 is the same as the previous commit.
![image](https://github.com/user-attachments/assets/f8a44482-0834-4d1b-bd7d-4bf632a8fad6)

**To Reproduce**
Use digest as the image update strategy.

**Expected behavior**
The second commit should never been happening.

**Additional context**

**Version**
```
argocd-image-updater: v0.12.2+1aa317c
  BuildDate: 2023-01-21T18:06:54Z
  GitCommit: 1aa317c3c57cdbd3e7f1b7accc99337f112a69e6
  GoVersion: go1.18.10
  GoCompiler: gc
  Platform: linux/amd64
```

**Logs**
```
time="2024-07-24T07:34:08Z" level=info msg="Starting image update cycle, considering 3 annotated application(s) for update"
time="2024-07-24T07:34:08Z" level=info msg="Setting new image to nginx@sha256:eb59aea8912e94968885b735e5b4059851618c432f0567c16be9be0504afa504" alias=nginx application=staging image_name=nginx image_tag="sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f" registry=...
time="2024-07-24T07:34:08Z" level=info msg="Successfully updated image 'nginx@sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f' to 'nginx@sha256:eb59aea8912e94968885b735e5b4059851618c432f0567c16be9be0504afa504', but pending spec update (dry run=false)" alias=nginx application=staging image_name=nginx image_tag="sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f" registry=...
time="2024-07-24T07:34:09Z" level=info msg="Setting new image to phpfpm@sha256:6d20c242f83747fe587565a5fe013e8c8ae5f8e9389419c172dbe911cf89c18a" alias=phpfpm application=staging image_name=phpfpm image_tag="sha256:f36e52f6425e53ea399cfb53725da79182bc8011659c77bbec0453ed0aebab6b" registry=...
time="2024-07-24T07:34:09Z" level=info msg="Successfully updated image 'phpfpm@sha256:f36e52f6425e53ea399cfb53725da79182bc8011659c77bbec0453ed0aebab6b' to 'phpfpm@sha256:6d20c242f83747fe587565a5fe013e8c8ae5f8e9389419c172dbe911cf89c18a', but pending spec update (dry run=false)" alias=phpfpm application=staging image_name=phpfpm image_tag="sha256:f36e52f6425e53ea399cfb53725da79182bc8011659c77bbec0453ed0aebab6b" registry=...
time="2024-07-24T07:34:09Z" level=info msg="Setting new image to phpcli@sha256:6ee1b02bbbfbaecb797fef48aee8009a9d7bedd23ccc10e3aeddf069b9bc19d9" alias=phpcli application=staging image_name=phpcli image_tag="sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47" registry=...
time="2024-07-24T07:34:09Z" level=info msg="Successfully updated image 'phpcli@sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47' to 'phpcli@sha256:6ee1b02bbbfbaecb797fef48aee8009a9d7bedd23ccc10e3aeddf069b9bc19d9', but pending spec update (dry run=false)" alias=phpcli application=staging image_name=phpcli image_tag="sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47" registry=...
time="2024-07-24T07:34:09Z" level=info msg="Committing 3 parameter update(s) for application staging" application=staging

-----------------

time="2024-07-24T07:35:15Z" level=info msg="Starting image update cycle, considering 3 annotated application(s) for update"
time="2024-07-24T07:35:15Z" level=info msg="Setting new image to nginx@sha256:eb59aea8912e94968885b735e5b4059851618c432f0567c16be9be0504afa504" alias=nginx application=staging image_name=nginx image_tag="sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f" registry=...
time="2024-07-24T07:35:15Z" level=info msg="Successfully updated image 'nginx@sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f' to 'nginx@sha256:eb59aea8912e94968885b735e5b4059851618c432f0567c16be9be0504afa504', but pending spec update (dry run=false)" alias=nginx application=staging image_name=nginx image_tag="sha256:4652d7d89eebb518ea2cc08f9103b71c1565892a24604625cf319286233c333f" registry=...
time="2024-07-24T07:35:16Z" level=info msg="phpcli@sha256:6ee1b02bbbfbaecb797fef48aee8009a9d7bedd23ccc10e3aeddf069b9bc19d9" alias=phpcli application=staging image_name=phpcli image_tag="sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47" registry=...
time="2024-07-24T07:35:16Z" level=info msg="Successfully updated image 'phpcli@sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47' to 'phpcli@sha256:6ee1b02bbbfbaecb797fef48aee8009a9d7bedd23ccc10e3aeddf069b9bc19d9', but pending spec update (dry run=false)" alias=phpcli application=staging image_name=phpcli image_tag="sha256:908c23110ad07f9dd0bdb357d16cc7c4ddb8e9d6dde05cdda47574e095aedd47" registry=...
time="2024-07-24T07:35:16Z" level=info msg="Committing 2 parameter update(s) for application staging" application=staging
```
