### ISSUE TITLE
ArgoCD fails to Sync image update for Helm, succeeds for Kustomize

### ISSUE THREAD

**Issue by kallentrustle** [argoproj-labs/argocd-image-updater#833]
**Describe the bug**
My test case app is in 2 different layouts. One is Kustomize, one is Helm. Ultimately we want to go with Helm. They both deploy successfully by ArgoCD. ArgoCD Image Updater (AIU) detects updated image for both and it successfully adds the .argocd-source* file to gitops. After AIU updates gitops, ArgoCD polls gitops: The test app running as Kustomize is successfully updated, the Helm test app is not. It's as if ArgoCD doesn't see the update.

I figure I'm doing something wrong, rather than this being a bug. Help greatly appreciated!

**Application beep-int-helm**
```
beep-int-helm-staging.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beep-int-helm-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: beep-int=us-central1-docker.pkg.dev/PROJECT_ID/boop-repo/beep-int/beep-int
    argocd-image-updater.argoproj.io/beep-int.update-strategy: newest-build
    argocd-image-updater.argoproj.io/beep-int.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/beep-int.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: git@github.com:MYDOMAIN/gitops.git
    targetRevision: poc
    path: hack/apps/beep-int-helm
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true

gitops: beep-int-helm $ tree -a .
.
├── .argocd-source-beep-int-helm-dev.yaml
├── .argocd-source-beep-int-helm-prod.yaml
├── .argocd-source-beep-int-helm-staging.yaml
├── .helmignore
├── Chart.yaml
├── README.md
├── templates
│   └── runservice.yaml
├── values-dev.yaml
├── values-prod.yaml
├── values-staging.yaml
└── values.yaml
```

**Application beep-int-kust**
```
beep-int-kust-staging.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beep-int-kust-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: beep-int=us-central1-docker.pkg.dev/PROJECT_ID/boop-repo/beep-int/beep-int
    argocd-image-updater.argoproj.io/beep-int.update-strategy: newest-build
    argocd-image-updater.argoproj.io/beep-int.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/beep-int.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: git@github.com:MYDOMAIN/gitops.git
    targetRevision: poc
    path: hack/apps/beep-int-kust/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true


gitops: beep-int-kust $ tree -a .
.
├── README.md
├── base
│   ├── kustomization.yaml
│   ├── runservice.yaml
└── overlays
    ├── dev
    │   ├── .argocd-source-beep-int-kust-dev.yaml
    │   ├── kustomization.yaml
    │   └── runservice-patch.yaml
    ├── prod
    │   ├── .argocd-source-beep-int-kust-prod.yaml
    │   ├── kustomization.yaml
    │   └── runservice-patch.yaml
    └── staging
        ├── .argocd-source-beep-int-kust-staging.yaml
        ├── kustomization.yaml
        └── runservice-patch.yaml
```

**Failing case:**
Here's what happens for the failing case, my test app using Helm.

1) deploy app with ArgoCD using manifest beep-int-helm-staging.yaml with an older image tag.
2) AIU polls our package repo and sees there's a newer package
3) AIU updates gitops repo, creating file .argocd-source-beep-int-helm-staging.yaml
```
gitops: beep-int-helm $ cat .argocd-source-beep-int-helm-staging.yaml
helm:
  parameters:
  - name: image.name
    value: us-central1-docker.pkg.dev/PROJECT_ID/boop-repo/beep-int/beep-int
    forcestring: true
  - name: image.tag
    value: b48d028
    forcestring: true
```
4) I hit refresh button on ArgoCD UI. ArgoCD does nothing. Here's the log:

```
time="2024-08-13T17:27:20Z" level=info msg="Refreshing app status (normal refresh requested), level (3)" application=argocd/beep-int-helm-staging
time="2024-08-13T17:27:20Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: staging)" application=argocd/beep-int-helm-staging
time="2024-08-13T17:27:23Z" level=info msg="GetRepoObjs stats" application=argocd/beep-int-helm-staging build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=3127 unmarshal_ms=3126 version_ms=0
time="2024-08-13T17:27:23Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"namespace\":\"staging\",\"server\":\"https://kubernetes.default.svc\"},\"source\":{\"helm\":{\"valueFiles\":[\"values.yaml\",\"values-staging.yaml\"]},\"path\":\"hack/apps/beep-int-helm\",\"repoURL\":\"git@github.com:MYDOMAIN/gitops.git\",\"targetRevision\":\"poc\"}}}}}" application=argocd/beep-int-helm-staging
time="2024-08-13T17:27:23Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/beep-int-helm-staging
time="2024-08-13T17:27:24Z" level=info msg="Update successful" application=argocd/beep-int-helm-staging
time="2024-08-13T17:27:24Z" level=info msg="Reconciliation completed" application=argocd/beep-int-helm-staging dedup_ms=0 dest-name= dest-namespace=staging dest-server="https://kubernetes.default.svc" diff_ms=3 fields.level=3 git_ms=3127 health_ms=0 live_ms=0 patch_ms=20 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=3178
```

**Succeeding case:**
Here's what happens for the working case, my test app using Kustomize

1) deploy app with ArgoCD using manifest beep-int-kust-staging.yaml with an older image tag.
2) AIU polls our package repo and sees there's a newer package
3) AIU updates gitops repo, creating file .argocd-source-beep-int-kust-staging.yaml
```
beep-int-kust $ cat overlays/staging/.argocd-source-beep-int-kust-staging.yaml
kustomize:
  images:
  - us-central1-docker.pkg.dev/PROJECT_ID/boop-repo/beep-int/beep-int:b48d028
```

4) I hit refresh button on ArgoCD UI. ArgoCD Syncs the update successfully. Here's the log:

```
time="2024-08-13T05:14:16Z" level=info msg="Refreshing app status (normal refresh requested), level (3)" application=argocd/beep-int-kust-staging
time="2024-08-13T05:14:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: staging)" application=argocd/beep-int-kust-staging
time="2024-08-13T05:14:20Z" level=info msg="GetRepoObjs stats" application=argocd/beep-int-kust-staging build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=3279 unmarshal_ms=3278 version_ms=0
time="2024-08-13T05:14:20Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"namespace\":\"staging\",\"server\":\"https://kubernetes.default.svc\"},\"source\":{\"path\":\"hack/apps/beep-int-kust/overlays/staging\",\"repoURL\":\"git@github.com:MYDOMAIN/gitops.git\",\"targetRevision\":\"poc\"}}}}}" application=argocd/beep-int-kust-staging
time="2024-08-13T05:14:20Z" level=info msg="Initiated automated sync to '3988291092e99973d251c0bfe07d2968c86b8d3f'" application=beep-int-kust-staging dest-namespace=staging dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2024-08-13T05:14:20Z" level=info msg="Initiated automated sync to '3988291092e99973d251c0bfe07d2968c86b8d3f'" application=argocd/beep-int-kust-staging
time="2024-08-13T05:14:20Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=beep-int-kust-staging dest-namespace=staging dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2024-08-13T05:14:20Z" level=info msg="updated 'argocd/beep-int-kust-staging' operation (phase: Running)" appNamespace=argocd application=beep-int-kust-staging project=main
...snip I assume that's enough log to see it succeeded, compared to the failing example..
```

**Version**
```
helm chart: argocd-image-updater-0.10.2
AIU version: v0.13.1

$ argocd version
argocd: v2.12.0+ec30a48
  BuildDate: 2024-08-05T15:31:14Z
  GitCommit: ec30a48bce7a60046836e481cd2160e28c59231d
  GitTreeState: clean
  GoVersion: go1.22.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.7+e4a0246
  BuildDate: 2024-07-24T09:33:49Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**
In-line above.
