### ISSUE TITLE
Could not update application spec: could not find an image-tag annotation for image

### ISSUE THREAD

**Issue by yazbekhe** [argoproj-labs/argocd-image-updater#840]
**Describe the bug**
when using  canonical name of the image for helm the image-update is not able to write back to git 

**To Reproduce**
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mytest
  namespace: argocd
spec:
  ignoreApplicationDifferences: 
    - jqPathExpressions:
        - .spec.sources[0].helm.parameters
  generators:
    - git:
        repoURL: https://dev.azure.com/xxx/mygit/_git/my-test
        revision: master 
        directories:
          - path: test/helm-values/plantuml/auto-generated/dev/* 
  template:
    metadata:
      name: "{{path.basename}}-plantuml" 
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: plantuml=dockerregistry.azurecr.io/devops/plantuml:dev 
        argocd-image-updater.argoproj.io/plantuml.update-strategy: digest
        argocd-image-updater.argoproj.io/plantuml.platforms: linux/amd64 
        argocd-image-updater.argoproj.io/plantuml.helm.image-spec:
          services.plantuml.containers.plantuml.image
        argocd-image-updater.argoproj.io/plantuml.force-update: "true" 
        argocd-image-updater.argoproj.io/git-repository: https://dev.azure.com/xxx/mygit/_git/my-test 
        argocd-image-updater.argoproj.io/git-branch: master 
        argocd-image-updater.argoproj.io/write-back-method: git 
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/private-repo-https  
        argocd-image-updater.argoproj.io/write-back-target: helmvalues:/test/helm-values/plantuml/auto-generated/dev/test/values.yaml 
    spec:
      project: default
      sources: #
        - chart: xxxdeploy 
          repoURL: "http://chartmuseum.mydomain.ca"
          targetRevision: ~0.3.0 
          helm:
            releaseName: "{{path.basename}}-plantuml" 
            valueFiles: 
              - $values/{{path}}/values.yaml 
      
        - repoURL: "https://dev.azure.com/xxx/mygit/_git/my-test"
          ref: values 
          targetRevision: master 
          directory:
            recurse: true

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}-plantuml" 
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true 
          - ApplyOutOfSyncOnly=true
```

my values files 
```
services:
  plantuml:
    containers:
      plantuml:
        image: dockerregistry.azurecr.io/devops/plantuml:dev
```
**Expected behavior**
i expected that my values file get updated. instead no wirte-back took place and even the pods were not updated with the new image sha256

**Additional context**

IF i remove the annotation "argocd-image-updater.argoproj.io/write-back-target" it works and the  file   .argocd-source-<appName>.yaml.  get created at the root of the repo

**Version**
v2.12.0+ec30a48

**Logs**
  level=error msg="Could not update application spec: could not find an image-tag annotation for image devops/plantuml" application=test-plantuml
