### ISSUE TITLE
Unable to write back to git helm values, key not found in the map

### ISSUE THREAD

**Issue by mimartin12** [argoproj-labs/argocd-image-updater#877]
**Describe the bug**
When using the `git` writeback method, image updater is unable to create the file in the branch with the helm value updates with an error:
 `time="2024-10-01T15:32:52Z" level=error msg="Could not update application spec: failed to set image parameter name value: key component not found in the map" application=test`

**To Reproduce**
Using the annotations:
```yaml
        argocd-image-updater.argoproj.io/image-list: admin=somewhere.azurecr.io/admin:{{.branch}}
        argocd-image-updater.argoproj.io/update-strategy: digest
        argocd-image-updater.argoproj.io/admin.helm.image-name: component.admin.image.name
        argocd-image-updater.argoproj.io/admin.helm.image-tag: component.admin.image.tag
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-repository: git@github.com:company/admin.git
        argocd-image-updater.argoproj.io/write-back-target: 'helmvalues:/envs/{{.branch}}.yaml'
        argocd-image-updater.argoproj.io/git-branch: '{{.branch}}'
```

The Helm chart supports the structure:
```yaml
component:
  admin:
    image:
      name: somewhere.azurecr.io/admin
      tag: dev
```

**Expected behavior**

When a new image is added to the ACR, the updater creates a file `/envs/{{.branch}}.yaml` on the branch `{{.branch}}` with the newly set values, `component.admin.image.name` and `component.admin.image.tag`.

**Additional context**

It's worth noting, if I create the file manually at `/envs/{{.branch}}.yaml` and add the structure:
```yaml
component:
  admin:
    image:
      name: somewhere.azurecr.io/admin
      tag: dev
```

The updates work.

**Version**
`0.14.0`

**Logs**
```
time="2024-10-01T15:32:52Z" level=error msg="Could not update application spec: failed to set image parameter name value: key component not found in the map" application=test
time="2024-10-01T15:32:52Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
time="2024-10-01T15:33:43Z" level=info msg="configmap informer cancelled"
time="2024-10-01T15:33:43Z" level=info msg="secrets informer cancelled"
```
