### ISSUE TITLE
Upgrading to v0.15.0 causing conflicts while updating apps

### ISSUE THREAD

**Issue by schahal** [argoproj-labs/argocd-image-updater#917]
**Describe the bug**

After upgrading to to v0.15.0 (as part of https://github.com/argoproj/argo-helm/releases/tag/argocd-image-updater-0.11.1) from v0.14.0, I started seeing the following messages:

```
...
2024-11-04 14:48:22.402 | time="2024-11-04T22:48:22Z" level=warning msg="conflict occurred while updating application: foo-app-remote-cluster, retrying... (5/7)
2024-11-04 14:48:21.739 | time="2024-11-04T22:48:21Z" level=warning msg="conflict occurred while updating application: baz-app-remote-cluster, retrying... (3/7)"
...
```

This would repeat for dozens of apps that get deployed to the remote cluster... and that symptom is likely due to the image updater adding overrides for unrelated apps.

For example, my app `foo` app spec was originally:

```
destination:
  namespace: foo
  server: https://<redacted>
project: foo
source:
  helm:
    ignoreMissingValueFiles: true
    parameters:
      - forceString: true
        name: foo.image.repository
        value: <redacted>.com/<redacted>/foo
      - forceString: true
        name: foo.image.tag
        value: latest@sha256:<redacted>
    releaseName: foo-app
    skipCrds: true
    valueFiles:
      - values.yaml
  path: charts/app
  repoURL: https://github.com/<redacted>/foo.git
  targetRevision: HEAD
syncPolicy:
  automated:
    prune: true
    selfHeal: false
```

But after the upgrade, the following **_additional_** parameters from _**other**_ apps were added:

```
      - forceString: true
        name: bar.image.repository
        value: <redacted>.com/<redacted>/bar
      - forceString: true
        name: bar.image.tag
        value: latest@sha256:<redacted>
      - forceString: true
        name: baz.image.repository
        value: <redacted>.com/<redacted>/baz
      - forceString: true
        name: baz.image.tag
        value: latest@sha256:<redacted>
```

This then manifested in ArgoCD unable to `Sync` due to errors like:

```
"Role/foo-app is part of applications argocd/bar-app foo-app-"
```

**To Reproduce**

1. Be running image-updater v0.14.0 (good)
2. Have a few (I have about a couple dozen) `Applications` with spec like above which syncs to a remote cluster
3. Upgrade image-updater to v0.15.0 (by upgrading to chart https://github.com/argoproj/argo-helm/releases/tag/argocd-image-updater-0.11.1 from 0.11.0)
4. Notice behavior above

**Expected behavior**

To work similar to v0.14.0 (i.e., no warnings/errors in logs and not cross-updating Applications incorrectly)

**Additional context**

Workaround:

1. Revert back to v0.14.0
5. Manually remove the extraneous ArgoCD parameters

**Version**

v0.15.0

**Logs**

`warning` and `error` logs arose from ~12:00 to 14:45 (when I was on v0.15.0)
 
<img width="1582" alt="Screenshot 2024-11-05 at 3 26 37 PM" src="https://github.com/user-attachments/assets/ecded63f-11a5-41da-918a-24c4c76fcf3c">

<details><summary>Those error/warn messages were all essentially this (Click to view):</summary>

```
2024-11-04 14:45:26.980 time="2024-11-04T22:45:26Z" level=warning msg="conflict occurred while updating application: <redacted>, retrying... (4/7)"
2024-11-04 14:45:26.801 time="2024-11-04T22:45:26Z" level=error msg="Could not update application spec: max retries(7) reached while updating application: <redacted>" application=<redacted>
```
