### ISSUE TITLE
Cannot use Github Container Registry

### ISSUE THREAD

**Issue by windsource** [argoproj-labs/argocd-image-updater#92]
**Describe the bug**
I want to use the new [Github Container Registry](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) ghcr.io but I get a strange error message "Could not get tags from registry: unexpected manifest schema was received from registry"

**To Reproduce**
My config map contains:

```yaml
  registries.conf: |
    registries:
    - name: Github Container Registry
      api_url: https://ghcr.io
      ping: no
      prefix: ghcr.io
      credentials: pullsecret:argocd-image-updater/regcred
```

**Expected behavior**
ghcr.io should be supported.

**Additional context**

**Version**
v0.6.1

**Logs**

```text
time="2020-09-24T21:00:36Z" level=info msg="argocd-image-updater v0.6.1 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2020-09-24T21:00:36Z" level=info msg="Loaded 1 registry configurations from /app/config/registries.conf"
time="2020-09-24T21:00:36Z" level=info msg="ArgoCD configuration: [server=argocd-server.argocd, auth_token=true, insecure=false, grpc_web=false, plaintext=true]"
time="2020-09-24T21:00:36Z" level=info msg="Starting health probe server TCP port=8080"
time="2020-09-24T21:00:36Z" level=info msg="Warming up image cache"
time="2020-09-24T21:00:37Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
time="2020-09-24T21:00:37Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 5 registries"
time="2020-09-24T21:00:37Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2020-09-24T21:00:38Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
time="2020-09-24T21:00:38Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
```

**Comment by jannfis** [comment]
Can you try with `tagsortmode: latest_first` configuration option for your registry configuration, so basically

```
  registries.conf: |
    registries:
    - name: Github Container Registry
      api_url: https://ghcr.io
      ping: no
      prefix: ghcr.io
      credentials: pullsecret:argocd-image-updater/regcred
      tagsortmode: latest_first
```

This will prevent fetching additional metadata (which GHCR does not support). The tags returned by GHCR are already sorted by the date they were pushed to the registry. 

Also, we should include the new prefix ghcr.io by default as alias for docker.pkg.github.com.

**Comment by windsource** [comment]
Now the pod is in CrashLoopBackOff:

```
time="2020-09-25T05:10:40Z" level=info msg="argocd-image-updater v0.6.1 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2020-09-25T05:10:40Z" level=error msg="Could not load registry configuration from /app/config/registries.conf: unknown tag sort mode for registry Github Container Registry: latest_first"
```

My whole ConfigMap looks like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  # Whether to use plain text connection (http) instead of TLS (https)
  argocd.plaintext: "true"
  registries.conf: |
    registries:
    - name: Github Container Registry
      api_url: https://ghcr.io
      ping: no
      prefix: ghcr.io
      credentials: pullsecret:argocd-image-updater/regcred
      tagsortmode: latest_first
```

Also I think that ghcr.io and docker.pkg.github.com should not be mixed up. They are both different registries with different implementations. ghcr.io is a new implementation which is current in public beta (see [blog post](https://github.blog/2020-09-01-introducing-github-container-registry/)) and was created due to limitations in docker.pkg.github.com (e.g. not being able to pull by digest). Finally ghcr.io will replace docker.pkg.github.com.

**Comment by windsource** [comment]
I checked the code and I think it should be `tagsortmode: latest-first` with a hyphen rather than an underscore. When I use that I still get an error:

```
time="2020-09-25T05:30:17Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
time="2020-09-25T05:30:17Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2020-09-25T05:30:18Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
time="2020-09-25T05:30:18Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
```

**Comment by jannfis** [comment]
> I checked the code and I think it should be `tagsortmode: latest-first` with a hyphen rather than an underscore. 

Oops, you are right! Thank you, I will update the documentation (and also add a hint that this is required for GHCR).

> When I use that I still get an error:
> ```
> time="2020-09-25T05:30:17Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
> time="2020-09-25T05:30:17Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
> time="2020-09-25T05:30:18Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
> time="2020-09-25T05:30:18Z" level=error msg="Could not get tags from registry: unexpected manifest schema was received from registry: application/vnd.docker.distribution.manifest.v2+json (registry may not support the manifest type(s) you want: [application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v1+json])" alias=techwiki application=techwiki image_name=windsource/techwiki image_tag=latest registry=ghcr.io
> ```

Hm, I have just pushed an image with two tags to ghcr.io, made them public and used the following configuration for the image updater:

```
registries:
- name: Github Container Registry
  api_url: https://ghcr.io
  ping: no
  prefix: ghcr.io
  tagsortmode: latest-first
```
When I run the updater on an application configured to use this image and annotated it correctly, it seems successful:
```
INFO[0240] Starting image update cycle, considering 1 annotated application(s) for update 
DEBU[0240] Processing application helm-guestbook        
DEBU[0240] Considering this image for update             alias=gb application=helm-guestbook image_name=jannfis/ks-guestbook-demo image_tag=0.1 registry=ghcr.io
DEBU[0240] Using version constraint '>=0.1' when looking for a new tag  alias=gb application=helm-guestbook image_name=jannfis/ks-guestbook-demo image_tag=0.1 registry=ghcr.io
DEBU[0241] found 2 from 2 tags eligible for consideration  image="ghcr.io/jannfis/ks-guestbook-demo:0.1"
INFO[0241] Setting new image to ghcr.io/jannfis/ks-guestbook-demo:0.2  alias=gb application=helm-guestbook image_name=jannfis/ks-guestbook-demo image_tag=0.1 registry=ghcr.io
DEBU[0241] target parameters: image-spec= image-name=image.repository, image-tag=image.tag  application=helm-guestbook image=ghcr.io/jannfis/ks-guestbook-demo
INFO[0241] Successfully updated image 'ghcr.io/jannfis/ks-guestbook-demo:0.1' to 'ghcr.io/jannfis/ks-guestbook-demo:0.2', but pending spec update (dry run=true)  alias=gb application=helm-guestbook image_name=jannfis/ks-guestbook-demo image_tag=0.1 registry=ghcr.io
INFO[0241] Dry run - not performing spec update          application=helm-guestbook
INFO[0241] Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0 
```
Can you please provide the image updater related annotations you used on your application, they might be the missing piece to the puzzle for reproducing the issue? Thanks!

**Comment by jannfis** [comment]
I think I have found the bug and fixed it with #93 - will prepare a v0.6.2 release containing the fix later this day

**Comment by windsource** [comment]
I use a private repo on ghcr.io with commit hashes as tags like ghcr.io/windsource/myrepo:b8b7c74. One tag is the 'latest' tag.

The application looks like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myrepo=ghcr.io/windsource/myrepo
    argocd-image-updater.argoproj.io/myrepo.update-strategy: latest
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: myapp
    repoURL: https://github.com/windsource/myapps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
```
