### ISSUE TITLE
Removed image references persist in Helm chart Git repository after removal from image-list

### ISSUE THREAD

**Issue by ravikiran-talluri** [argoproj-labs/argocd-image-updater#939]
**Describe the bug**
When using Argo CD Image Updater with Git write-back, removing an image from the argocd-image-updater.argoproj.io/image-list annotation removes it from the Argo CD Application manifest. However, references to this image persist in the .argocd-source-<appname>.yaml file committed back to the **Helm chart's** Git repository.

**To Reproduce**
1. Annotate an Argo CD Application with the argocd-image-updater.argoproj.io/image-list annotation, including image/s.
2. Allow the Image Updater to track and update the image.
3. Remove the image from the image-list annotation in the Application manifest.
4. Observe that while the image is removed from the Application manifest, references in the .argocd-source-<appname>.yaml file in the Helm chart repository are not cleaned up

**Expected behavior**
The Git write-back process should fully remove references to the deleted image from the .argocd-source-<appname>.yaml file, ensuring consistency between the Application manifest and the Helm chart Git repository.

**Additional context**
The removed image references are not properly cleaned from .argocd-source-<appname>.yaml during Git write-back, leading to potential issues with Helm chart consistency.

**Version**
15.1

**Comment by chengfang** [comment]
Does this extra image element in git repo cause any harm?  Currently we pass a changeList to the writer, and since the unregistered images will not be included in that changeList, so any existing images in git repo files will not be changed. We probably should also compare each existing image in git repo file against a updateableImages list to see if any image has been unregistered since last write.

**Comment by ravikiran-talluri** [comment]
The issue is problematic because if we forget to manually clean up the .argocd-source-.yaml file, Argo CD still deploys the removed image. This leads to unintended deployments and breaks synchronization between the Application manifest and the Helm chart repository.

To fix this, we should modify the Git write-back logic to compare the .argocd-source-.yaml file against updateableImages. Any image reference that was previously tracked but is no longer present in updateableImages should be removed during the write-back process. This would ensure consistency and prevent unwanted deployments. Would you agree that this is the right approach?

**Comment by chengfang** [comment]
On the other side, is there a case where the user wants to keep the persistent updates (params override) in .argocd-source-*.yaml file, sine these are valid updates from previous update cycles? But from now on, the user just wants to end the updating of a particular image by removing it from the image-list, while still honoring any previous updates.

**Comment by dkarpele** [comment]
Hi @ravikiran-talluri,
we **can** reproduce the issue (argocd-server: v2.14.6) that you described but I don't understand the exact use case. Could you also send us the `Application` manifest and especially the Helm chart's Git repository (or Kustomize) that you use, please? You mention "Argo CD still deploys the removed image.". I checked that if I completely remove the object (for example `Deployment`) from the Git repo and leave the image in .argocd-source-.yaml file, then ArgoCD **doesn't** deploy it. 

I tested with these 2 configs:
1 pod with 2 images:
```yaml
apiVersion: apps/v1
kind: Deployment
...
    spec:
      containers:
      - name: test-image
        image: 10.42.0.1:30000/test-image:1.0.0
      - name: guestbook
        image: gcr.io/heptio-images/ks-guestbook-demo:0.1
```

2 Deployment with different images:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-dep-0
...
    spec:
      containers:
      - name: test-image
        image: 10.42.0.1:30000/test-image:1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-dep-1
...
    spec:
      containers:
        - name: guestbook
          image: gcr.io/heptio-images/ks-guestbook-demo:0.1
```
