### ISSUE TITLE
ArgoCD doesn't see image tag in target branch from argocd-image-updater.argoproj.io/git-branch: :target parameter.

### ISSUE THREAD

**Issue by yury-stsefanovich** [argoproj-labs/argocd-image-updater#941]
**Describe the bug**
When I try to specify a target branch to commit for image updater argoCD doesn't catch image from the branch.

I have:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-app-set
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          - environment_name: "staging"
            eks_cluster: "cluster"
            namespace: "argo-test"
  template:
    metadata:
      name: '{{environment_name}}-test-app'
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/image-list: 'my.jfrog.io/docker-dev/test:latest'
        argocd-image-updater.argoproj.io/update-strategy: digest
        argocd-image-updater.argoproj.io/helm.image-name: image.name
        argocd-image-updater.argoproj.io/helm.image-tag: image.tag
        argocd-image-updater.argoproj.io/git-branch: image_updater_branch
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/helm/my-chart.git
        targetRevision: main
        path: helm/chart
        helm:
          releaseName: my-app
          ignoreMissingValueFiles: false
          valueFiles:
            - ../values/default.yaml
      destination:
        name: '{{eks_cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated: {}
```

Image updater successfully push new image tag with digest to image_updater_branch .argocd-source-staging-my-app.yaml file, but ArgoCD doesn't update deployment with the new tag from .argocd-source-staging-my-app.yaml file. 
Without argocd-image-updater.argoproj.io/git-branch: image_updater_branch annotation all works correctly, but I want to keep main branch protected and use image_updater_branch for image changes. 

**Expected behavior**
Image updater push new tag to image_updater_branch .argocd-source-staging-my-app.yaml file, argo update deployment's image after sync. 

**Version**
Image updater 0.15.1, ArgoCD 2.13.0
**Logs**
No any errors in logs.
