### ISSUE TITLE
latest strategy not work 

### ISSUE THREAD

**Issue by leezhihui** [argoproj-labs/argocd-image-updater#975]
**Describe the bug**
when I use these annotation with latest strategy like

```
argocd-image-updater.argoproj.io/image-list: yourtool=yourorg/yourimage
argocd-image-updater.argoproj.io/yourtool.update-strategy: latest
```
when the pipeline build a new tag with commit-id, it can not deploy or restart the pod and deploy it, just with this 

[docker.artifactory.com/zhihui](http://docker.artifactory.com/zhihui) time="2024-12-17T08:37:46Z" level=info msg="Successfully updated image '[test--docker.artifactory.com/zhihui:latest](http://test--docker.artifactory..com/zhihui:latest)' to '[test--docker.artifactory.com/zhihui:4c462997](http://test--docker.artifactory.com/zhihui:4c462997)', **but pending spec update (dry run=false)**

**To Reproduce**

**Expected behavior**
it should deployed the new generated tag in the image repo

**Additional context**

**Version**
Please tell us about the version you encountered the issue with
0.14.0
0.11.0

**Logs**
Please paste any relevant logs here

**Comment by chengfang** [comment]
Have you tried latest release 0.15.1, which contains a number of fixes and enhancements? It could be that image-updater failed to determine the timestamp of the new tag for some reason. See docs on newest-build strategy: https://argocd-image-updater.readthedocs.io/en/latest/basics/update-strategies/#latestnewest-build-update-to-the-most-recently-built-image

**Comment by leezhihui** [comment]
Successfully updated image 'test--docker.artifactory.com/zhihui:latest' to 'test--docker.artifactory.com/zhihui:4c462997

and this means?
actually it didnot used the image in effect

**Comment by leezhihui** [comment]
Pipeline will generate two images one is the commit tag: 46dhjcbn
One is the latest.
So if we need delete the latest, because they are all the frest

**Comment by leezhihui** [comment]
tried with v0.15.1,
and annotation like this 
```
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=iep--docker.artifactory.arm.com/zhihui
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/argocd.force-update: "true"
    argocd-image-updater.argoproj.io/myalias.helm.image-name: backstage.image.registry
    argocd-image-updater.argoproj.io/myalias.helm.image-tag: backstage.image.tag
```


error looks like

```
76
time="2024-12-23T07:29:00Z" level=debug msg="found 11 from 11 tags eligible for consideration" image="iep--docker.artifactory.arm.com/zhihui:latest"
75
time="2024-12-23T07:29:00Z" level=info msg="Setting new image to iep--docker.artifactory.arm.com/zhihui:34da755d" alias=myalias application=zhihui image_name=zhihui image_tag=latest registry=iep--docker.artifactory.arm.com
74
time="2024-12-23T07:29:00Z" level=debug msg="target parameters: image-spec= image-name=backstage.image.registry, image-tag=backstage.image.tag" application=zhihui image=iep--docker.artifactory.arm.com/zhihui namespace=argocd
73
time="2024-12-23T07:29:00Z" level=info msg="Successfully updated image 'iep--docker.artifactory.arm.com/zhihui:latest' to 'iep--docker.artifactory.arm.com/zhihui:34da755d', but pending spec update (dry run=false)" alias=myalias application=zhihui image_name=zhihui image_tag=latest registry=iep--docker.artifactory.arm.com
72
time="2024-12-23T07:29:00Z" level=debug msg="Using commit message: "
```

**Comment by leezhihui** [comment]
comment the  **repository: []**
and try again

the error like this


271 image: 'iep--docker.artifactory.arm.com/zhihui:latest' --->  271 | image: 'iep--docker.artifactory.arm.com****/zhihui/zhihui****:34da755d'

the spec have more than one repository like */zhihui/zhihui****:34da755d'




```
backstage:

  image:

    # -- Backstage image registry
    # registry: ghcr.io
    registry: iep--docker.artifactory.com

    # -- Backstage image repository
    # repository: backstage/backstage
    # repository: []

    # -- Backstage image tag (immutable tags are recommended)
    tag: latest
```
