### ISSUE TITLE
Customising the location of helm.image-tag

### ISSUE THREAD

**Issue by ForcemCS** [argoproj-labs/argocd-image-updater#991]
I use the helmfile plugin to deploy my gaming business, regarding the settings for each gaming suit I don't define them in values.yaml, but through a separate file, as in the following example
```
server:
- id: 10030
  name: operation
  runtype: 0
  siteid: 1
  parent: 0
  fight: flight01
  trade: trans01
  repo: xxxxxxxxx
  image: hdh5test
  tag: "20241204203734"
  opentime: 2024-12-05T10:14:22+08:00
  db: xxxxxx:30009:30:ccccccc
  ................
```

I want to use image updater to keep track of new images in the repository, a sample file looks like this
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hdh5-game
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
   .。。。。。。。。。。。。
  template:
    metadata:
      name: '{{.describe}}-{{.proj}}-game'
      annotations:
	    ...............
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-name: <How should I write？>
        argocd-image-updater.argoproj.io/hdh5-game.helm.image-tag: <How should I write？>

    spec:
      project: team-a
      sources:
      - repoURL: xxxxxxxxxxxxxxx/alls-hdh5.git
        path: helmfile_charts/hdh5
        targetRevision: HEAD
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'
.............

```
My helmfile chart is structured as follows:

```
root@debian:~/alls-hdh5/helmfile_charts# tree  -L 4   hdh5/
hdh5/
├── helmfile.yaml
└── servers
    ├── Chart.yaml
    ├── servers.yaml
    ├── templates
    │   ├── configmap-main.yaml
    │   ├── deployment.yaml
    │   ├── forward-service.yaml
    │   ├── _helpers.tpl
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   └── service.yaml
    └── values.yaml
```
